// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: abuse.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpReputation = `-- name: BumpReputation :one
INSERT INTO ip_reputation (subject_type, subject_value, score, updated_at)
VALUES ($1,$2,$3,now())
ON CONFLICT (subject_type, subject_value) DO UPDATE SET score = ip_reputation.score + EXCLUDED.score, updated_at = now()
RETURNING subject_type, subject_value, score, updated_at
`

type BumpReputationParams struct {
	SubjectType  string
	SubjectValue string
	Score        int32
}

func (q *Queries) BumpReputation(ctx context.Context, arg BumpReputationParams) (IpReputation, error) {
	row := q.db.QueryRow(ctx, bumpReputation, arg.SubjectType, arg.SubjectValue, arg.Score)
	var i IpReputation
	err := row.Scan(
		&i.SubjectType,
		&i.SubjectValue,
		&i.Score,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveQueueTokensByUser = `-- name: CountActiveQueueTokensByUser :one
SELECT count(*) FROM queue_tokens WHERE participant_id = $1 AND status IN ('WAITING','ALLOWED')
`

func (q *Queries) CountActiveQueueTokensByUser(ctx context.Context, participantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveQueueTokensByUser, participantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIPRule = `-- name: CreateIPRule :one
INSERT INTO ip_rules (cidr, rule, note, created_by) VALUES ($1,$2,$3,$4) RETURNING id, cidr, rule, note, created_by, created_at
`

type CreateIPRuleParams struct {
	Cidr      string
	Rule      string
	Note      pgtype.Text
	CreatedBy *uuid.UUID
}

func (q *Queries) CreateIPRule(ctx context.Context, arg CreateIPRuleParams) (IpRule, error) {
	row := q.db.QueryRow(ctx, createIPRule,
		arg.Cidr,
		arg.Rule,
		arg.Note,
		arg.CreatedBy,
	)
	var i IpRule
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.Rule,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlockedSubject = `-- name: DeleteBlockedSubject :exec
DELETE FROM blocked_subjects WHERE subject_type = $1 AND subject_value = $2
`

type DeleteBlockedSubjectParams struct {
	SubjectType  string
	SubjectValue string
}

func (q *Queries) DeleteBlockedSubject(ctx context.Context, arg DeleteBlockedSubjectParams) error {
	_, err := q.db.Exec(ctx, deleteBlockedSubject, arg.SubjectType, arg.SubjectValue)
	return err
}

const deleteIPRule = `-- name: DeleteIPRule :exec
DELETE FROM ip_rules WHERE id = $1
`

func (q *Queries) DeleteIPRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIPRule, id)
	return err
}

const getBlockedSubject = `-- name: GetBlockedSubject :one
SELECT id, subject_type, subject_value, reason, blocked_by, created_at, expires_at FROM blocked_subjects
WHERE subject_type = $1 AND subject_value = $2
  AND (expires_at IS NULL OR expires_at > now())
`

type GetBlockedSubjectParams struct {
	SubjectType  string
	SubjectValue string
}

func (q *Queries) GetBlockedSubject(ctx context.Context, arg GetBlockedSubjectParams) (BlockedSubject, error) {
	row := q.db.QueryRow(ctx, getBlockedSubject, arg.SubjectType, arg.SubjectValue)
	var i BlockedSubject
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectValue,
		&i.Reason,
		&i.BlockedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getReputation = `-- name: GetReputation :one
SELECT subject_type, subject_value, score, updated_at FROM ip_reputation WHERE subject_type = $1 AND subject_value = $2
`

type GetReputationParams struct {
	SubjectType  string
	SubjectValue string
}

func (q *Queries) GetReputation(ctx context.Context, arg GetReputationParams) (IpReputation, error) {
	row := q.db.QueryRow(ctx, getReputation, arg.SubjectType, arg.SubjectValue)
	var i IpReputation
	err := row.Scan(
		&i.SubjectType,
		&i.SubjectValue,
		&i.Score,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAbuseLog = `-- name: InsertAbuseLog :exec
INSERT INTO abuse_log (subject_type, subject_value, action, category, fingerprint, ip, user_id, detail)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertAbuseLogParams struct {
	SubjectType  pgtype.Text
	SubjectValue pgtype.Text
	Action       string
	Category     pgtype.Text
	Fingerprint  pgtype.Text
	Ip           pgtype.Text
	UserID       *uuid.UUID
	Detail       []byte
}

func (q *Queries) InsertAbuseLog(ctx context.Context, arg InsertAbuseLogParams) error {
	_, err := q.db.Exec(ctx, insertAbuseLog,
		arg.SubjectType,
		arg.SubjectValue,
		arg.Action,
		arg.Category,
		arg.Fingerprint,
		arg.Ip,
		arg.UserID,
		arg.Detail,
	)
	return err
}

const listAbuseLog = `-- name: ListAbuseLog :many
SELECT id, subject_type, subject_value, action, category, fingerprint, ip, user_id, detail, created_at FROM abuse_log ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAbuseLogParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAbuseLog(ctx context.Context, arg ListAbuseLogParams) ([]AbuseLog, error) {
	rows, err := q.db.Query(ctx, listAbuseLog, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AbuseLog
	for rows.Next() {
		var i AbuseLog
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectValue,
			&i.Action,
			&i.Category,
			&i.Fingerprint,
			&i.Ip,
			&i.UserID,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockedSubjects = `-- name: ListBlockedSubjects :many
SELECT id, subject_type, subject_value, reason, blocked_by, created_at, expires_at FROM blocked_subjects ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListBlockedSubjectsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListBlockedSubjects(ctx context.Context, arg ListBlockedSubjectsParams) ([]BlockedSubject, error) {
	rows, err := q.db.Query(ctx, listBlockedSubjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockedSubject
	for rows.Next() {
		var i BlockedSubject
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectValue,
			&i.Reason,
			&i.BlockedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIPRules = `-- name: ListIPRules :many
SELECT id, cidr, rule, note, created_by, created_at FROM ip_rules ORDER BY created_at DESC
`

func (q *Queries) ListIPRules(ctx context.Context) ([]IpRule, error) {
	rows, err := q.db.Query(ctx, listIPRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpRule
	for rows.Next() {
		var i IpRule
		if err := rows.Scan(
			&i.ID,
			&i.Cidr,
			&i.Rule,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformSettings = `-- name: ListPlatformSettings :many
SELECT key, value, updated_by, updated_at FROM platform_settings
`

func (q *Queries) ListPlatformSettings(ctx context.Context) ([]PlatformSetting, error) {
	rows, err := q.db.Query(ctx, listPlatformSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformSetting
	for rows.Next() {
		var i PlatformSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBlockedSubject = `-- name: UpsertBlockedSubject :one
INSERT INTO blocked_subjects (subject_type, subject_value, reason, blocked_by, expires_at)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (subject_type, subject_value) DO UPDATE SET reason = EXCLUDED.reason, blocked_by = EXCLUDED.blocked_by, expires_at = EXCLUDED.expires_at, created_at = now()
RETURNING id, subject_type, subject_value, reason, blocked_by, created_at, expires_at
`

type UpsertBlockedSubjectParams struct {
	SubjectType  string
	SubjectValue string
	Reason       pgtype.Text
	BlockedBy    *uuid.UUID
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) UpsertBlockedSubject(ctx context.Context, arg UpsertBlockedSubjectParams) (BlockedSubject, error) {
	row := q.db.QueryRow(ctx, upsertBlockedSubject,
		arg.SubjectType,
		arg.SubjectValue,
		arg.Reason,
		arg.BlockedBy,
		arg.ExpiresAt,
	)
	var i BlockedSubject
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectValue,
		&i.Reason,
		&i.BlockedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertPlatformSetting = `-- name: UpsertPlatformSetting :one
INSERT INTO platform_settings (key, value, updated_by, updated_at)
VALUES ($1,$2,$3,now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING key, value, updated_by, updated_at
`

type UpsertPlatformSettingParams struct {
	Key       string
	Value     string
	UpdatedBy *uuid.UUID
}

func (q *Queries) UpsertPlatformSetting(ctx context.Context, arg UpsertPlatformSettingParams) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, upsertPlatformSetting, arg.Key, arg.Value, arg.UpdatedBy)
	var i PlatformSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
