// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeGrant = `-- name: ConsumeGrant :exec
UPDATE access_grants
SET status = 'CONSUMED', consumed_at = now(), order_id = $2
WHERE id = $1
`

type ConsumeGrantParams struct {
	ID      uuid.UUID
	OrderID *uuid.UUID
}

func (q *Queries) ConsumeGrant(ctx context.Context, arg ConsumeGrantParams) error {
	_, err := q.db.Exec(ctx, consumeGrant, arg.ID, arg.OrderID)
	return err
}

const consumePoolSlot = `-- name: ConsumePoolSlot :exec
UPDATE access_pools
SET reserved_slots = reserved_slots - 1, used_slots = used_slots + 1
WHERE id = $1
`

func (q *Queries) ConsumePoolSlot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumePoolSlot, id)
	return err
}

const createAccessGrant = `-- name: CreateAccessGrant :one
INSERT INTO access_grants
    (pool_id, participant_id, event_id, category_id, code_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, pool_id, participant_id, event_id, category_id, code_id, status, granted_at, expires_at, consumed_at, order_id, created_at
`

type CreateAccessGrantParams struct {
	PoolID        *uuid.UUID
	ParticipantID uuid.UUID
	EventID       uuid.UUID
	CategoryID    uuid.UUID
	CodeID        *uuid.UUID
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateAccessGrant(ctx context.Context, arg CreateAccessGrantParams) (AccessGrant, error) {
	row := q.db.QueryRow(ctx, createAccessGrant,
		arg.PoolID,
		arg.ParticipantID,
		arg.EventID,
		arg.CategoryID,
		arg.CodeID,
		arg.ExpiresAt,
	)
	var i AccessGrant
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.ParticipantID,
		&i.EventID,
		&i.CategoryID,
		&i.CodeID,
		&i.Status,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const createAccessPool = `-- name: CreateAccessPool :one
INSERT INTO access_pools
    (organization_id, event_id, category_id, pool_type, name, total_slots,
     is_visible_to_participants, eligibility_rule, valid_from, valid_until, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, organization_id, event_id, category_id, pool_type, name, total_slots, reserved_slots, used_slots, released_slots, owner_account_id, is_visible_to_participants, eligibility_rule, valid_from, valid_until, created_by, created_at
`

type CreateAccessPoolParams struct {
	OrganizationID          uuid.UUID
	EventID                 uuid.UUID
	CategoryID              uuid.UUID
	PoolType                string
	Name                    string
	TotalSlots              int32
	IsVisibleToParticipants bool
	EligibilityRule         []byte
	ValidFrom               pgtype.Timestamptz
	ValidUntil              pgtype.Timestamptz
	CreatedBy               uuid.UUID
}

func (q *Queries) CreateAccessPool(ctx context.Context, arg CreateAccessPoolParams) (AccessPool, error) {
	row := q.db.QueryRow(ctx, createAccessPool,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.PoolType,
		arg.Name,
		arg.TotalSlots,
		arg.IsVisibleToParticipants,
		arg.EligibilityRule,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.CreatedBy,
	)
	var i AccessPool
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.PoolType,
		&i.Name,
		&i.TotalSlots,
		&i.ReservedSlots,
		&i.UsedSlots,
		&i.ReleasedSlots,
		&i.OwnerAccountID,
		&i.IsVisibleToParticipants,
		&i.EligibilityRule,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const expireGrant = `-- name: ExpireGrant :exec
UPDATE access_grants SET status = 'EXPIRED' WHERE id = $1
`

func (q *Queries) ExpireGrant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, expireGrant, id)
	return err
}

const getAccessGrant = `-- name: GetAccessGrant :one
SELECT id, pool_id, participant_id, event_id, category_id, code_id, status, granted_at, expires_at, consumed_at, order_id, created_at FROM access_grants WHERE id = $1
`

func (q *Queries) GetAccessGrant(ctx context.Context, id uuid.UUID) (AccessGrant, error) {
	row := q.db.QueryRow(ctx, getAccessGrant, id)
	var i AccessGrant
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.ParticipantID,
		&i.EventID,
		&i.CategoryID,
		&i.CodeID,
		&i.Status,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const getAccessPool = `-- name: GetAccessPool :one
SELECT id, organization_id, event_id, category_id, pool_type, name, total_slots, reserved_slots, used_slots, released_slots, owner_account_id, is_visible_to_participants, eligibility_rule, valid_from, valid_until, created_by, created_at FROM access_pools WHERE id = $1
`

func (q *Queries) GetAccessPool(ctx context.Context, id uuid.UUID) (AccessPool, error) {
	row := q.db.QueryRow(ctx, getAccessPool, id)
	var i AccessPool
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.PoolType,
		&i.Name,
		&i.TotalSlots,
		&i.ReservedSlots,
		&i.UsedSlots,
		&i.ReleasedSlots,
		&i.OwnerAccountID,
		&i.IsVisibleToParticipants,
		&i.EligibilityRule,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveGrantForParticipant = `-- name: GetActiveGrantForParticipant :one
SELECT id, pool_id, participant_id, event_id, category_id, code_id, status, granted_at, expires_at, consumed_at, order_id, created_at FROM access_grants
WHERE participant_id = $1 AND category_id = $2 AND status = 'ACTIVE'
ORDER BY granted_at DESC
LIMIT 1
`

type GetActiveGrantForParticipantParams struct {
	ParticipantID uuid.UUID
	CategoryID    uuid.UUID
}

func (q *Queries) GetActiveGrantForParticipant(ctx context.Context, arg GetActiveGrantForParticipantParams) (AccessGrant, error) {
	row := q.db.QueryRow(ctx, getActiveGrantForParticipant, arg.ParticipantID, arg.CategoryID)
	var i AccessGrant
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.ParticipantID,
		&i.EventID,
		&i.CategoryID,
		&i.CodeID,
		&i.Status,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiredActiveGrants = `-- name: ListExpiredActiveGrants :many
SELECT id, pool_id, participant_id, event_id, category_id, code_id, status, granted_at, expires_at, consumed_at, order_id, created_at FROM access_grants
WHERE status = 'ACTIVE' AND expires_at < now()
LIMIT $1
`

func (q *Queries) ListExpiredActiveGrants(ctx context.Context, limit int32) ([]AccessGrant, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveGrants, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessGrant
	for rows.Next() {
		var i AccessGrant
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.ParticipantID,
			&i.EventID,
			&i.CategoryID,
			&i.CodeID,
			&i.Status,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.OrderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releasePoolSlot = `-- name: ReleasePoolSlot :exec
UPDATE access_pools
SET reserved_slots = reserved_slots - 1, released_slots = released_slots + 1
WHERE id = $1
`

func (q *Queries) ReleasePoolSlot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, releasePoolSlot, id)
	return err
}

const reservePoolSlot = `-- name: ReservePoolSlot :one
UPDATE access_pools
SET reserved_slots = reserved_slots + 1
WHERE id = $1 AND reserved_slots + used_slots < total_slots
RETURNING id, organization_id, event_id, category_id, pool_type, name, total_slots, reserved_slots, used_slots, released_slots, owner_account_id, is_visible_to_participants, eligibility_rule, valid_from, valid_until, created_by, created_at
`

func (q *Queries) ReservePoolSlot(ctx context.Context, id uuid.UUID) (AccessPool, error) {
	row := q.db.QueryRow(ctx, reservePoolSlot, id)
	var i AccessPool
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.PoolType,
		&i.Name,
		&i.TotalSlots,
		&i.ReservedSlots,
		&i.UsedSlots,
		&i.ReleasedSlots,
		&i.OwnerAccountID,
		&i.IsVisibleToParticipants,
		&i.EligibilityRule,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
