// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit_logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (organization_id, actor_user_id, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogParams struct {
	OrganizationID *uuid.UUID
	ActorUserID    *uuid.UUID
	Action         string
	TargetType     pgtype.Text
	TargetID       pgtype.Text
	Metadata       []byte
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	return err
}

const listAuditLogsByOrg = `-- name: ListAuditLogsByOrg :many
SELECT id, organization_id, actor_user_id, action, target_type, target_id, metadata, created_at FROM audit_logs WHERE organization_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListAuditLogsByOrgParams struct {
	OrganizationID *uuid.UUID
	Limit          int32
}

func (q *Queries) ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByOrg, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsWithActorByOrg = `-- name: ListAuditLogsWithActorByOrg :many
SELECT
    al.id,
    al.organization_id,
    al.actor_user_id,
    al.action,
    al.target_type,
    al.target_id,
    al.metadata,
    al.created_at,
    COALESCE(u.email, '')::citext AS actor_email,
    COALESCE(u.full_name, '')::text AS actor_name
FROM audit_logs al
LEFT JOIN users u ON u.id = al.actor_user_id
WHERE al.organization_id = $1
ORDER BY al.created_at DESC
LIMIT $2
`

type ListAuditLogsWithActorByOrgParams struct {
	OrganizationID *uuid.UUID
	Limit          int32
}

type ListAuditLogsWithActorByOrgRow struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
	ActorUserID    *uuid.UUID
	Action         string
	TargetType     pgtype.Text
	TargetID       pgtype.Text
	Metadata       []byte
	CreatedAt      pgtype.Timestamptz
	ActorEmail     string
	ActorName      string
}

func (q *Queries) ListAuditLogsWithActorByOrg(ctx context.Context, arg ListAuditLogsWithActorByOrgParams) ([]ListAuditLogsWithActorByOrgRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsWithActorByOrg, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsWithActorByOrgRow
	for rows.Next() {
		var i ListAuditLogsWithActorByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
			&i.ActorEmail,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
