// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ballot.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateBallotOutcome = `-- name: BulkUpdateBallotOutcome :exec
UPDATE ballot_entries SET status = $2 WHERE id = ANY($1::uuid[])
`

type BulkUpdateBallotOutcomeParams struct {
	Column1 []uuid.UUID
	Status  string
}

func (q *Queries) BulkUpdateBallotOutcome(ctx context.Context, arg BulkUpdateBallotOutcomeParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateBallotOutcome, arg.Column1, arg.Status)
	return err
}

const countBallotDrawResults = `-- name: CountBallotDrawResults :one
SELECT count(*) FROM ballot_draw_results WHERE draw_id = $1 AND outcome = $2
`

type CountBallotDrawResultsParams struct {
	DrawID  uuid.UUID
	Outcome string
}

func (q *Queries) CountBallotDrawResults(ctx context.Context, arg CountBallotDrawResultsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBallotDrawResults, arg.DrawID, arg.Outcome)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBallotDraw = `-- name: CreateBallotDraw :one
INSERT INTO ballot_draws
    (organization_id, event_id, category_id, quota, waitlist_size,
     payment_window_hours, application_opens_at, application_closes_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, event_id, category_id, status, quota, waitlist_size, payment_window_hours, application_opens_at, application_closes_at, draw_at, announced_at, seed, draw_nonce, winner_pool_id, waitlist_id, created_by, created_at, updated_at
`

type CreateBallotDrawParams struct {
	OrganizationID      uuid.UUID
	EventID             uuid.UUID
	CategoryID          uuid.UUID
	Quota               int32
	WaitlistSize        pgtype.Int4
	PaymentWindowHours  int32
	ApplicationOpensAt  pgtype.Timestamptz
	ApplicationClosesAt pgtype.Timestamptz
	CreatedBy           uuid.UUID
}

func (q *Queries) CreateBallotDraw(ctx context.Context, arg CreateBallotDrawParams) (BallotDraw, error) {
	row := q.db.QueryRow(ctx, createBallotDraw,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.Quota,
		arg.WaitlistSize,
		arg.PaymentWindowHours,
		arg.ApplicationOpensAt,
		arg.ApplicationClosesAt,
		arg.CreatedBy,
	)
	var i BallotDraw
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Status,
		&i.Quota,
		&i.WaitlistSize,
		&i.PaymentWindowHours,
		&i.ApplicationOpensAt,
		&i.ApplicationClosesAt,
		&i.DrawAt,
		&i.AnnouncedAt,
		&i.Seed,
		&i.DrawNonce,
		&i.WinnerPoolID,
		&i.WaitlistID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBallotEntry = `-- name: CreateBallotEntry :one
INSERT INTO ballot_entries
    (draw_id, organization_id, event_id, category_id, participant_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, draw_id, organization_id, event_id, category_id, participant_id, status, applied_at, payment_deadline, converted_at, promoted_round, access_grant_id
`

type CreateBallotEntryParams struct {
	DrawID         uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     uuid.UUID
	ParticipantID  uuid.UUID
}

func (q *Queries) CreateBallotEntry(ctx context.Context, arg CreateBallotEntryParams) (BallotEntry, error) {
	row := q.db.QueryRow(ctx, createBallotEntry,
		arg.DrawID,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.ParticipantID,
	)
	var i BallotEntry
	err := row.Scan(
		&i.ID,
		&i.DrawID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.Status,
		&i.AppliedAt,
		&i.PaymentDeadline,
		&i.ConvertedAt,
		&i.PromotedRound,
		&i.AccessGrantID,
	)
	return i, err
}

const getActiveBallotDrawByCategory = `-- name: GetActiveBallotDrawByCategory :one
SELECT id, organization_id, event_id, category_id, status, quota, waitlist_size, payment_window_hours, application_opens_at, application_closes_at, draw_at, announced_at, seed, draw_nonce, winner_pool_id, waitlist_id, created_by, created_at, updated_at FROM ballot_draws
WHERE event_id = $1 AND category_id = $2 AND status NOT IN ('ANNOUNCED')
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveBallotDrawByCategoryParams struct {
	EventID    uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) GetActiveBallotDrawByCategory(ctx context.Context, arg GetActiveBallotDrawByCategoryParams) (BallotDraw, error) {
	row := q.db.QueryRow(ctx, getActiveBallotDrawByCategory, arg.EventID, arg.CategoryID)
	var i BallotDraw
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Status,
		&i.Quota,
		&i.WaitlistSize,
		&i.PaymentWindowHours,
		&i.ApplicationOpensAt,
		&i.ApplicationClosesAt,
		&i.DrawAt,
		&i.AnnouncedAt,
		&i.Seed,
		&i.DrawNonce,
		&i.WinnerPoolID,
		&i.WaitlistID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBallotDraw = `-- name: GetBallotDraw :one
SELECT id, organization_id, event_id, category_id, status, quota, waitlist_size, payment_window_hours, application_opens_at, application_closes_at, draw_at, announced_at, seed, draw_nonce, winner_pool_id, waitlist_id, created_by, created_at, updated_at FROM ballot_draws WHERE id = $1
`

func (q *Queries) GetBallotDraw(ctx context.Context, id uuid.UUID) (BallotDraw, error) {
	row := q.db.QueryRow(ctx, getBallotDraw, id)
	var i BallotDraw
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Status,
		&i.Quota,
		&i.WaitlistSize,
		&i.PaymentWindowHours,
		&i.ApplicationOpensAt,
		&i.ApplicationClosesAt,
		&i.DrawAt,
		&i.AnnouncedAt,
		&i.Seed,
		&i.DrawNonce,
		&i.WinnerPoolID,
		&i.WaitlistID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBallotEntry = `-- name: GetBallotEntry :one
SELECT id, draw_id, organization_id, event_id, category_id, participant_id, status, applied_at, payment_deadline, converted_at, promoted_round, access_grant_id FROM ballot_entries WHERE draw_id = $1 AND participant_id = $2
`

type GetBallotEntryParams struct {
	DrawID        uuid.UUID
	ParticipantID uuid.UUID
}

func (q *Queries) GetBallotEntry(ctx context.Context, arg GetBallotEntryParams) (BallotEntry, error) {
	row := q.db.QueryRow(ctx, getBallotEntry, arg.DrawID, arg.ParticipantID)
	var i BallotEntry
	err := row.Scan(
		&i.ID,
		&i.DrawID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.Status,
		&i.AppliedAt,
		&i.PaymentDeadline,
		&i.ConvertedAt,
		&i.PromotedRound,
		&i.AccessGrantID,
	)
	return i, err
}

const getBallotEntryByID = `-- name: GetBallotEntryByID :one
SELECT id, draw_id, organization_id, event_id, category_id, participant_id, status, applied_at, payment_deadline, converted_at, promoted_round, access_grant_id FROM ballot_entries WHERE id = $1
`

func (q *Queries) GetBallotEntryByID(ctx context.Context, id uuid.UUID) (BallotEntry, error) {
	row := q.db.QueryRow(ctx, getBallotEntryByID, id)
	var i BallotEntry
	err := row.Scan(
		&i.ID,
		&i.DrawID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.Status,
		&i.AppliedAt,
		&i.PaymentDeadline,
		&i.ConvertedAt,
		&i.PromotedRound,
		&i.AccessGrantID,
	)
	return i, err
}

const getBallotEntryByParticipant = `-- name: GetBallotEntryByParticipant :many
SELECT id, draw_id, organization_id, event_id, category_id, participant_id, status, applied_at, payment_deadline, converted_at, promoted_round, access_grant_id FROM ballot_entries
WHERE participant_id = $1
ORDER BY applied_at DESC
LIMIT $2 OFFSET $3
`

type GetBallotEntryByParticipantParams struct {
	ParticipantID uuid.UUID
	Limit         int32
	Offset        int32
}

func (q *Queries) GetBallotEntryByParticipant(ctx context.Context, arg GetBallotEntryByParticipantParams) ([]BallotEntry, error) {
	rows, err := q.db.Query(ctx, getBallotEntryByParticipant, arg.ParticipantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BallotEntry
	for rows.Next() {
		var i BallotEntry
		if err := rows.Scan(
			&i.ID,
			&i.DrawID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.ParticipantID,
			&i.Status,
			&i.AppliedAt,
			&i.PaymentDeadline,
			&i.ConvertedAt,
			&i.PromotedRound,
			&i.AccessGrantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBallotDrawResult = `-- name: InsertBallotDrawResult :exec
INSERT INTO ballot_draw_results (draw_id, ballot_entry_id, outcome, rank, result_hash)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (draw_id, ballot_entry_id) DO NOTHING
`

type InsertBallotDrawResultParams struct {
	DrawID        uuid.UUID
	BallotEntryID uuid.UUID
	Outcome       string
	Rank          int32
	ResultHash    string
}

func (q *Queries) InsertBallotDrawResult(ctx context.Context, arg InsertBallotDrawResultParams) error {
	_, err := q.db.Exec(ctx, insertBallotDrawResult,
		arg.DrawID,
		arg.BallotEntryID,
		arg.Outcome,
		arg.Rank,
		arg.ResultHash,
	)
	return err
}

const listAllDrawResults = `-- name: ListAllDrawResults :many
SELECT bdr.rank, bdr.outcome, bdr.result_hash,
       be.id AS ballot_entry_id, be.participant_id
FROM ballot_draw_results bdr
JOIN ballot_entries be ON be.id = bdr.ballot_entry_id
WHERE bdr.draw_id = $1
ORDER BY bdr.rank ASC
`

type ListAllDrawResultsRow struct {
	Rank          int32
	Outcome       string
	ResultHash    string
	BallotEntryID uuid.UUID
	ParticipantID uuid.UUID
}

func (q *Queries) ListAllDrawResults(ctx context.Context, drawID uuid.UUID) ([]ListAllDrawResultsRow, error) {
	rows, err := q.db.Query(ctx, listAllDrawResults, drawID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDrawResultsRow
	for rows.Next() {
		var i ListAllDrawResultsRow
		if err := rows.Scan(
			&i.Rank,
			&i.Outcome,
			&i.ResultHash,
			&i.BallotEntryID,
			&i.ParticipantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppliedEntriesForDraw = `-- name: ListAppliedEntriesForDraw :many
SELECT id, draw_id, organization_id, event_id, category_id, participant_id, status, applied_at, payment_deadline, converted_at, promoted_round, access_grant_id FROM ballot_entries
WHERE draw_id = $1 AND status = 'APPLIED'
ORDER BY id ASC
`

func (q *Queries) ListAppliedEntriesForDraw(ctx context.Context, drawID uuid.UUID) ([]BallotEntry, error) {
	rows, err := q.db.Query(ctx, listAppliedEntriesForDraw, drawID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BallotEntry
	for rows.Next() {
		var i BallotEntry
		if err := rows.Scan(
			&i.ID,
			&i.DrawID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.ParticipantID,
			&i.Status,
			&i.AppliedAt,
			&i.PaymentDeadline,
			&i.ConvertedAt,
			&i.PromotedRound,
			&i.AccessGrantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBallotDrawResults = `-- name: ListBallotDrawResults :many
SELECT bdr.rank, bdr.outcome, bdr.result_hash,
       be.id AS ballot_entry_id, be.participant_id
FROM ballot_draw_results bdr
JOIN ballot_entries be ON be.id = bdr.ballot_entry_id
WHERE bdr.draw_id = $1
ORDER BY bdr.rank ASC
LIMIT $2 OFFSET $3
`

type ListBallotDrawResultsParams struct {
	DrawID uuid.UUID
	Limit  int32
	Offset int32
}

type ListBallotDrawResultsRow struct {
	Rank          int32
	Outcome       string
	ResultHash    string
	BallotEntryID uuid.UUID
	ParticipantID uuid.UUID
}

func (q *Queries) ListBallotDrawResults(ctx context.Context, arg ListBallotDrawResultsParams) ([]ListBallotDrawResultsRow, error) {
	rows, err := q.db.Query(ctx, listBallotDrawResults, arg.DrawID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBallotDrawResultsRow
	for rows.Next() {
		var i ListBallotDrawResultsRow
		if err := rows.Scan(
			&i.Rank,
			&i.Outcome,
			&i.ResultHash,
			&i.BallotEntryID,
			&i.ParticipantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringWinners = `-- name: ListExpiringWinners :many
SELECT id, draw_id, organization_id, event_id, category_id, participant_id, status, applied_at, payment_deadline, converted_at, promoted_round, access_grant_id FROM ballot_entries
WHERE status = 'WINNER' AND payment_deadline < now()
LIMIT $1
`

func (q *Queries) ListExpiringWinners(ctx context.Context, limit int32) ([]BallotEntry, error) {
	rows, err := q.db.Query(ctx, listExpiringWinners, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BallotEntry
	for rows.Next() {
		var i BallotEntry
		if err := rows.Scan(
			&i.ID,
			&i.DrawID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.ParticipantID,
			&i.Status,
			&i.AppliedAt,
			&i.PaymentDeadline,
			&i.ConvertedAt,
			&i.PromotedRound,
			&i.AccessGrantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWinnerEntries = `-- name: ListWinnerEntries :many
SELECT id, draw_id, organization_id, event_id, category_id, participant_id, status, applied_at, payment_deadline, converted_at, promoted_round, access_grant_id FROM ballot_entries
WHERE draw_id = $1 AND status = 'WINNER'
`

func (q *Queries) ListWinnerEntries(ctx context.Context, drawID uuid.UUID) ([]BallotEntry, error) {
	rows, err := q.db.Query(ctx, listWinnerEntries, drawID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BallotEntry
	for rows.Next() {
		var i BallotEntry
		if err := rows.Scan(
			&i.ID,
			&i.DrawID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.ParticipantID,
			&i.Status,
			&i.AppliedAt,
			&i.PaymentDeadline,
			&i.ConvertedAt,
			&i.PromotedRound,
			&i.AccessGrantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBallotDrawPools = `-- name: SetBallotDrawPools :exec
UPDATE ballot_draws SET winner_pool_id = $2, waitlist_id = $3, updated_at = now()
WHERE id = $1
`

type SetBallotDrawPoolsParams struct {
	ID           uuid.UUID
	WinnerPoolID *uuid.UUID
	WaitlistID   *uuid.UUID
}

func (q *Queries) SetBallotDrawPools(ctx context.Context, arg SetBallotDrawPoolsParams) error {
	_, err := q.db.Exec(ctx, setBallotDrawPools, arg.ID, arg.WinnerPoolID, arg.WaitlistID)
	return err
}

const setBallotDrawSeed = `-- name: SetBallotDrawSeed :one
UPDATE ballot_draws SET seed = $2, draw_nonce = $3, updated_at = now()
WHERE id = $1 AND seed IS NULL
RETURNING id, organization_id, event_id, category_id, status, quota, waitlist_size, payment_window_hours, application_opens_at, application_closes_at, draw_at, announced_at, seed, draw_nonce, winner_pool_id, waitlist_id, created_by, created_at, updated_at
`

type SetBallotDrawSeedParams struct {
	ID        uuid.UUID
	Seed      pgtype.Text
	DrawNonce *uuid.UUID
}

func (q *Queries) SetBallotDrawSeed(ctx context.Context, arg SetBallotDrawSeedParams) (BallotDraw, error) {
	row := q.db.QueryRow(ctx, setBallotDrawSeed, arg.ID, arg.Seed, arg.DrawNonce)
	var i BallotDraw
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Status,
		&i.Quota,
		&i.WaitlistSize,
		&i.PaymentWindowHours,
		&i.ApplicationOpensAt,
		&i.ApplicationClosesAt,
		&i.DrawAt,
		&i.AnnouncedAt,
		&i.Seed,
		&i.DrawNonce,
		&i.WinnerPoolID,
		&i.WaitlistID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBallotDrawStatus = `-- name: UpdateBallotDrawStatus :one
UPDATE ballot_draws
SET status = $2,
    draw_at = CASE WHEN $2 = 'DRAWN' THEN now() ELSE draw_at END,
    announced_at = CASE WHEN $2 = 'ANNOUNCED' THEN now() ELSE announced_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, category_id, status, quota, waitlist_size, payment_window_hours, application_opens_at, application_closes_at, draw_at, announced_at, seed, draw_nonce, winner_pool_id, waitlist_id, created_by, created_at, updated_at
`

type UpdateBallotDrawStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateBallotDrawStatus(ctx context.Context, arg UpdateBallotDrawStatusParams) (BallotDraw, error) {
	row := q.db.QueryRow(ctx, updateBallotDrawStatus, arg.ID, arg.Status)
	var i BallotDraw
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Status,
		&i.Quota,
		&i.WaitlistSize,
		&i.PaymentWindowHours,
		&i.ApplicationOpensAt,
		&i.ApplicationClosesAt,
		&i.DrawAt,
		&i.AnnouncedAt,
		&i.Seed,
		&i.DrawNonce,
		&i.WinnerPoolID,
		&i.WaitlistID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBallotEntryStatus = `-- name: UpdateBallotEntryStatus :one
UPDATE ballot_entries
SET status = $2,
    payment_deadline = COALESCE($3, payment_deadline),
    access_grant_id  = COALESCE($4, access_grant_id),
    converted_at     = CASE WHEN $2 = 'CONVERTED' THEN now() ELSE converted_at END
WHERE id = $1
RETURNING id, draw_id, organization_id, event_id, category_id, participant_id, status, applied_at, payment_deadline, converted_at, promoted_round, access_grant_id
`

type UpdateBallotEntryStatusParams struct {
	ID              uuid.UUID
	Status          string
	PaymentDeadline pgtype.Timestamptz
	AccessGrantID   *uuid.UUID
}

func (q *Queries) UpdateBallotEntryStatus(ctx context.Context, arg UpdateBallotEntryStatusParams) (BallotEntry, error) {
	row := q.db.QueryRow(ctx, updateBallotEntryStatus,
		arg.ID,
		arg.Status,
		arg.PaymentDeadline,
		arg.AccessGrantID,
	)
	var i BallotEntry
	err := row.Scan(
		&i.ID,
		&i.DrawID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.Status,
		&i.AppliedAt,
		&i.PaymentDeadline,
		&i.ConvertedAt,
		&i.PromotedRound,
		&i.AccessGrantID,
	)
	return i, err
}
