// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByOrg = `-- name: CountEventsByOrg :one
SELECT COUNT(*)::bigint AS count FROM events WHERE organization_id = $1
`

func (q *Queries) CountEventsByOrg(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByOrg, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlatformInvoice = `-- name: CreatePlatformInvoice :one
INSERT INTO platform_invoices (organization_id, invoice_number, period_start, period_end, subscription_amount, fee_amount, total_amount, status, issued_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'ISSUED', now())
RETURNING id, organization_id, invoice_number, period_start, period_end, subscription_amount, fee_amount, total_amount, status, issued_at, paid_at, created_at, updated_at
`

type CreatePlatformInvoiceParams struct {
	OrganizationID     uuid.UUID
	InvoiceNumber      string
	PeriodStart        pgtype.Date
	PeriodEnd          pgtype.Date
	SubscriptionAmount int64
	FeeAmount          int64
	TotalAmount        int64
}

func (q *Queries) CreatePlatformInvoice(ctx context.Context, arg CreatePlatformInvoiceParams) (PlatformInvoice, error) {
	row := q.db.QueryRow(ctx, createPlatformInvoice,
		arg.OrganizationID,
		arg.InvoiceNumber,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.SubscriptionAmount,
		arg.FeeAmount,
		arg.TotalAmount,
	)
	var i PlatformInvoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SubscriptionAmount,
		&i.FeeAmount,
		&i.TotalAmount,
		&i.Status,
		&i.IssuedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscriptionPackage = `-- name: CreateSubscriptionPackage :one
INSERT INTO subscription_packages (slug, name, description, price_monthly, max_events, fee_bps, features, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, slug, name, description, price_monthly, max_events, fee_bps, features, is_active, sort_order, created_at, updated_at
`

type CreateSubscriptionPackageParams struct {
	Slug         string
	Name         string
	Description  string
	PriceMonthly int64
	MaxEvents    pgtype.Int4
	FeeBps       int32
	Features     []byte
	SortOrder    int32
}

func (q *Queries) CreateSubscriptionPackage(ctx context.Context, arg CreateSubscriptionPackageParams) (SubscriptionPackage, error) {
	row := q.db.QueryRow(ctx, createSubscriptionPackage,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.PriceMonthly,
		arg.MaxEvents,
		arg.FeeBps,
		arg.Features,
		arg.SortOrder,
	)
	var i SubscriptionPackage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.PriceMonthly,
		&i.MaxEvents,
		&i.FeeBps,
		&i.Features,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgSubscription = `-- name: GetOrgSubscription :one
SELECT os.id, os.organization_id, os.package_id, os.status, os.started_at, os.expires_at, os.created_at, os.updated_at, sp.id, sp.slug, sp.name, sp.description, sp.price_monthly, sp.max_events, sp.fee_bps, sp.features, sp.is_active, sp.sort_order, sp.created_at, sp.updated_at
FROM org_subscriptions os
JOIN subscription_packages sp ON sp.id = os.package_id
WHERE os.organization_id = $1
`

type GetOrgSubscriptionRow struct {
	OrgSubscription     OrgSubscription
	SubscriptionPackage SubscriptionPackage
}

func (q *Queries) GetOrgSubscription(ctx context.Context, organizationID uuid.UUID) (GetOrgSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getOrgSubscription, organizationID)
	var i GetOrgSubscriptionRow
	err := row.Scan(
		&i.OrgSubscription.ID,
		&i.OrgSubscription.OrganizationID,
		&i.OrgSubscription.PackageID,
		&i.OrgSubscription.Status,
		&i.OrgSubscription.StartedAt,
		&i.OrgSubscription.ExpiresAt,
		&i.OrgSubscription.CreatedAt,
		&i.OrgSubscription.UpdatedAt,
		&i.SubscriptionPackage.ID,
		&i.SubscriptionPackage.Slug,
		&i.SubscriptionPackage.Name,
		&i.SubscriptionPackage.Description,
		&i.SubscriptionPackage.PriceMonthly,
		&i.SubscriptionPackage.MaxEvents,
		&i.SubscriptionPackage.FeeBps,
		&i.SubscriptionPackage.Features,
		&i.SubscriptionPackage.IsActive,
		&i.SubscriptionPackage.SortOrder,
		&i.SubscriptionPackage.CreatedAt,
		&i.SubscriptionPackage.UpdatedAt,
	)
	return i, err
}

const getPlatformInvoice = `-- name: GetPlatformInvoice :one
SELECT id, organization_id, invoice_number, period_start, period_end, subscription_amount, fee_amount, total_amount, status, issued_at, paid_at, created_at, updated_at FROM platform_invoices WHERE id = $1
`

func (q *Queries) GetPlatformInvoice(ctx context.Context, id uuid.UUID) (PlatformInvoice, error) {
	row := q.db.QueryRow(ctx, getPlatformInvoice, id)
	var i PlatformInvoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SubscriptionAmount,
		&i.FeeAmount,
		&i.TotalAmount,
		&i.Status,
		&i.IssuedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionPackage = `-- name: GetSubscriptionPackage :one
SELECT id, slug, name, description, price_monthly, max_events, fee_bps, features, is_active, sort_order, created_at, updated_at FROM subscription_packages WHERE id = $1
`

func (q *Queries) GetSubscriptionPackage(ctx context.Context, id uuid.UUID) (SubscriptionPackage, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPackage, id)
	var i SubscriptionPackage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.PriceMonthly,
		&i.MaxEvents,
		&i.FeeBps,
		&i.Features,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionPackageBySlug = `-- name: GetSubscriptionPackageBySlug :one
SELECT id, slug, name, description, price_monthly, max_events, fee_bps, features, is_active, sort_order, created_at, updated_at FROM subscription_packages WHERE slug = $1
`

func (q *Queries) GetSubscriptionPackageBySlug(ctx context.Context, slug string) (SubscriptionPackage, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPackageBySlug, slug)
	var i SubscriptionPackage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.PriceMonthly,
		&i.MaxEvents,
		&i.FeeBps,
		&i.Features,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlatformFee = `-- name: InsertPlatformFee :one
INSERT INTO platform_fee_ledger (organization_id, order_id, order_total, fee_bps, fee_amount)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (order_id) DO NOTHING
RETURNING id, organization_id, order_id, order_total, fee_bps, fee_amount, created_at
`

type InsertPlatformFeeParams struct {
	OrganizationID uuid.UUID
	OrderID        uuid.UUID
	OrderTotal     int64
	FeeBps         int32
	FeeAmount      int64
}

func (q *Queries) InsertPlatformFee(ctx context.Context, arg InsertPlatformFeeParams) (PlatformFeeLedger, error) {
	row := q.db.QueryRow(ctx, insertPlatformFee,
		arg.OrganizationID,
		arg.OrderID,
		arg.OrderTotal,
		arg.FeeBps,
		arg.FeeAmount,
	)
	var i PlatformFeeLedger
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderID,
		&i.OrderTotal,
		&i.FeeBps,
		&i.FeeAmount,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSubscriptionPackages = `-- name: ListActiveSubscriptionPackages :many
SELECT id, slug, name, description, price_monthly, max_events, fee_bps, features, is_active, sort_order, created_at, updated_at FROM subscription_packages
WHERE is_active = true
ORDER BY sort_order, price_monthly
`

func (q *Queries) ListActiveSubscriptionPackages(ctx context.Context) ([]SubscriptionPackage, error) {
	rows, err := q.db.Query(ctx, listActiveSubscriptionPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionPackage
	for rows.Next() {
		var i SubscriptionPackage
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.PriceMonthly,
			&i.MaxEvents,
			&i.FeeBps,
			&i.Features,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformFeesByOrg = `-- name: ListPlatformFeesByOrg :many
SELECT id, organization_id, order_id, order_total, fee_bps, fee_amount, created_at FROM platform_fee_ledger
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPlatformFeesByOrgParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListPlatformFeesByOrg(ctx context.Context, arg ListPlatformFeesByOrgParams) ([]PlatformFeeLedger, error) {
	rows, err := q.db.Query(ctx, listPlatformFeesByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformFeeLedger
	for rows.Next() {
		var i PlatformFeeLedger
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrderID,
			&i.OrderTotal,
			&i.FeeBps,
			&i.FeeAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformInvoicesByOrg = `-- name: ListPlatformInvoicesByOrg :many
SELECT id, organization_id, invoice_number, period_start, period_end, subscription_amount, fee_amount, total_amount, status, issued_at, paid_at, created_at, updated_at FROM platform_invoices
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPlatformInvoicesByOrgParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListPlatformInvoicesByOrg(ctx context.Context, arg ListPlatformInvoicesByOrgParams) ([]PlatformInvoice, error) {
	rows, err := q.db.Query(ctx, listPlatformInvoicesByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformInvoice
	for rows.Next() {
		var i PlatformInvoice
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InvoiceNumber,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.SubscriptionAmount,
			&i.FeeAmount,
			&i.TotalAmount,
			&i.Status,
			&i.IssuedAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionPackages = `-- name: ListSubscriptionPackages :many
SELECT id, slug, name, description, price_monthly, max_events, fee_bps, features, is_active, sort_order, created_at, updated_at FROM subscription_packages
ORDER BY sort_order, price_monthly
`

func (q *Queries) ListSubscriptionPackages(ctx context.Context) ([]SubscriptionPackage, error) {
	rows, err := q.db.Query(ctx, listSubscriptionPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionPackage
	for rows.Next() {
		var i SubscriptionPackage
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.PriceMonthly,
			&i.MaxEvents,
			&i.FeeBps,
			&i.Features,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPlatformInvoicePaid = `-- name: MarkPlatformInvoicePaid :one
UPDATE platform_invoices
SET status = 'PAID', paid_at = now(), updated_at = now()
WHERE id = $1 AND status = 'ISSUED'
RETURNING id, organization_id, invoice_number, period_start, period_end, subscription_amount, fee_amount, total_amount, status, issued_at, paid_at, created_at, updated_at
`

func (q *Queries) MarkPlatformInvoicePaid(ctx context.Context, id uuid.UUID) (PlatformInvoice, error) {
	row := q.db.QueryRow(ctx, markPlatformInvoicePaid, id)
	var i PlatformInvoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SubscriptionAmount,
		&i.FeeAmount,
		&i.TotalAmount,
		&i.Status,
		&i.IssuedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const platformFeeSummary = `-- name: PlatformFeeSummary :one
SELECT
    COALESCE(COUNT(*), 0)::bigint         AS entries,
    COALESCE(SUM(order_total), 0)::bigint AS gross_orders,
    COALESCE(SUM(fee_amount), 0)::bigint  AS total_fees
FROM platform_fee_ledger
WHERE organization_id = $1
`

type PlatformFeeSummaryRow struct {
	Entries     int64
	GrossOrders int64
	TotalFees   int64
}

func (q *Queries) PlatformFeeSummary(ctx context.Context, organizationID uuid.UUID) (PlatformFeeSummaryRow, error) {
	row := q.db.QueryRow(ctx, platformFeeSummary, organizationID)
	var i PlatformFeeSummaryRow
	err := row.Scan(&i.Entries, &i.GrossOrders, &i.TotalFees)
	return i, err
}

const platformRevenueSummary = `-- name: PlatformRevenueSummary :many
SELECT
    o.id                                    AS organization_id,
    o.name                                  AS organization_name,
    COALESCE(SUM(l.fee_amount), 0)::bigint  AS total_fees,
    COALESCE(SUM(l.order_total), 0)::bigint AS gross_orders,
    COALESCE(COUNT(l.id), 0)::bigint        AS fee_entries
FROM organizations o
LEFT JOIN platform_fee_ledger l ON l.organization_id = o.id
GROUP BY o.id, o.name
ORDER BY total_fees DESC
`

type PlatformRevenueSummaryRow struct {
	OrganizationID   uuid.UUID
	OrganizationName string
	TotalFees        int64
	GrossOrders      int64
	FeeEntries       int64
}

func (q *Queries) PlatformRevenueSummary(ctx context.Context) ([]PlatformRevenueSummaryRow, error) {
	rows, err := q.db.Query(ctx, platformRevenueSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformRevenueSummaryRow
	for rows.Next() {
		var i PlatformRevenueSummaryRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.OrganizationName,
			&i.TotalFees,
			&i.GrossOrders,
			&i.FeeEntries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriptionPackage = `-- name: UpdateSubscriptionPackage :one
UPDATE subscription_packages
SET name = $2, description = $3, price_monthly = $4, max_events = $5,
    fee_bps = $6, features = $7, is_active = $8, sort_order = $9, updated_at = now()
WHERE id = $1
RETURNING id, slug, name, description, price_monthly, max_events, fee_bps, features, is_active, sort_order, created_at, updated_at
`

type UpdateSubscriptionPackageParams struct {
	ID           uuid.UUID
	Name         string
	Description  string
	PriceMonthly int64
	MaxEvents    pgtype.Int4
	FeeBps       int32
	Features     []byte
	IsActive     bool
	SortOrder    int32
}

func (q *Queries) UpdateSubscriptionPackage(ctx context.Context, arg UpdateSubscriptionPackageParams) (SubscriptionPackage, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionPackage,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceMonthly,
		arg.MaxEvents,
		arg.FeeBps,
		arg.Features,
		arg.IsActive,
		arg.SortOrder,
	)
	var i SubscriptionPackage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.PriceMonthly,
		&i.MaxEvents,
		&i.FeeBps,
		&i.Features,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrgSubscription = `-- name: UpsertOrgSubscription :one
INSERT INTO org_subscriptions (organization_id, package_id, status, started_at, expires_at)
VALUES ($1, $2, 'ACTIVE', now(), $3)
ON CONFLICT (organization_id) DO UPDATE
SET package_id = EXCLUDED.package_id,
    status = 'ACTIVE',
    started_at = now(),
    expires_at = EXCLUDED.expires_at,
    updated_at = now()
RETURNING id, organization_id, package_id, status, started_at, expires_at, created_at, updated_at
`

type UpsertOrgSubscriptionParams struct {
	OrganizationID uuid.UUID
	PackageID      uuid.UUID
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) UpsertOrgSubscription(ctx context.Context, arg UpsertOrgSubscriptionParams) (OrgSubscription, error) {
	row := q.db.QueryRow(ctx, upsertOrgSubscription, arg.OrganizationID, arg.PackageID, arg.ExpiresAt)
	var i OrgSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PackageID,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
