package db

// catalog_ext.go — hand-written extensions for the public catalog.
// These are NOT generated by sqlc; do not run sqlc generate on this file.

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// EventCategoryWithMode extends EventCategory with the resolved registration
// mode from category_registration_settings (LEFT JOIN, nullable).
type EventCategoryWithMode struct {
	ID                   uuid.UUID
	OrganizationID       uuid.UUID
	EventID              uuid.UUID
	Name                 string
	Price                int64
	Capacity             int32
	RegistrationOpensAt  pgtype.Timestamptz
	RegistrationClosesAt pgtype.Timestamptz
	BibPrefix            pgtype.Text
	MinAge               pgtype.Int4
	MaxOrderPerUser      int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	// From category_registration_settings — NULL when no row exists.
	RegistrationMode pgtype.Text
}

const listCategoriesByEventForPublicWithMode = `
SELECT
    ec.id, ec.organization_id, ec.event_id, ec.name, ec.price, ec.capacity,
    ec.registration_opens_at, ec.registration_closes_at,
    ec.bib_prefix, ec.min_age, ec.max_order_per_user,
    ec.created_at, ec.updated_at,
    crs.registration_mode
FROM event_categories ec
LEFT JOIN category_registration_settings crs ON crs.category_id = ec.id
WHERE ec.event_id = $1
ORDER BY ec.price
`

// ListCategoriesByEventForPublicWithMode returns categories for a public event
// with their resolved registration mode (NULL → treat as NORMAL in the service).
func (q *Queries) ListCategoriesByEventForPublicWithMode(ctx context.Context, eventID uuid.UUID) ([]EventCategoryWithMode, error) {
	rows, err := q.db.Query(ctx, listCategoriesByEventForPublicWithMode, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventCategoryWithMode
	for rows.Next() {
		var i EventCategoryWithMode
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.Name,
			&i.Price,
			&i.Capacity,
			&i.RegistrationOpensAt,
			&i.RegistrationClosesAt,
			&i.BibPrefix,
			&i.MinAge,
			&i.MaxOrderPerUser,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RegistrationMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
