// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: competitions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompetitionMatch = `-- name: CreateCompetitionMatch :one
INSERT INTO competition_matches (
    organization_id, event_id, stage_id, round_number, match_number,
    home_team_id, away_team_id, home_entry_id, away_entry_id,
    scheduled_start_time, venue_court_name, home_score, away_score,
    match_status, winner_id, score_details
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, organization_id, event_id, stage_id, round_number, match_number, home_team_id, away_team_id, home_entry_id, away_entry_id, scheduled_start_time, venue_court_name, home_score, away_score, match_status, winner_id, score_details, created_at, updated_at
`

type CreateCompetitionMatchParams struct {
	OrganizationID     uuid.UUID
	EventID            uuid.UUID
	StageID            uuid.UUID
	RoundNumber        int32
	MatchNumber        int32
	HomeTeamID         *uuid.UUID
	AwayTeamID         *uuid.UUID
	HomeEntryID        *uuid.UUID
	AwayEntryID        *uuid.UUID
	ScheduledStartTime pgtype.Timestamptz
	VenueCourtName     pgtype.Text
	HomeScore          int32
	AwayScore          int32
	MatchStatus        string
	WinnerID           *uuid.UUID
	ScoreDetails       []byte
}

func (q *Queries) CreateCompetitionMatch(ctx context.Context, arg CreateCompetitionMatchParams) (CompetitionMatch, error) {
	row := q.db.QueryRow(ctx, createCompetitionMatch,
		arg.OrganizationID,
		arg.EventID,
		arg.StageID,
		arg.RoundNumber,
		arg.MatchNumber,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.HomeEntryID,
		arg.AwayEntryID,
		arg.ScheduledStartTime,
		arg.VenueCourtName,
		arg.HomeScore,
		arg.AwayScore,
		arg.MatchStatus,
		arg.WinnerID,
		arg.ScoreDetails,
	)
	var i CompetitionMatch
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.StageID,
		&i.RoundNumber,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeEntryID,
		&i.AwayEntryID,
		&i.ScheduledStartTime,
		&i.VenueCourtName,
		&i.HomeScore,
		&i.AwayScore,
		&i.MatchStatus,
		&i.WinnerID,
		&i.ScoreDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCompetitionObservation = `-- name: CreateCompetitionObservation :one
INSERT INTO competition_observations (
    organization_id, event_id, stage_id, match_id, entry_id,
    observation_type, source, numeric_value, text_value, observed_at_ms, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, organization_id, event_id, stage_id, match_id, entry_id, observation_type, source, numeric_value, text_value, observed_at_ms, metadata, created_at
`

type CreateCompetitionObservationParams struct {
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	StageID         *uuid.UUID
	MatchID         *uuid.UUID
	EntryID         *uuid.UUID
	ObservationType string
	Source          string
	NumericValue    pgtype.Numeric
	TextValue       pgtype.Text
	ObservedAtMs    int64
	Metadata        []byte
}

// 6. Observations
func (q *Queries) CreateCompetitionObservation(ctx context.Context, arg CreateCompetitionObservationParams) (CompetitionObservation, error) {
	row := q.db.QueryRow(ctx, createCompetitionObservation,
		arg.OrganizationID,
		arg.EventID,
		arg.StageID,
		arg.MatchID,
		arg.EntryID,
		arg.ObservationType,
		arg.Source,
		arg.NumericValue,
		arg.TextValue,
		arg.ObservedAtMs,
		arg.Metadata,
	)
	var i CompetitionObservation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.StageID,
		&i.MatchID,
		&i.EntryID,
		&i.ObservationType,
		&i.Source,
		&i.NumericValue,
		&i.TextValue,
		&i.ObservedAtMs,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionStage = `-- name: CreateCompetitionStage :one
INSERT INTO competition_stages (
    organization_id, event_id, category_id, name, stage_type, sequence_order, status, stage_config
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, event_id, category_id, name, stage_type, sequence_order, status, stage_config, created_at, updated_at
`

type CreateCompetitionStageParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     *uuid.UUID
	Name           string
	StageType      string
	SequenceOrder  int32
	Status         string
	StageConfig    []byte
}

// 4. Stages & Matches
func (q *Queries) CreateCompetitionStage(ctx context.Context, arg CreateCompetitionStageParams) (CompetitionStage, error) {
	row := q.db.QueryRow(ctx, createCompetitionStage,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.Name,
		arg.StageType,
		arg.SequenceOrder,
		arg.Status,
		arg.StageConfig,
	)
	var i CompetitionStage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Name,
		&i.StageType,
		&i.SequenceOrder,
		&i.Status,
		&i.StageConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createParticipantEntry = `-- name: CreateParticipantEntry :one
INSERT INTO participant_entries (
    organization_id, event_id, category_id, ticket_id, team_id,
    entry_type, display_name, identifier_code, seed_number, lane_number, heat_number, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, organization_id, event_id, category_id, ticket_id, team_id, entry_type, display_name, identifier_code, seed_number, lane_number, heat_number, status, created_at, updated_at
`

type CreateParticipantEntryParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     *uuid.UUID
	TicketID       *uuid.UUID
	TeamID         *uuid.UUID
	EntryType      string
	DisplayName    string
	IdentifierCode pgtype.Text
	SeedNumber     pgtype.Int4
	LaneNumber     pgtype.Int4
	HeatNumber     pgtype.Int4
	Status         string
}

// 5. Participant Entries
func (q *Queries) CreateParticipantEntry(ctx context.Context, arg CreateParticipantEntryParams) (ParticipantEntry, error) {
	row := q.db.QueryRow(ctx, createParticipantEntry,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.TicketID,
		arg.TeamID,
		arg.EntryType,
		arg.DisplayName,
		arg.IdentifierCode,
		arg.SeedNumber,
		arg.LaneNumber,
		arg.HeatNumber,
		arg.Status,
	)
	var i ParticipantEntry
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.TicketID,
		&i.TeamID,
		&i.EntryType,
		&i.DisplayName,
		&i.IdentifierCode,
		&i.SeedNumber,
		&i.LaneNumber,
		&i.HeatNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
    organization_id, event_id, category_id, name, short_name,
    manager_user_id, logo_url, seed_number, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, event_id, category_id, name, short_name, manager_user_id, logo_url, seed_number, status, created_at, updated_at
`

type CreateTeamParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     *uuid.UUID
	Name           string
	ShortName      pgtype.Text
	ManagerUserID  *uuid.UUID
	LogoUrl        pgtype.Text
	SeedNumber     pgtype.Int4
	Status         string
}

// 3. Teams & Rosters
func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.Name,
		arg.ShortName,
		arg.ManagerUserID,
		arg.LogoUrl,
		arg.SeedNumber,
		arg.Status,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Name,
		&i.ShortName,
		&i.ManagerUserID,
		&i.LogoUrl,
		&i.SeedNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeamRosterMember = `-- name: CreateTeamRosterMember :one
INSERT INTO team_rosters (
    team_id, ticket_id, user_id, player_name, jersey_number, position, is_captain, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, team_id, ticket_id, user_id, player_name, jersey_number, position, is_captain, status, created_at, updated_at
`

type CreateTeamRosterMemberParams struct {
	TeamID       uuid.UUID
	TicketID     *uuid.UUID
	UserID       *uuid.UUID
	PlayerName   string
	JerseyNumber pgtype.Int4
	Position     pgtype.Text
	IsCaptain    bool
	Status       string
}

func (q *Queries) CreateTeamRosterMember(ctx context.Context, arg CreateTeamRosterMemberParams) (TeamRoster, error) {
	row := q.db.QueryRow(ctx, createTeamRosterMember,
		arg.TeamID,
		arg.TicketID,
		arg.UserID,
		arg.PlayerName,
		arg.JerseyNumber,
		arg.Position,
		arg.IsCaptain,
		arg.Status,
	)
	var i TeamRoster
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.TicketID,
		&i.UserID,
		&i.PlayerName,
		&i.JerseyNumber,
		&i.Position,
		&i.IsCaptain,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeamRosterMember = `-- name: DeleteTeamRosterMember :exec
DELETE FROM team_rosters WHERE id = $1
`

func (q *Queries) DeleteTeamRosterMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeamRosterMember, id)
	return err
}

const getCompetitionConfigByCategory = `-- name: GetCompetitionConfigByCategory :one
SELECT id, organization_id, event_id, category_id, sport_id, discipline_id, has_timing, has_scoring, has_matches, has_heats_lanes, has_stages, team_based, min_team_size, max_team_size, ranking_strategy, time_precision, rules_config, created_at, updated_at FROM competition_configs
WHERE event_id = $1 AND category_id = $2
`

type GetCompetitionConfigByCategoryParams struct {
	EventID    uuid.UUID
	CategoryID *uuid.UUID
}

func (q *Queries) GetCompetitionConfigByCategory(ctx context.Context, arg GetCompetitionConfigByCategoryParams) (CompetitionConfig, error) {
	row := q.db.QueryRow(ctx, getCompetitionConfigByCategory, arg.EventID, arg.CategoryID)
	var i CompetitionConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.SportID,
		&i.DisciplineID,
		&i.HasTiming,
		&i.HasScoring,
		&i.HasMatches,
		&i.HasHeatsLanes,
		&i.HasStages,
		&i.TeamBased,
		&i.MinTeamSize,
		&i.MaxTeamSize,
		&i.RankingStrategy,
		&i.TimePrecision,
		&i.RulesConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompetitionConfigByEvent = `-- name: GetCompetitionConfigByEvent :one
SELECT id, organization_id, event_id, category_id, sport_id, discipline_id, has_timing, has_scoring, has_matches, has_heats_lanes, has_stages, team_based, min_team_size, max_team_size, ranking_strategy, time_precision, rules_config, created_at, updated_at FROM competition_configs
WHERE event_id = $1 AND category_id IS NULL
`

func (q *Queries) GetCompetitionConfigByEvent(ctx context.Context, eventID uuid.UUID) (CompetitionConfig, error) {
	row := q.db.QueryRow(ctx, getCompetitionConfigByEvent, eventID)
	var i CompetitionConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.SportID,
		&i.DisciplineID,
		&i.HasTiming,
		&i.HasScoring,
		&i.HasMatches,
		&i.HasHeatsLanes,
		&i.HasStages,
		&i.TeamBased,
		&i.MinTeamSize,
		&i.MaxTeamSize,
		&i.RankingStrategy,
		&i.TimePrecision,
		&i.RulesConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompetitionMatchByID = `-- name: GetCompetitionMatchByID :one
SELECT id, organization_id, event_id, stage_id, round_number, match_number, home_team_id, away_team_id, home_entry_id, away_entry_id, scheduled_start_time, venue_court_name, home_score, away_score, match_status, winner_id, score_details, created_at, updated_at FROM competition_matches WHERE id = $1
`

func (q *Queries) GetCompetitionMatchByID(ctx context.Context, id uuid.UUID) (CompetitionMatch, error) {
	row := q.db.QueryRow(ctx, getCompetitionMatchByID, id)
	var i CompetitionMatch
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.StageID,
		&i.RoundNumber,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeEntryID,
		&i.AwayEntryID,
		&i.ScheduledStartTime,
		&i.VenueCourtName,
		&i.HomeScore,
		&i.AwayScore,
		&i.MatchStatus,
		&i.WinnerID,
		&i.ScoreDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompetitionMatchByRoundAndNumber = `-- name: GetCompetitionMatchByRoundAndNumber :one
SELECT id, organization_id, event_id, stage_id, round_number, match_number, home_team_id, away_team_id, home_entry_id, away_entry_id, scheduled_start_time, venue_court_name, home_score, away_score, match_status, winner_id, score_details, created_at, updated_at FROM competition_matches
WHERE stage_id = $1 AND round_number = $2 AND match_number = $3
`

type GetCompetitionMatchByRoundAndNumberParams struct {
	StageID     uuid.UUID
	RoundNumber int32
	MatchNumber int32
}

func (q *Queries) GetCompetitionMatchByRoundAndNumber(ctx context.Context, arg GetCompetitionMatchByRoundAndNumberParams) (CompetitionMatch, error) {
	row := q.db.QueryRow(ctx, getCompetitionMatchByRoundAndNumber, arg.StageID, arg.RoundNumber, arg.MatchNumber)
	var i CompetitionMatch
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.StageID,
		&i.RoundNumber,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeEntryID,
		&i.AwayEntryID,
		&i.ScheduledStartTime,
		&i.VenueCourtName,
		&i.HomeScore,
		&i.AwayScore,
		&i.MatchStatus,
		&i.WinnerID,
		&i.ScoreDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompetitionMatchScoped = `-- name: GetCompetitionMatchScoped :one
SELECT cm.id, cm.organization_id, cm.event_id, cm.stage_id, cm.round_number, cm.match_number, cm.home_team_id, cm.away_team_id, cm.home_entry_id, cm.away_entry_id, cm.scheduled_start_time, cm.venue_court_name, cm.home_score, cm.away_score, cm.match_status, cm.winner_id, cm.score_details, cm.created_at, cm.updated_at
FROM competition_matches cm
JOIN competition_stages cs ON cs.id = cm.stage_id
JOIN events e ON e.id = cs.event_id
WHERE cm.id = $1
  AND cs.event_id = $2
  AND e.organization_id = $3
`

type GetCompetitionMatchScopedParams struct {
	ID             uuid.UUID
	EventID        uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetCompetitionMatchScoped(ctx context.Context, arg GetCompetitionMatchScopedParams) (CompetitionMatch, error) {
	row := q.db.QueryRow(ctx, getCompetitionMatchScoped, arg.ID, arg.EventID, arg.OrganizationID)
	var i CompetitionMatch
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.StageID,
		&i.RoundNumber,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeEntryID,
		&i.AwayEntryID,
		&i.ScheduledStartTime,
		&i.VenueCourtName,
		&i.HomeScore,
		&i.AwayScore,
		&i.MatchStatus,
		&i.WinnerID,
		&i.ScoreDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompetitionResultByEntry = `-- name: GetCompetitionResultByEntry :one
SELECT id, organization_id, event_id, stage_id, category_id, entry_id, rank_overall, rank_category, status, primary_time_ms, secondary_time_ms, points_scored, metrics, notes, created_at, updated_at FROM competition_results
WHERE stage_id = $1 AND entry_id = $2
`

type GetCompetitionResultByEntryParams struct {
	StageID *uuid.UUID
	EntryID uuid.UUID
}

func (q *Queries) GetCompetitionResultByEntry(ctx context.Context, arg GetCompetitionResultByEntryParams) (CompetitionResult, error) {
	row := q.db.QueryRow(ctx, getCompetitionResultByEntry, arg.StageID, arg.EntryID)
	var i CompetitionResult
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.StageID,
		&i.CategoryID,
		&i.EntryID,
		&i.RankOverall,
		&i.RankCategory,
		&i.Status,
		&i.PrimaryTimeMs,
		&i.SecondaryTimeMs,
		&i.PointsScored,
		&i.Metrics,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompetitionStageByID = `-- name: GetCompetitionStageByID :one
SELECT id, organization_id, event_id, category_id, name, stage_type, sequence_order, status, stage_config, created_at, updated_at FROM competition_stages WHERE id = $1
`

func (q *Queries) GetCompetitionStageByID(ctx context.Context, id uuid.UUID) (CompetitionStage, error) {
	row := q.db.QueryRow(ctx, getCompetitionStageByID, id)
	var i CompetitionStage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Name,
		&i.StageType,
		&i.SequenceOrder,
		&i.Status,
		&i.StageConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipantEntryByID = `-- name: GetParticipantEntryByID :one
SELECT id, organization_id, event_id, category_id, ticket_id, team_id, entry_type, display_name, identifier_code, seed_number, lane_number, heat_number, status, created_at, updated_at FROM participant_entries WHERE id = $1
`

func (q *Queries) GetParticipantEntryByID(ctx context.Context, id uuid.UUID) (ParticipantEntry, error) {
	row := q.db.QueryRow(ctx, getParticipantEntryByID, id)
	var i ParticipantEntry
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.TicketID,
		&i.TeamID,
		&i.EntryType,
		&i.DisplayName,
		&i.IdentifierCode,
		&i.SeedNumber,
		&i.LaneNumber,
		&i.HeatNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipantEntryByTicket = `-- name: GetParticipantEntryByTicket :one
SELECT id, organization_id, event_id, category_id, ticket_id, team_id, entry_type, display_name, identifier_code, seed_number, lane_number, heat_number, status, created_at, updated_at FROM participant_entries WHERE ticket_id = $1
`

func (q *Queries) GetParticipantEntryByTicket(ctx context.Context, ticketID *uuid.UUID) (ParticipantEntry, error) {
	row := q.db.QueryRow(ctx, getParticipantEntryByTicket, ticketID)
	var i ParticipantEntry
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.TicketID,
		&i.TeamID,
		&i.EntryType,
		&i.DisplayName,
		&i.IdentifierCode,
		&i.SeedNumber,
		&i.LaneNumber,
		&i.HeatNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSportByID = `-- name: GetSportByID :one
SELECT id, name, governing_body, created_at FROM sports WHERE id = $1
`

func (q *Queries) GetSportByID(ctx context.Context, id string) (Sport, error) {
	row := q.db.QueryRow(ctx, getSportByID, id)
	var i Sport
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GoverningBody,
		&i.CreatedAt,
	)
	return i, err
}

const getSportDisciplineByID = `-- name: GetSportDisciplineByID :one
SELECT id, sport_id, name, default_config, created_at FROM sport_disciplines WHERE id = $1
`

func (q *Queries) GetSportDisciplineByID(ctx context.Context, id string) (SportDiscipline, error) {
	row := q.db.QueryRow(ctx, getSportDisciplineByID, id)
	var i SportDiscipline
	err := row.Scan(
		&i.ID,
		&i.SportID,
		&i.Name,
		&i.DefaultConfig,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, organization_id, event_id, category_id, name, short_name, manager_user_id, logo_url, seed_number, status, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Name,
		&i.ShortName,
		&i.ManagerUserID,
		&i.LogoUrl,
		&i.SeedNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompetitionMatchesByStage = `-- name: ListCompetitionMatchesByStage :many
SELECT id, organization_id, event_id, stage_id, round_number, match_number, home_team_id, away_team_id, home_entry_id, away_entry_id, scheduled_start_time, venue_court_name, home_score, away_score, match_status, winner_id, score_details, created_at, updated_at FROM competition_matches
WHERE stage_id = $1
ORDER BY round_number ASC, match_number ASC
`

func (q *Queries) ListCompetitionMatchesByStage(ctx context.Context, stageID uuid.UUID) ([]CompetitionMatch, error) {
	rows, err := q.db.Query(ctx, listCompetitionMatchesByStage, stageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitionMatch
	for rows.Next() {
		var i CompetitionMatch
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.StageID,
			&i.RoundNumber,
			&i.MatchNumber,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeEntryID,
			&i.AwayEntryID,
			&i.ScheduledStartTime,
			&i.VenueCourtName,
			&i.HomeScore,
			&i.AwayScore,
			&i.MatchStatus,
			&i.WinnerID,
			&i.ScoreDetails,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionResultsByEvent = `-- name: ListCompetitionResultsByEvent :many
SELECT cr.id, cr.organization_id, cr.event_id, cr.stage_id, cr.category_id, cr.entry_id, cr.rank_overall, cr.rank_category, cr.status, cr.primary_time_ms, cr.secondary_time_ms, cr.points_scored, cr.metrics, cr.notes, cr.created_at, cr.updated_at, pe.display_name, pe.identifier_code, pe.entry_type, pe.team_id
FROM competition_results cr
JOIN participant_entries pe ON pe.id = cr.entry_id
WHERE cr.event_id = $1
ORDER BY cr.rank_overall ASC NULLS LAST, cr.points_scored DESC, cr.primary_time_ms ASC NULLS LAST
`

type ListCompetitionResultsByEventRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	StageID         *uuid.UUID
	CategoryID      *uuid.UUID
	EntryID         uuid.UUID
	RankOverall     pgtype.Int4
	RankCategory    pgtype.Int4
	Status          string
	PrimaryTimeMs   pgtype.Int8
	SecondaryTimeMs pgtype.Int8
	PointsScored    pgtype.Numeric
	Metrics         []byte
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DisplayName     string
	IdentifierCode  pgtype.Text
	EntryType       string
	TeamID          *uuid.UUID
}

func (q *Queries) ListCompetitionResultsByEvent(ctx context.Context, eventID uuid.UUID) ([]ListCompetitionResultsByEventRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionResultsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionResultsByEventRow
	for rows.Next() {
		var i ListCompetitionResultsByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.StageID,
			&i.CategoryID,
			&i.EntryID,
			&i.RankOverall,
			&i.RankCategory,
			&i.Status,
			&i.PrimaryTimeMs,
			&i.SecondaryTimeMs,
			&i.PointsScored,
			&i.Metrics,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.IdentifierCode,
			&i.EntryType,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionResultsByStage = `-- name: ListCompetitionResultsByStage :many
SELECT cr.id, cr.organization_id, cr.event_id, cr.stage_id, cr.category_id, cr.entry_id, cr.rank_overall, cr.rank_category, cr.status, cr.primary_time_ms, cr.secondary_time_ms, cr.points_scored, cr.metrics, cr.notes, cr.created_at, cr.updated_at, pe.display_name, pe.identifier_code, pe.entry_type, pe.team_id, pe.lane_number, pe.heat_number
FROM competition_results cr
JOIN participant_entries pe ON pe.id = cr.entry_id
WHERE cr.stage_id = $1
ORDER BY cr.rank_overall ASC NULLS LAST, cr.primary_time_ms ASC NULLS LAST, cr.points_scored DESC, pe.display_name ASC
`

type ListCompetitionResultsByStageRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	StageID         *uuid.UUID
	CategoryID      *uuid.UUID
	EntryID         uuid.UUID
	RankOverall     pgtype.Int4
	RankCategory    pgtype.Int4
	Status          string
	PrimaryTimeMs   pgtype.Int8
	SecondaryTimeMs pgtype.Int8
	PointsScored    pgtype.Numeric
	Metrics         []byte
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DisplayName     string
	IdentifierCode  pgtype.Text
	EntryType       string
	TeamID          *uuid.UUID
	LaneNumber      pgtype.Int4
	HeatNumber      pgtype.Int4
}

func (q *Queries) ListCompetitionResultsByStage(ctx context.Context, stageID *uuid.UUID) ([]ListCompetitionResultsByStageRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionResultsByStage, stageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionResultsByStageRow
	for rows.Next() {
		var i ListCompetitionResultsByStageRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.StageID,
			&i.CategoryID,
			&i.EntryID,
			&i.RankOverall,
			&i.RankCategory,
			&i.Status,
			&i.PrimaryTimeMs,
			&i.SecondaryTimeMs,
			&i.PointsScored,
			&i.Metrics,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.IdentifierCode,
			&i.EntryType,
			&i.TeamID,
			&i.LaneNumber,
			&i.HeatNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionStagesByEvent = `-- name: ListCompetitionStagesByEvent :many
SELECT id, organization_id, event_id, category_id, name, stage_type, sequence_order, status, stage_config, created_at, updated_at FROM competition_stages
WHERE event_id = $1
ORDER BY sequence_order ASC, name ASC
`

func (q *Queries) ListCompetitionStagesByEvent(ctx context.Context, eventID uuid.UUID) ([]CompetitionStage, error) {
	rows, err := q.db.Query(ctx, listCompetitionStagesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitionStage
	for rows.Next() {
		var i CompetitionStage
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.Name,
			&i.StageType,
			&i.SequenceOrder,
			&i.Status,
			&i.StageConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByEntry = `-- name: ListObservationsByEntry :many
SELECT id, organization_id, event_id, stage_id, match_id, entry_id, observation_type, source, numeric_value, text_value, observed_at_ms, metadata, created_at FROM competition_observations
WHERE entry_id = $1
ORDER BY observed_at_ms ASC, created_at ASC
`

func (q *Queries) ListObservationsByEntry(ctx context.Context, entryID *uuid.UUID) ([]CompetitionObservation, error) {
	rows, err := q.db.Query(ctx, listObservationsByEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitionObservation
	for rows.Next() {
		var i CompetitionObservation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.StageID,
			&i.MatchID,
			&i.EntryID,
			&i.ObservationType,
			&i.Source,
			&i.NumericValue,
			&i.TextValue,
			&i.ObservedAtMs,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByMatch = `-- name: ListObservationsByMatch :many
SELECT id, organization_id, event_id, stage_id, match_id, entry_id, observation_type, source, numeric_value, text_value, observed_at_ms, metadata, created_at FROM competition_observations
WHERE match_id = $1
ORDER BY observed_at_ms ASC, created_at ASC
`

func (q *Queries) ListObservationsByMatch(ctx context.Context, matchID *uuid.UUID) ([]CompetitionObservation, error) {
	rows, err := q.db.Query(ctx, listObservationsByMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitionObservation
	for rows.Next() {
		var i CompetitionObservation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.StageID,
			&i.MatchID,
			&i.EntryID,
			&i.ObservationType,
			&i.Source,
			&i.NumericValue,
			&i.TextValue,
			&i.ObservedAtMs,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByStage = `-- name: ListObservationsByStage :many
SELECT id, organization_id, event_id, stage_id, match_id, entry_id, observation_type, source, numeric_value, text_value, observed_at_ms, metadata, created_at FROM competition_observations
WHERE stage_id = $1
ORDER BY observed_at_ms ASC, created_at ASC
`

func (q *Queries) ListObservationsByStage(ctx context.Context, stageID *uuid.UUID) ([]CompetitionObservation, error) {
	rows, err := q.db.Query(ctx, listObservationsByStage, stageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitionObservation
	for rows.Next() {
		var i CompetitionObservation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.StageID,
			&i.MatchID,
			&i.EntryID,
			&i.ObservationType,
			&i.Source,
			&i.NumericValue,
			&i.TextValue,
			&i.ObservedAtMs,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantEntriesByEvent = `-- name: ListParticipantEntriesByEvent :many
SELECT id, organization_id, event_id, category_id, ticket_id, team_id, entry_type, display_name, identifier_code, seed_number, lane_number, heat_number, status, created_at, updated_at FROM participant_entries
WHERE event_id = $1
ORDER BY heat_number ASC NULLS LAST, lane_number ASC NULLS LAST, seed_number ASC NULLS LAST, display_name ASC
`

func (q *Queries) ListParticipantEntriesByEvent(ctx context.Context, eventID uuid.UUID) ([]ParticipantEntry, error) {
	rows, err := q.db.Query(ctx, listParticipantEntriesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParticipantEntry
	for rows.Next() {
		var i ParticipantEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.TicketID,
			&i.TeamID,
			&i.EntryType,
			&i.DisplayName,
			&i.IdentifierCode,
			&i.SeedNumber,
			&i.LaneNumber,
			&i.HeatNumber,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSportDisciplinesBySport = `-- name: ListSportDisciplinesBySport :many
SELECT id, sport_id, name, default_config, created_at FROM sport_disciplines WHERE sport_id = $1 ORDER BY name ASC
`

func (q *Queries) ListSportDisciplinesBySport(ctx context.Context, sportID string) ([]SportDiscipline, error) {
	rows, err := q.db.Query(ctx, listSportDisciplinesBySport, sportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SportDiscipline
	for rows.Next() {
		var i SportDiscipline
		if err := rows.Scan(
			&i.ID,
			&i.SportID,
			&i.Name,
			&i.DefaultConfig,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSports = `-- name: ListSports :many

SELECT id, name, governing_body, created_at FROM sports ORDER BY name ASC
`

// Multi-Sport Generic Competition Queries
// 1. Sports & Disciplines
func (q *Queries) ListSports(ctx context.Context) ([]Sport, error) {
	rows, err := q.db.Query(ctx, listSports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sport
	for rows.Next() {
		var i Sport
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GoverningBody,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamRosterByTeam = `-- name: ListTeamRosterByTeam :many
SELECT id, team_id, ticket_id, user_id, player_name, jersey_number, position, is_captain, status, created_at, updated_at FROM team_rosters
WHERE team_id = $1
ORDER BY is_captain DESC, jersey_number ASC NULLS LAST, player_name ASC
`

func (q *Queries) ListTeamRosterByTeam(ctx context.Context, teamID uuid.UUID) ([]TeamRoster, error) {
	rows, err := q.db.Query(ctx, listTeamRosterByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamRoster
	for rows.Next() {
		var i TeamRoster
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.TicketID,
			&i.UserID,
			&i.PlayerName,
			&i.JerseyNumber,
			&i.Position,
			&i.IsCaptain,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByEvent = `-- name: ListTeamsByEvent :many
SELECT id, organization_id, event_id, category_id, name, short_name, manager_user_id, logo_url, seed_number, status, created_at, updated_at FROM teams
WHERE event_id = $1
ORDER BY seed_number ASC NULLS LAST, name ASC
`

func (q *Queries) ListTeamsByEvent(ctx context.Context, eventID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.Name,
			&i.ShortName,
			&i.ManagerUserID,
			&i.LogoUrl,
			&i.SeedNumber,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rankCompetitionStageByPoints = `-- name: RankCompetitionStageByPoints :exec
UPDATE competition_results r
SET rank_overall = s.rnk, updated_at = now()
FROM (
    SELECT cr.id, RANK() OVER (
        ORDER BY cr.points_scored DESC, (cr.metrics->>'goal_difference')::numeric DESC NULLS LAST, (cr.metrics->>'goals_for')::numeric DESC NULLS LAST
    ) AS rnk
    FROM competition_results cr
    WHERE cr.stage_id = $1 AND cr.status = 'FINISHED'
) s
WHERE r.id = s.id
`

func (q *Queries) RankCompetitionStageByPoints(ctx context.Context, stageID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, rankCompetitionStageByPoints, stageID)
	return err
}

const rankCompetitionStageByTime = `-- name: RankCompetitionStageByTime :exec
UPDATE competition_results r
SET rank_overall = s.rnk, updated_at = now()
FROM (
    SELECT cr.id, RANK() OVER (
        ORDER BY COALESCE(cr.primary_time_ms, cr.secondary_time_ms) ASC, cr.secondary_time_ms ASC NULLS LAST
    ) AS rnk
    FROM competition_results cr
    WHERE cr.stage_id = $1 AND cr.status = 'FINISHED'
      AND COALESCE(cr.primary_time_ms, cr.secondary_time_ms) IS NOT NULL
) s
WHERE r.id = s.id
`

func (q *Queries) RankCompetitionStageByTime(ctx context.Context, stageID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, rankCompetitionStageByTime, stageID)
	return err
}

const updateCompetitionMatchParticipants = `-- name: UpdateCompetitionMatchParticipants :exec
UPDATE competition_matches
SET home_entry_id = COALESCE($2, home_entry_id),
    away_entry_id = COALESCE($3, away_entry_id),
    updated_at = now()
WHERE stage_id = $1 AND round_number = $4 AND match_number = $5
`

type UpdateCompetitionMatchParticipantsParams struct {
	StageID     uuid.UUID
	HomeEntryID *uuid.UUID
	AwayEntryID *uuid.UUID
	RoundNumber int32
	MatchNumber int32
}

func (q *Queries) UpdateCompetitionMatchParticipants(ctx context.Context, arg UpdateCompetitionMatchParticipantsParams) error {
	_, err := q.db.Exec(ctx, updateCompetitionMatchParticipants,
		arg.StageID,
		arg.HomeEntryID,
		arg.AwayEntryID,
		arg.RoundNumber,
		arg.MatchNumber,
	)
	return err
}

const updateCompetitionMatchParticipantsScheduled = `-- name: UpdateCompetitionMatchParticipantsScheduled :execrows
UPDATE competition_matches
SET home_entry_id = COALESCE($2, home_entry_id),
    away_entry_id = COALESCE($3, away_entry_id),
    updated_at = now()
WHERE stage_id = $1 AND round_number = $4 AND match_number = $5 AND match_status = 'SCHEDULED'
`

type UpdateCompetitionMatchParticipantsScheduledParams struct {
	StageID     uuid.UUID
	HomeEntryID *uuid.UUID
	AwayEntryID *uuid.UUID
	RoundNumber int32
	MatchNumber int32
}

func (q *Queries) UpdateCompetitionMatchParticipantsScheduled(ctx context.Context, arg UpdateCompetitionMatchParticipantsScheduledParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCompetitionMatchParticipantsScheduled,
		arg.StageID,
		arg.HomeEntryID,
		arg.AwayEntryID,
		arg.RoundNumber,
		arg.MatchNumber,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCompetitionMatchScore = `-- name: UpdateCompetitionMatchScore :one
UPDATE competition_matches
SET home_score = $2,
    away_score = $3,
    match_status = $4,
    winner_id = $5,
    score_details = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, stage_id, round_number, match_number, home_team_id, away_team_id, home_entry_id, away_entry_id, scheduled_start_time, venue_court_name, home_score, away_score, match_status, winner_id, score_details, created_at, updated_at
`

type UpdateCompetitionMatchScoreParams struct {
	ID           uuid.UUID
	HomeScore    int32
	AwayScore    int32
	MatchStatus  string
	WinnerID     *uuid.UUID
	ScoreDetails []byte
}

func (q *Queries) UpdateCompetitionMatchScore(ctx context.Context, arg UpdateCompetitionMatchScoreParams) (CompetitionMatch, error) {
	row := q.db.QueryRow(ctx, updateCompetitionMatchScore,
		arg.ID,
		arg.HomeScore,
		arg.AwayScore,
		arg.MatchStatus,
		arg.WinnerID,
		arg.ScoreDetails,
	)
	var i CompetitionMatch
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.StageID,
		&i.RoundNumber,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeEntryID,
		&i.AwayEntryID,
		&i.ScheduledStartTime,
		&i.VenueCourtName,
		&i.HomeScore,
		&i.AwayScore,
		&i.MatchStatus,
		&i.WinnerID,
		&i.ScoreDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompetitionMatchScoreScoped = `-- name: UpdateCompetitionMatchScoreScoped :one
UPDATE competition_matches cm
SET home_score = $2,
    away_score = $3,
    match_status = $4,
    winner_id = $5,
    score_details = $6,
    updated_at = now()
FROM competition_stages cs
JOIN events e ON e.id = cs.event_id
WHERE cm.id = $1
  AND cm.stage_id = cs.id
  AND cs.event_id = $7
  AND e.organization_id = $8
RETURNING cm.id, cm.organization_id, cm.event_id, cm.stage_id, cm.round_number, cm.match_number, cm.home_team_id, cm.away_team_id, cm.home_entry_id, cm.away_entry_id, cm.scheduled_start_time, cm.venue_court_name, cm.home_score, cm.away_score, cm.match_status, cm.winner_id, cm.score_details, cm.created_at, cm.updated_at
`

type UpdateCompetitionMatchScoreScopedParams struct {
	ID             uuid.UUID
	HomeScore      int32
	AwayScore      int32
	MatchStatus    string
	WinnerID       *uuid.UUID
	ScoreDetails   []byte
	EventID        uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) UpdateCompetitionMatchScoreScoped(ctx context.Context, arg UpdateCompetitionMatchScoreScopedParams) (CompetitionMatch, error) {
	row := q.db.QueryRow(ctx, updateCompetitionMatchScoreScoped,
		arg.ID,
		arg.HomeScore,
		arg.AwayScore,
		arg.MatchStatus,
		arg.WinnerID,
		arg.ScoreDetails,
		arg.EventID,
		arg.OrganizationID,
	)
	var i CompetitionMatch
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.StageID,
		&i.RoundNumber,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeEntryID,
		&i.AwayEntryID,
		&i.ScheduledStartTime,
		&i.VenueCourtName,
		&i.HomeScore,
		&i.AwayScore,
		&i.MatchStatus,
		&i.WinnerID,
		&i.ScoreDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompetitionStageStatus = `-- name: UpdateCompetitionStageStatus :one
UPDATE competition_stages
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, category_id, name, stage_type, sequence_order, status, stage_config, created_at, updated_at
`

type UpdateCompetitionStageStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateCompetitionStageStatus(ctx context.Context, arg UpdateCompetitionStageStatusParams) (CompetitionStage, error) {
	row := q.db.QueryRow(ctx, updateCompetitionStageStatus, arg.ID, arg.Status)
	var i CompetitionStage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Name,
		&i.StageType,
		&i.SequenceOrder,
		&i.Status,
		&i.StageConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParticipantEntryStatus = `-- name: UpdateParticipantEntryStatus :one
UPDATE participant_entries
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, category_id, ticket_id, team_id, entry_type, display_name, identifier_code, seed_number, lane_number, heat_number, status, created_at, updated_at
`

type UpdateParticipantEntryStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateParticipantEntryStatus(ctx context.Context, arg UpdateParticipantEntryStatusParams) (ParticipantEntry, error) {
	row := q.db.QueryRow(ctx, updateParticipantEntryStatus, arg.ID, arg.Status)
	var i ParticipantEntry
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.TicketID,
		&i.TeamID,
		&i.EntryType,
		&i.DisplayName,
		&i.IdentifierCode,
		&i.SeedNumber,
		&i.LaneNumber,
		&i.HeatNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamStatus = `-- name: UpdateTeamStatus :one
UPDATE teams
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, category_id, name, short_name, manager_user_id, logo_url, seed_number, status, created_at, updated_at
`

type UpdateTeamStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateTeamStatus(ctx context.Context, arg UpdateTeamStatusParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeamStatus, arg.ID, arg.Status)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Name,
		&i.ShortName,
		&i.ManagerUserID,
		&i.LogoUrl,
		&i.SeedNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCompetitionConfig = `-- name: UpsertCompetitionConfig :one
INSERT INTO competition_configs (
    organization_id, event_id, category_id, sport_id, discipline_id,
    has_timing, has_scoring, has_matches, has_heats_lanes, has_stages, team_based,
    min_team_size, max_team_size, ranking_strategy, time_precision, rules_config
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16
)
ON CONFLICT (event_id, category_id) DO UPDATE SET
    sport_id = EXCLUDED.sport_id,
    discipline_id = EXCLUDED.discipline_id,
    has_timing = EXCLUDED.has_timing,
    has_scoring = EXCLUDED.has_scoring,
    has_matches = EXCLUDED.has_matches,
    has_heats_lanes = EXCLUDED.has_heats_lanes,
    has_stages = EXCLUDED.has_stages,
    team_based = EXCLUDED.team_based,
    min_team_size = EXCLUDED.min_team_size,
    max_team_size = EXCLUDED.max_team_size,
    ranking_strategy = EXCLUDED.ranking_strategy,
    time_precision = EXCLUDED.time_precision,
    rules_config = EXCLUDED.rules_config,
    updated_at = now()
RETURNING id, organization_id, event_id, category_id, sport_id, discipline_id, has_timing, has_scoring, has_matches, has_heats_lanes, has_stages, team_based, min_team_size, max_team_size, ranking_strategy, time_precision, rules_config, created_at, updated_at
`

type UpsertCompetitionConfigParams struct {
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	CategoryID      *uuid.UUID
	SportID         string
	DisciplineID    string
	HasTiming       bool
	HasScoring      bool
	HasMatches      bool
	HasHeatsLanes   bool
	HasStages       bool
	TeamBased       bool
	MinTeamSize     int32
	MaxTeamSize     int32
	RankingStrategy string
	TimePrecision   string
	RulesConfig     []byte
}

// 2. Competition Configs
func (q *Queries) UpsertCompetitionConfig(ctx context.Context, arg UpsertCompetitionConfigParams) (CompetitionConfig, error) {
	row := q.db.QueryRow(ctx, upsertCompetitionConfig,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.SportID,
		arg.DisciplineID,
		arg.HasTiming,
		arg.HasScoring,
		arg.HasMatches,
		arg.HasHeatsLanes,
		arg.HasStages,
		arg.TeamBased,
		arg.MinTeamSize,
		arg.MaxTeamSize,
		arg.RankingStrategy,
		arg.TimePrecision,
		arg.RulesConfig,
	)
	var i CompetitionConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.SportID,
		&i.DisciplineID,
		&i.HasTiming,
		&i.HasScoring,
		&i.HasMatches,
		&i.HasHeatsLanes,
		&i.HasStages,
		&i.TeamBased,
		&i.MinTeamSize,
		&i.MaxTeamSize,
		&i.RankingStrategy,
		&i.TimePrecision,
		&i.RulesConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCompetitionResult = `-- name: UpsertCompetitionResult :one
INSERT INTO competition_results (
    organization_id, event_id, stage_id, category_id, entry_id,
    rank_overall, rank_category, status, primary_time_ms, secondary_time_ms,
    points_scored, metrics, notes
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13
)
ON CONFLICT (stage_id, entry_id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    rank_overall = EXCLUDED.rank_overall,
    rank_category = EXCLUDED.rank_category,
    status = EXCLUDED.status,
    primary_time_ms = EXCLUDED.primary_time_ms,
    secondary_time_ms = EXCLUDED.secondary_time_ms,
    points_scored = EXCLUDED.points_scored,
    metrics = EXCLUDED.metrics,
    notes = EXCLUDED.notes,
    updated_at = now()
RETURNING id, organization_id, event_id, stage_id, category_id, entry_id, rank_overall, rank_category, status, primary_time_ms, secondary_time_ms, points_scored, metrics, notes, created_at, updated_at
`

type UpsertCompetitionResultParams struct {
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	StageID         *uuid.UUID
	CategoryID      *uuid.UUID
	EntryID         uuid.UUID
	RankOverall     pgtype.Int4
	RankCategory    pgtype.Int4
	Status          string
	PrimaryTimeMs   pgtype.Int8
	SecondaryTimeMs pgtype.Int8
	PointsScored    pgtype.Numeric
	Metrics         []byte
	Notes           pgtype.Text
}

// 7. Competition Results
func (q *Queries) UpsertCompetitionResult(ctx context.Context, arg UpsertCompetitionResultParams) (CompetitionResult, error) {
	row := q.db.QueryRow(ctx, upsertCompetitionResult,
		arg.OrganizationID,
		arg.EventID,
		arg.StageID,
		arg.CategoryID,
		arg.EntryID,
		arg.RankOverall,
		arg.RankCategory,
		arg.Status,
		arg.PrimaryTimeMs,
		arg.SecondaryTimeMs,
		arg.PointsScored,
		arg.Metrics,
		arg.Notes,
	)
	var i CompetitionResult
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.StageID,
		&i.CategoryID,
		&i.EntryID,
		&i.RankOverall,
		&i.RankCategory,
		&i.Status,
		&i.PrimaryTimeMs,
		&i.SecondaryTimeMs,
		&i.PointsScored,
		&i.Metrics,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
