// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enterprise.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (organization_id, name, key_prefix, key_hash, scopes, rate_limit_per_min)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, name, key_prefix, key_hash, scopes, rate_limit_per_min, last_used_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	OrganizationID  uuid.UUID
	Name            string
	KeyPrefix       string
	KeyHash         string
	Scopes          []byte
	RateLimitPerMin int32
}

// Phase 23 — Enterprise API: API keys, webhook endpoints, delivery ledger.
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.OrganizationID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Scopes,
		arg.RateLimitPerMin,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.RateLimitPerMin,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (organization_id, url, secret, events, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, url, secret, events, is_active, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	OrganizationID uuid.UUID
	Url            string
	Secret         string
	Events         []byte
	IsActive       bool
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.OrganizationID,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.IsActive,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
DELETE FROM webhook_endpoints WHERE id = $1 AND organization_id = $2
`

type DeleteWebhookEndpointParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) error {
	_, err := q.db.Exec(ctx, deleteWebhookEndpoint, arg.ID, arg.OrganizationID)
	return err
}

const enqueueWebhookDelivery = `-- name: EnqueueWebhookDelivery :one
INSERT INTO webhook_deliveries (endpoint_id, organization_id, event_type, event_key, payload)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (endpoint_id, event_key) DO NOTHING
RETURNING id, endpoint_id, organization_id, event_type, event_key, payload, status, attempts, last_error, next_attempt_at, delivered_at, created_at, updated_at
`

type EnqueueWebhookDeliveryParams struct {
	EndpointID     uuid.UUID
	OrganizationID uuid.UUID
	EventType      string
	EventKey       string
	Payload        []byte
}

func (q *Queries) EnqueueWebhookDelivery(ctx context.Context, arg EnqueueWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, enqueueWebhookDelivery,
		arg.EndpointID,
		arg.OrganizationID,
		arg.EventType,
		arg.EventKey,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.OrganizationID,
		&i.EventType,
		&i.EventKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, organization_id, name, key_prefix, key_hash, scopes, rate_limit_per_min, last_used_at, revoked_at, created_at FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.RateLimitPerMin,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookEndpointByID = `-- name: GetWebhookEndpointByID :one
SELECT id, organization_id, url, secret, events, is_active, created_at, updated_at FROM webhook_endpoints WHERE id = $1
`

func (q *Queries) GetWebhookEndpointByID(ctx context.Context, id uuid.UUID) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByID, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeysByOrg = `-- name: ListAPIKeysByOrg :many
SELECT id, organization_id, name, key_prefix, key_hash, scopes, rate_limit_per_min, last_used_at, revoked_at, created_at FROM api_keys
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByOrg(ctx context.Context, organizationID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.RateLimitPerMin,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWebhookEndpointsForEvent = `-- name: ListActiveWebhookEndpointsForEvent :many
SELECT id, organization_id, url, secret, events, is_active, created_at, updated_at FROM webhook_endpoints
WHERE organization_id = $1
  AND is_active = true
  AND events ? $2::text
`

type ListActiveWebhookEndpointsForEventParams struct {
	OrganizationID uuid.UUID
	EventType      string
}

func (q *Queries) ListActiveWebhookEndpointsForEvent(ctx context.Context, arg ListActiveWebhookEndpointsForEventParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listActiveWebhookEndpointsForEvent, arg.OrganizationID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueWebhookDeliveries = `-- name: ListDueWebhookDeliveries :many
SELECT id, endpoint_id, organization_id, event_type, event_key, payload, status, attempts, last_error, next_attempt_at, delivered_at, created_at, updated_at FROM webhook_deliveries
WHERE status = 'PENDING' AND next_attempt_at <= now()
ORDER BY next_attempt_at
LIMIT $1
`

func (q *Queries) ListDueWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDueWebhookDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.OrganizationID,
			&i.EventType,
			&i.EventKey,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesByOrg = `-- name: ListWebhookDeliveriesByOrg :many
SELECT id, endpoint_id, organization_id, event_type, event_key, payload, status, attempts, last_error, next_attempt_at, delivered_at, created_at, updated_at FROM webhook_deliveries
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesByOrgParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListWebhookDeliveriesByOrg(ctx context.Context, arg ListWebhookDeliveriesByOrgParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.OrganizationID,
			&i.EventType,
			&i.EventKey,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpointsByOrg = `-- name: ListWebhookEndpointsByOrg :many
SELECT id, organization_id, url, secret, events, is_active, created_at, updated_at FROM webhook_endpoints
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhookEndpointsByOrg(ctx context.Context, organizationID uuid.UUID) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpointsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :exec
UPDATE webhook_deliveries
SET status = 'DELIVERED', delivered_at = now(), attempts = attempts + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkWebhookDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookDelivered, id)
	return err
}

const markWebhookRetry = `-- name: MarkWebhookRetry :exec
UPDATE webhook_deliveries
SET attempts = attempts + 1,
    last_error = $2,
    next_attempt_at = $3,
    status = CASE WHEN attempts + 1 >= $4 THEN 'DEAD' ELSE 'PENDING' END,
    updated_at = now()
WHERE id = $1
`

type MarkWebhookRetryParams struct {
	ID            uuid.UUID
	LastError     pgtype.Text
	NextAttemptAt pgtype.Timestamptz
	Attempts      int32
}

func (q *Queries) MarkWebhookRetry(ctx context.Context, arg MarkWebhookRetryParams) error {
	_, err := q.db.Exec(ctx, markWebhookRetry,
		arg.ID,
		arg.LastError,
		arg.NextAttemptAt,
		arg.Attempts,
	)
	return err
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND organization_id = $2 AND revoked_at IS NULL
RETURNING id, organization_id, name, key_prefix, key_hash, scopes, rate_limit_per_min, last_used_at, revoked_at, created_at
`

type RevokeAPIKeyParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.OrganizationID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.RateLimitPerMin,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
