// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCategoriesForEvent = `-- name: CountCategoriesForEvent :one
SELECT count(*) FROM event_categories WHERE event_id = $1
`

func (q *Queries) CountCategoriesForEvent(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriesForEvent, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (organization_id, name, slug, description, event_type,
    venue_name, venue_address, starts_at, ends_at, faq, terms, waiver)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, organization_id, name, slug, description, event_type, status, banner_object_key, logo_object_key, venue_name, venue_address, starts_at, ends_at, faq, terms, waiver, published_at, created_at, updated_at
`

type CreateEventParams struct {
	OrganizationID uuid.UUID
	Name           string
	Slug           string
	Description    pgtype.Text
	EventType      string
	VenueName      pgtype.Text
	VenueAddress   pgtype.Text
	StartsAt       pgtype.Timestamptz
	EndsAt         pgtype.Timestamptz
	Faq            pgtype.Text
	Terms          pgtype.Text
	Waiver         pgtype.Text
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.EventType,
		arg.VenueName,
		arg.VenueAddress,
		arg.StartsAt,
		arg.EndsAt,
		arg.Faq,
		arg.Terms,
		arg.Waiver,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.BannerObjectKey,
		&i.LogoObjectKey,
		&i.VenueName,
		&i.VenueAddress,
		&i.StartsAt,
		&i.EndsAt,
		&i.Faq,
		&i.Terms,
		&i.Waiver,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1 AND organization_id = $2
`

type DeleteEventParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.Exec(ctx, deleteEvent, arg.ID, arg.OrganizationID)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, organization_id, name, slug, description, event_type, status, banner_object_key, logo_object_key, venue_name, venue_address, starts_at, ends_at, faq, terms, waiver, published_at, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.BannerObjectKey,
		&i.LogoObjectKey,
		&i.VenueName,
		&i.VenueAddress,
		&i.StartsAt,
		&i.EndsAt,
		&i.Faq,
		&i.Terms,
		&i.Waiver,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByOrgAndSlug = `-- name: GetEventByOrgAndSlug :one
SELECT id, organization_id, name, slug, description, event_type, status, banner_object_key, logo_object_key, venue_name, venue_address, starts_at, ends_at, faq, terms, waiver, published_at, created_at, updated_at FROM events WHERE organization_id = $1 AND slug = $2
`

type GetEventByOrgAndSlugParams struct {
	OrganizationID uuid.UUID
	Slug           string
}

func (q *Queries) GetEventByOrgAndSlug(ctx context.Context, arg GetEventByOrgAndSlugParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByOrgAndSlug, arg.OrganizationID, arg.Slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.BannerObjectKey,
		&i.LogoObjectKey,
		&i.VenueName,
		&i.VenueAddress,
		&i.StartsAt,
		&i.EndsAt,
		&i.Faq,
		&i.Terms,
		&i.Waiver,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedEventByOrgAndSlug = `-- name: GetPublishedEventByOrgAndSlug :one
SELECT e.id, e.organization_id, e.name, e.slug, e.description, e.event_type, e.status, e.banner_object_key, e.logo_object_key, e.venue_name, e.venue_address, e.starts_at, e.ends_at, e.faq, e.terms, e.waiver, e.published_at, e.created_at, e.updated_at FROM events e
JOIN organizations o ON o.id = e.organization_id
WHERE o.slug = $1 AND e.slug = $2 AND e.status = 'published'
`

type GetPublishedEventByOrgAndSlugParams struct {
	Slug   string
	Slug_2 string
}

func (q *Queries) GetPublishedEventByOrgAndSlug(ctx context.Context, arg GetPublishedEventByOrgAndSlugParams) (Event, error) {
	row := q.db.QueryRow(ctx, getPublishedEventByOrgAndSlug, arg.Slug, arg.Slug_2)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.BannerObjectKey,
		&i.LogoObjectKey,
		&i.VenueName,
		&i.VenueAddress,
		&i.StartsAt,
		&i.EndsAt,
		&i.Faq,
		&i.Terms,
		&i.Waiver,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsByOrg = `-- name: ListEventsByOrg :many
SELECT id, organization_id, name, slug, description, event_type, status, banner_object_key, logo_object_key, venue_name, venue_address, starts_at, ends_at, faq, terms, waiver, published_at, created_at, updated_at FROM events WHERE organization_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListEventsByOrg(ctx context.Context, organizationID uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.EventType,
			&i.Status,
			&i.BannerObjectKey,
			&i.LogoObjectKey,
			&i.VenueName,
			&i.VenueAddress,
			&i.StartsAt,
			&i.EndsAt,
			&i.Faq,
			&i.Terms,
			&i.Waiver,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEventsByOrgSlug = `-- name: ListPublishedEventsByOrgSlug :many
SELECT e.id, e.organization_id, e.name, e.slug, e.description, e.event_type, e.status, e.banner_object_key, e.logo_object_key, e.venue_name, e.venue_address, e.starts_at, e.ends_at, e.faq, e.terms, e.waiver, e.published_at, e.created_at, e.updated_at FROM events e
JOIN organizations o ON o.id = e.organization_id
WHERE o.slug = $1 AND e.status = 'published'
ORDER BY e.starts_at NULLS LAST, e.created_at DESC
`

func (q *Queries) ListPublishedEventsByOrgSlug(ctx context.Context, slug string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listPublishedEventsByOrgSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.EventType,
			&i.Status,
			&i.BannerObjectKey,
			&i.LogoObjectKey,
			&i.VenueName,
			&i.VenueAddress,
			&i.StartsAt,
			&i.EndsAt,
			&i.Faq,
			&i.Terms,
			&i.Waiver,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventMediaKey = `-- name: SetEventMediaKey :one
UPDATE events SET banner_object_key = COALESCE($2, banner_object_key),
    logo_object_key = COALESCE($3, logo_object_key), updated_at = now()
WHERE id = $1 AND organization_id = $4
RETURNING id, organization_id, name, slug, description, event_type, status, banner_object_key, logo_object_key, venue_name, venue_address, starts_at, ends_at, faq, terms, waiver, published_at, created_at, updated_at
`

type SetEventMediaKeyParams struct {
	ID              uuid.UUID
	BannerObjectKey pgtype.Text
	LogoObjectKey   pgtype.Text
	OrganizationID  uuid.UUID
}

func (q *Queries) SetEventMediaKey(ctx context.Context, arg SetEventMediaKeyParams) (Event, error) {
	row := q.db.QueryRow(ctx, setEventMediaKey,
		arg.ID,
		arg.BannerObjectKey,
		arg.LogoObjectKey,
		arg.OrganizationID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.BannerObjectKey,
		&i.LogoObjectKey,
		&i.VenueName,
		&i.VenueAddress,
		&i.StartsAt,
		&i.EndsAt,
		&i.Faq,
		&i.Terms,
		&i.Waiver,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    name = $2, description = $3, event_type = $4,
    venue_name = $5, venue_address = $6, starts_at = $7, ends_at = $8,
    faq = $9, terms = $10, waiver = $11, updated_at = now()
WHERE id = $1 AND organization_id = $12
RETURNING id, organization_id, name, slug, description, event_type, status, banner_object_key, logo_object_key, venue_name, venue_address, starts_at, ends_at, faq, terms, waiver, published_at, created_at, updated_at
`

type UpdateEventParams struct {
	ID             uuid.UUID
	Name           string
	Description    pgtype.Text
	EventType      string
	VenueName      pgtype.Text
	VenueAddress   pgtype.Text
	StartsAt       pgtype.Timestamptz
	EndsAt         pgtype.Timestamptz
	Faq            pgtype.Text
	Terms          pgtype.Text
	Waiver         pgtype.Text
	OrganizationID uuid.UUID
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.EventType,
		arg.VenueName,
		arg.VenueAddress,
		arg.StartsAt,
		arg.EndsAt,
		arg.Faq,
		arg.Terms,
		arg.Waiver,
		arg.OrganizationID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.BannerObjectKey,
		&i.LogoObjectKey,
		&i.VenueName,
		&i.VenueAddress,
		&i.StartsAt,
		&i.EndsAt,
		&i.Faq,
		&i.Terms,
		&i.Waiver,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventStatus = `-- name: UpdateEventStatus :one
UPDATE events SET status = $2, published_at = $3, updated_at = now()
WHERE id = $1 AND organization_id = $4
RETURNING id, organization_id, name, slug, description, event_type, status, banner_object_key, logo_object_key, venue_name, venue_address, starts_at, ends_at, faq, terms, waiver, published_at, created_at, updated_at
`

type UpdateEventStatusParams struct {
	ID             uuid.UUID
	Status         string
	PublishedAt    pgtype.Timestamptz
	OrganizationID uuid.UUID
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEventStatus,
		arg.ID,
		arg.Status,
		arg.PublishedAt,
		arg.OrganizationID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.BannerObjectKey,
		&i.LogoObjectKey,
		&i.VenueName,
		&i.VenueAddress,
		&i.StartsAt,
		&i.EndsAt,
		&i.Faq,
		&i.Terms,
		&i.Waiver,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
