// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO event_categories (organization_id, event_id, name, price, capacity,
    registration_opens_at, registration_closes_at, bib_prefix, min_age, max_order_per_user)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, organization_id, event_id, name, price, capacity, registration_opens_at, registration_closes_at, bib_prefix, min_age, max_order_per_user, created_at, updated_at
`

type CreateCategoryParams struct {
	OrganizationID       uuid.UUID
	EventID              uuid.UUID
	Name                 string
	Price                int64
	Capacity             int32
	RegistrationOpensAt  pgtype.Timestamptz
	RegistrationClosesAt pgtype.Timestamptz
	BibPrefix            pgtype.Text
	MinAge               pgtype.Int4
	MaxOrderPerUser      int32
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (EventCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.OrganizationID,
		arg.EventID,
		arg.Name,
		arg.Price,
		arg.Capacity,
		arg.RegistrationOpensAt,
		arg.RegistrationClosesAt,
		arg.BibPrefix,
		arg.MinAge,
		arg.MaxOrderPerUser,
	)
	var i EventCategory
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.Capacity,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.BibPrefix,
		&i.MinAge,
		&i.MaxOrderPerUser,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM event_categories WHERE id = $1 AND event_id = $2
`

type DeleteCategoryParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.EventID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, organization_id, event_id, name, price, capacity, registration_opens_at, registration_closes_at, bib_prefix, min_age, max_order_per_user, created_at, updated_at FROM event_categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (EventCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i EventCategory
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.Capacity,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.BibPrefix,
		&i.MinAge,
		&i.MaxOrderPerUser,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByEvent = `-- name: ListCategoriesByEvent :many
SELECT id, organization_id, event_id, name, price, capacity, registration_opens_at, registration_closes_at, bib_prefix, min_age, max_order_per_user, created_at, updated_at FROM event_categories WHERE event_id = $1 ORDER BY created_at
`

func (q *Queries) ListCategoriesByEvent(ctx context.Context, eventID uuid.UUID) ([]EventCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventCategory
	for rows.Next() {
		var i EventCategory
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.Name,
			&i.Price,
			&i.Capacity,
			&i.RegistrationOpensAt,
			&i.RegistrationClosesAt,
			&i.BibPrefix,
			&i.MinAge,
			&i.MaxOrderPerUser,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByEventForPublic = `-- name: ListCategoriesByEventForPublic :many
SELECT id, organization_id, event_id, name, price, capacity, registration_opens_at, registration_closes_at, bib_prefix, min_age, max_order_per_user, created_at, updated_at FROM event_categories WHERE event_id = $1 ORDER BY price
`

func (q *Queries) ListCategoriesByEventForPublic(ctx context.Context, eventID uuid.UUID) ([]EventCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesByEventForPublic, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventCategory
	for rows.Next() {
		var i EventCategory
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.Name,
			&i.Price,
			&i.Capacity,
			&i.RegistrationOpensAt,
			&i.RegistrationClosesAt,
			&i.BibPrefix,
			&i.MinAge,
			&i.MaxOrderPerUser,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE event_categories SET
    name = $2, price = $3, capacity = $4,
    registration_opens_at = $5, registration_closes_at = $6,
    bib_prefix = $7, min_age = $8, max_order_per_user = $9, updated_at = now()
WHERE id = $1 AND event_id = $10
RETURNING id, organization_id, event_id, name, price, capacity, registration_opens_at, registration_closes_at, bib_prefix, min_age, max_order_per_user, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID                   uuid.UUID
	Name                 string
	Price                int64
	Capacity             int32
	RegistrationOpensAt  pgtype.Timestamptz
	RegistrationClosesAt pgtype.Timestamptz
	BibPrefix            pgtype.Text
	MinAge               pgtype.Int4
	MaxOrderPerUser      int32
	EventID              uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (EventCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Capacity,
		arg.RegistrationOpensAt,
		arg.RegistrationClosesAt,
		arg.BibPrefix,
		arg.MinAge,
		arg.MaxOrderPerUser,
		arg.EventID,
	)
	var i EventCategory
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.Capacity,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.BibPrefix,
		&i.MinAge,
		&i.MaxOrderPerUser,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
