// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forms.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createField = `-- name: CreateField :one
INSERT INTO form_fields (organization_id, form_schema_id, field_type, label, field_key,
    help_text, is_required, display_order, options, validation, conditional, category_scope)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, organization_id, form_schema_id, field_type, label, field_key, help_text, is_required, display_order, options, validation, conditional, category_scope, created_at, updated_at
`

type CreateFieldParams struct {
	OrganizationID uuid.UUID
	FormSchemaID   uuid.UUID
	FieldType      string
	Label          string
	FieldKey       string
	HelpText       pgtype.Text
	IsRequired     bool
	DisplayOrder   int32
	Options        []byte
	Validation     []byte
	Conditional    []byte
	CategoryScope  []byte
}

func (q *Queries) CreateField(ctx context.Context, arg CreateFieldParams) (FormField, error) {
	row := q.db.QueryRow(ctx, createField,
		arg.OrganizationID,
		arg.FormSchemaID,
		arg.FieldType,
		arg.Label,
		arg.FieldKey,
		arg.HelpText,
		arg.IsRequired,
		arg.DisplayOrder,
		arg.Options,
		arg.Validation,
		arg.Conditional,
		arg.CategoryScope,
	)
	var i FormField
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.FormSchemaID,
		&i.FieldType,
		&i.Label,
		&i.FieldKey,
		&i.HelpText,
		&i.IsRequired,
		&i.DisplayOrder,
		&i.Options,
		&i.Validation,
		&i.Conditional,
		&i.CategoryScope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFormSchema = `-- name: CreateFormSchema :one
INSERT INTO form_schemas (organization_id, event_id, name)
VALUES ($1, $2, $3)
RETURNING id, organization_id, event_id, name, created_at, updated_at
`

type CreateFormSchemaParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	Name           string
}

func (q *Queries) CreateFormSchema(ctx context.Context, arg CreateFormSchemaParams) (FormSchema, error) {
	row := q.db.QueryRow(ctx, createFormSchema, arg.OrganizationID, arg.EventID, arg.Name)
	var i FormSchema
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteField = `-- name: DeleteField :exec
DELETE FROM form_fields WHERE id = $1 AND form_schema_id = $2
`

type DeleteFieldParams struct {
	ID           uuid.UUID
	FormSchemaID uuid.UUID
}

func (q *Queries) DeleteField(ctx context.Context, arg DeleteFieldParams) error {
	_, err := q.db.Exec(ctx, deleteField, arg.ID, arg.FormSchemaID)
	return err
}

const getFieldByID = `-- name: GetFieldByID :one
SELECT id, organization_id, form_schema_id, field_type, label, field_key, help_text, is_required, display_order, options, validation, conditional, category_scope, created_at, updated_at FROM form_fields WHERE id = $1
`

func (q *Queries) GetFieldByID(ctx context.Context, id uuid.UUID) (FormField, error) {
	row := q.db.QueryRow(ctx, getFieldByID, id)
	var i FormField
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.FormSchemaID,
		&i.FieldType,
		&i.Label,
		&i.FieldKey,
		&i.HelpText,
		&i.IsRequired,
		&i.DisplayOrder,
		&i.Options,
		&i.Validation,
		&i.Conditional,
		&i.CategoryScope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFormSchemaByEvent = `-- name: GetFormSchemaByEvent :one
SELECT id, organization_id, event_id, name, created_at, updated_at FROM form_schemas WHERE event_id = $1
`

func (q *Queries) GetFormSchemaByEvent(ctx context.Context, eventID uuid.UUID) (FormSchema, error) {
	row := q.db.QueryRow(ctx, getFormSchemaByEvent, eventID)
	var i FormSchema
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFieldsBySchema = `-- name: ListFieldsBySchema :many
SELECT id, organization_id, form_schema_id, field_type, label, field_key, help_text, is_required, display_order, options, validation, conditional, category_scope, created_at, updated_at FROM form_fields WHERE form_schema_id = $1 ORDER BY display_order
`

func (q *Queries) ListFieldsBySchema(ctx context.Context, formSchemaID uuid.UUID) ([]FormField, error) {
	rows, err := q.db.Query(ctx, listFieldsBySchema, formSchemaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormField
	for rows.Next() {
		var i FormField
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.FormSchemaID,
			&i.FieldType,
			&i.Label,
			&i.FieldKey,
			&i.HelpText,
			&i.IsRequired,
			&i.DisplayOrder,
			&i.Options,
			&i.Validation,
			&i.Conditional,
			&i.CategoryScope,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxFieldOrder = `-- name: MaxFieldOrder :one
SELECT COALESCE(MAX(display_order), 0)::int FROM form_fields WHERE form_schema_id = $1
`

func (q *Queries) MaxFieldOrder(ctx context.Context, formSchemaID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxFieldOrder, formSchemaID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateField = `-- name: UpdateField :one
UPDATE form_fields SET
    field_type = $2, label = $3, field_key = $4, help_text = $5, is_required = $6,
    options = $7, validation = $8, conditional = $9, category_scope = $10, updated_at = now()
WHERE id = $1 AND form_schema_id = $11
RETURNING id, organization_id, form_schema_id, field_type, label, field_key, help_text, is_required, display_order, options, validation, conditional, category_scope, created_at, updated_at
`

type UpdateFieldParams struct {
	ID            uuid.UUID
	FieldType     string
	Label         string
	FieldKey      string
	HelpText      pgtype.Text
	IsRequired    bool
	Options       []byte
	Validation    []byte
	Conditional   []byte
	CategoryScope []byte
	FormSchemaID  uuid.UUID
}

func (q *Queries) UpdateField(ctx context.Context, arg UpdateFieldParams) (FormField, error) {
	row := q.db.QueryRow(ctx, updateField,
		arg.ID,
		arg.FieldType,
		arg.Label,
		arg.FieldKey,
		arg.HelpText,
		arg.IsRequired,
		arg.Options,
		arg.Validation,
		arg.Conditional,
		arg.CategoryScope,
		arg.FormSchemaID,
	)
	var i FormField
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.FormSchemaID,
		&i.FieldType,
		&i.Label,
		&i.FieldKey,
		&i.HelpText,
		&i.IsRequired,
		&i.DisplayOrder,
		&i.Options,
		&i.Validation,
		&i.Conditional,
		&i.CategoryScope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFieldOrder = `-- name: UpdateFieldOrder :exec
UPDATE form_fields SET display_order = $2, updated_at = now()
WHERE id = $1 AND form_schema_id = $3
`

type UpdateFieldOrderParams struct {
	ID           uuid.UUID
	DisplayOrder int32
	FormSchemaID uuid.UUID
}

func (q *Queries) UpdateFieldOrder(ctx context.Context, arg UpdateFieldOrderParams) error {
	_, err := q.db.Exec(ctx, updateFieldOrder, arg.ID, arg.DisplayOrder, arg.FormSchemaID)
	return err
}

const updateFormSchemaName = `-- name: UpdateFormSchemaName :one
UPDATE form_schemas SET name = $2, updated_at = now()
WHERE id = $1 AND organization_id = $3
RETURNING id, organization_id, event_id, name, created_at, updated_at
`

type UpdateFormSchemaNameParams struct {
	ID             uuid.UUID
	Name           string
	OrganizationID uuid.UUID
}

func (q *Queries) UpdateFormSchemaName(ctx context.Context, arg UpdateFormSchemaNameParams) (FormSchema, error) {
	row := q.db.QueryRow(ctx, updateFormSchemaName, arg.ID, arg.Name, arg.OrganizationID)
	var i FormSchema
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
