// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveReservationsByCategory = `-- name: CountActiveReservationsByCategory :one
SELECT count(*) FROM inventory_reservations
WHERE category_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) CountActiveReservationsByCategory(ctx context.Context, categoryID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveReservationsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO inventory_reservations (organization_id, event_id, category_id,
    order_id, participant_id, status, expires_at)
VALUES ($1, $2, $3, $4, $5, 'ACTIVE', $6)
RETURNING id, organization_id, event_id, category_id, order_id, participant_id, status, expires_at, created_at
`

type CreateReservationParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     uuid.UUID
	OrderID        uuid.UUID
	ParticipantID  uuid.UUID
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.OrderID,
		arg.ParticipantID,
		arg.ExpiresAt,
	)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.OrderID,
		&i.ParticipantID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const expireReservationsForOrder = `-- name: ExpireReservationsForOrder :exec
UPDATE inventory_reservations SET status = 'EXPIRED'
WHERE order_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) ExpireReservationsForOrder(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, expireReservationsForOrder, orderID)
	return err
}

const getReservationByOrder = `-- name: GetReservationByOrder :one
SELECT id, organization_id, event_id, category_id, order_id, participant_id, status, expires_at, created_at FROM inventory_reservations WHERE order_id = $1
`

func (q *Queries) GetReservationByOrder(ctx context.Context, orderID uuid.UUID) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByOrder, orderID)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.OrderID,
		&i.ParticipantID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockCategoryForUpdate = `-- name: LockCategoryForUpdate :one
SELECT id, organization_id, event_id, name, price, capacity, registration_opens_at, registration_closes_at, bib_prefix, min_age, max_order_per_user, created_at, updated_at FROM event_categories WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockCategoryForUpdate(ctx context.Context, id uuid.UUID) (EventCategory, error) {
	row := q.db.QueryRow(ctx, lockCategoryForUpdate, id)
	var i EventCategory
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.Capacity,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.BibPrefix,
		&i.MinAge,
		&i.MaxOrderPerUser,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReservationStatusByOrder = `-- name: UpdateReservationStatusByOrder :exec
UPDATE inventory_reservations SET status = $2
WHERE order_id = $1 AND status = 'ACTIVE'
`

type UpdateReservationStatusByOrderParams struct {
	OrderID uuid.UUID
	Status  string
}

func (q *Queries) UpdateReservationStatusByOrder(ctx context.Context, arg UpdateReservationStatusByOrderParams) error {
	_, err := q.db.Exec(ctx, updateReservationStatusByOrder, arg.OrderID, arg.Status)
	return err
}
