// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMemberRole = `-- name: AddMemberRole :exec
INSERT INTO member_roles (organization_member_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddMemberRoleParams struct {
	OrganizationMemberID uuid.UUID
	RoleID               uuid.UUID
}

func (q *Queries) AddMemberRole(ctx context.Context, arg AddMemberRoleParams) error {
	_, err := q.db.Exec(ctx, addMemberRole, arg.OrganizationMemberID, arg.RoleID)
	return err
}

const clearMemberRoles = `-- name: ClearMemberRoles :exec
DELETE FROM member_roles WHERE organization_member_id = $1
`

func (q *Queries) ClearMemberRoles(ctx context.Context, organizationMemberID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearMemberRoles, organizationMemberID)
	return err
}

const countOwnersInOrg = `-- name: CountOwnersInOrg :one
SELECT count(DISTINCT mr.organization_member_id)
FROM member_roles mr
JOIN roles r ON r.id = mr.role_id
WHERE r.organization_id = $1 AND r.slug = 'owner'
`

func (q *Queries) CountOwnersInOrg(ctx context.Context, organizationID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnersInOrg, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO organization_members (organization_id, user_id)
VALUES ($1, $2)
RETURNING id, organization_id, user_id, created_at
`

type CreateMemberParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, createMember, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM organization_members WHERE id = $1 AND organization_id = $2
`

type DeleteMemberParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.ID, arg.OrganizationID)
	return err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, organization_id, user_id, created_at FROM organization_members WHERE id = $1
`

func (q *Queries) GetMemberByID(ctx context.Context, id uuid.UUID) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberByOrgAndUser = `-- name: GetMemberByOrgAndUser :one
SELECT id, organization_id, user_id, created_at FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type GetMemberByOrgAndUserParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) GetMemberByOrgAndUser(ctx context.Context, arg GetMemberByOrgAndUserParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getMemberByOrgAndUser, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listMembersByOrg = `-- name: ListMembersByOrg :many
SELECT m.id, m.user_id, m.created_at, u.email, u.full_name
FROM organization_members m
JOIN users u ON u.id = m.user_id
WHERE m.organization_id = $1
ORDER BY m.created_at
`

type ListMembersByOrgRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	Email     string
	FullName  string
}

func (q *Queries) ListMembersByOrg(ctx context.Context, organizationID uuid.UUID) ([]ListMembersByOrgRow, error) {
	rows, err := q.db.Query(ctx, listMembersByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersByOrgRow
	for rows.Next() {
		var i ListMembersByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsForMember = `-- name: ListPermissionsForMember :many
SELECT DISTINCT p.key
FROM member_roles mr
JOIN role_permissions rp ON rp.role_id = mr.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE mr.organization_member_id = $1
`

func (q *Queries) ListPermissionsForMember(ctx context.Context, organizationMemberID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionsForMember, organizationMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForMember = `-- name: ListRolesForMember :many
SELECT r.id, r.organization_id, r.name, r.slug, r.is_system, r.created_at FROM roles r
JOIN member_roles mr ON mr.role_id = r.id
WHERE mr.organization_member_id = $1
ORDER BY r.name
`

func (q *Queries) ListRolesForMember(ctx context.Context, organizationMemberID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesForMember, organizationMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberHasRoleSlug = `-- name: MemberHasRoleSlug :one
SELECT EXISTS (
    SELECT 1 FROM member_roles mr
    JOIN roles r ON r.id = mr.role_id
    WHERE mr.organization_member_id = $1 AND r.slug = $2
)
`

type MemberHasRoleSlugParams struct {
	OrganizationMemberID uuid.UUID
	Slug                 string
}

func (q *Queries) MemberHasRoleSlug(ctx context.Context, arg MemberHasRoleSlugParams) (bool, error) {
	row := q.db.QueryRow(ctx, memberHasRoleSlug, arg.OrganizationMemberID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
