// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AbuseLog struct {
	ID           uuid.UUID
	SubjectType  pgtype.Text
	SubjectValue pgtype.Text
	Action       string
	Category     pgtype.Text
	Fingerprint  pgtype.Text
	Ip           pgtype.Text
	UserID       *uuid.UUID
	Detail       []byte
	CreatedAt    pgtype.Timestamptz
}

type AccessGrant struct {
	ID            uuid.UUID
	PoolID        *uuid.UUID
	ParticipantID uuid.UUID
	EventID       uuid.UUID
	CategoryID    uuid.UUID
	CodeID        *uuid.UUID
	Status        string
	GrantedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	ConsumedAt    pgtype.Timestamptz
	OrderID       *uuid.UUID
	CreatedAt     pgtype.Timestamptz
}

type AccessPool struct {
	ID                      uuid.UUID
	OrganizationID          uuid.UUID
	EventID                 uuid.UUID
	CategoryID              uuid.UUID
	PoolType                string
	Name                    string
	TotalSlots              int32
	ReservedSlots           int32
	UsedSlots               int32
	ReleasedSlots           int32
	OwnerAccountID          *uuid.UUID
	IsVisibleToParticipants bool
	EligibilityRule         []byte
	ValidFrom               pgtype.Timestamptz
	ValidUntil              pgtype.Timestamptz
	CreatedBy               uuid.UUID
	CreatedAt               pgtype.Timestamptz
}

type AccessPoolMember struct {
	ID              uuid.UUID
	PoolID          uuid.UUID
	UserID          *uuid.UUID
	Email           string
	MemberStatus    string
	EligibilityMeta []byte
	AccessGrantID   *uuid.UUID
	InvitedAt       pgtype.Timestamptz
	RegisteredAt    pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

type AuditLog struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
	ActorUserID    *uuid.UUID
	Action         string
	TargetType     pgtype.Text
	TargetID       pgtype.Text
	Metadata       []byte
	CreatedAt      pgtype.Timestamptz
}

type BallotDraw struct {
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
	EventID             uuid.UUID
	CategoryID          uuid.UUID
	Status              string
	Quota               int32
	WaitlistSize        pgtype.Int4
	PaymentWindowHours  int32
	ApplicationOpensAt  pgtype.Timestamptz
	ApplicationClosesAt pgtype.Timestamptz
	DrawAt              pgtype.Timestamptz
	AnnouncedAt         pgtype.Timestamptz
	Seed                pgtype.Text
	DrawNonce           *uuid.UUID
	WinnerPoolID        *uuid.UUID
	WaitlistID          *uuid.UUID
	CreatedBy           uuid.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type BallotDrawResult struct {
	ID            uuid.UUID
	DrawID        uuid.UUID
	BallotEntryID uuid.UUID
	Outcome       string
	Rank          int32
	ResultHash    string
}

type BallotEntry struct {
	ID              uuid.UUID
	DrawID          uuid.UUID
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	CategoryID      uuid.UUID
	ParticipantID   uuid.UUID
	Status          string
	AppliedAt       pgtype.Timestamptz
	PaymentDeadline pgtype.Timestamptz
	ConvertedAt     pgtype.Timestamptz
	PromotedRound   int32
	AccessGrantID   *uuid.UUID
}

type BlockedSubject struct {
	ID           uuid.UUID
	SubjectType  string
	SubjectValue string
	Reason       pgtype.Text
	BlockedBy    *uuid.UUID
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

type CategoryRegistrationSetting struct {
	CategoryID       uuid.UUID
	RegistrationMode pgtype.Text
	OverrideEnabled  bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type CorporateAccount struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	Name            string
	BillingEmail    string
	InvoiceRequired bool
	Status          string
	ApprovedAt      pgtype.Timestamptz
	ApprovedBy      *uuid.UUID
	CreatedBy       uuid.UUID
	CreatedAt       pgtype.Timestamptz
}

type Event struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	Name            string
	Slug            string
	Description     pgtype.Text
	EventType       string
	Status          string
	BannerObjectKey pgtype.Text
	LogoObjectKey   pgtype.Text
	VenueName       pgtype.Text
	VenueAddress    pgtype.Text
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	Faq             pgtype.Text
	Terms           pgtype.Text
	Waiver          pgtype.Text
	PublishedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type EventCategory struct {
	ID                   uuid.UUID
	OrganizationID       uuid.UUID
	EventID              uuid.UUID
	Name                 string
	Price                int64
	Capacity             int32
	RegistrationOpensAt  pgtype.Timestamptz
	RegistrationClosesAt pgtype.Timestamptz
	BibPrefix            pgtype.Text
	MinAge               pgtype.Int4
	MaxOrderPerUser      int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type EventRegistrationSetting struct {
	EventID         uuid.UUID
	DefaultMode     string
	QueueEnabled    bool
	BallotEnabled   bool
	PriorityEnabled bool
	WaitlistEnabled bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type FormField struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	FormSchemaID   uuid.UUID
	FieldType      string
	Label          string
	FieldKey       string
	HelpText       pgtype.Text
	IsRequired     bool
	DisplayOrder   int32
	Options        []byte
	Validation     []byte
	Conditional    []byte
	CategoryScope  []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type FormSchema struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	Name           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type InventoryReservation struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     uuid.UUID
	OrderID        uuid.UUID
	ParticipantID  uuid.UUID
	Status         string
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type IpReputation struct {
	SubjectType  string
	SubjectValue string
	Score        int32
	UpdatedAt    pgtype.Timestamptz
}

type IpRule struct {
	ID        uuid.UUID
	Cidr      string
	Rule      string
	Note      pgtype.Text
	CreatedBy *uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type LifecyclePhase struct {
	ID               uuid.UUID
	LifecycleID      uuid.UUID
	PhaseIndex       int32
	RegistrationMode string
	Label            string
	OpensAt          pgtype.Timestamptz
	ClosesAt         pgtype.Timestamptz
	CapacityOverride pgtype.Int4
	AutoAdvance      bool
	Status           string
	ActivatedAt      pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
}

type MemberRole struct {
	OrganizationMemberID uuid.UUID
	RoleID               uuid.UUID
}

type Order struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     uuid.UUID
	ParticipantID  uuid.UUID
	OrderNumber    string
	Status         string
	Subtotal       int64
	Fee            int64
	Discount       int64
	Total          int64
	ExpiredAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OrganizationMember struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	CreatedAt      pgtype.Timestamptz
}

type Payment struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	EventID           uuid.UUID
	OrderID           uuid.UUID
	ParticipantID     uuid.UUID
	Gateway           string
	Method            string
	Channel           pgtype.Text
	Status            string
	Amount            int64
	Currency          string
	GatewayReference  pgtype.Text
	MerchantReference string
	PayUrl            pgtype.Text
	QrString          pgtype.Text
	VaNumber          pgtype.Text
	Instructions      []byte
	ExpiresAt         pgtype.Timestamptz
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PaymentWebhook struct {
	ID                 uuid.UUID
	Gateway            string
	EventType          pgtype.Text
	MerchantReference  pgtype.Text
	GatewayReference   pgtype.Text
	Signature          pgtype.Text
	SignatureValid     bool
	Payload            []byte
	DedupeKey          pgtype.Text
	ProcessingStatus   string
	ProcessedPaymentID *uuid.UUID
	ErrorDetail        pgtype.Text
	ReceivedAt         pgtype.Timestamptz
	ProcessedAt        pgtype.Timestamptz
}

type Permission struct {
	ID          uuid.UUID
	Key         string
	Description string
}

type PlatformSetting struct {
	Key       string
	Value     string
	UpdatedBy *uuid.UUID
	UpdatedAt pgtype.Timestamptz
}

type QueueAdmission struct {
	ID                uuid.UUID
	TokenID           uuid.UUID
	EventID           uuid.UUID
	ParticipantID     uuid.UUID
	CheckoutExpiresAt pgtype.Timestamptz
	Status            string
	CreatedAt         pgtype.Timestamptz
}

type QueueControl struct {
	EventID           uuid.UUID
	State             string
	ReleaseRate       int32
	RandomizationSeed pgtype.Text
	SaleStartAt       pgtype.Timestamptz
	PresalePoolOpenAt pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type QueueToken struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	ParticipantID  uuid.UUID
	Status         string
	Pool           string
	Score          int64
	JoinedAt       pgtype.Timestamptz
	AllowedAt      pgtype.Timestamptz
	ExpiredAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RegistrationLifecycle struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	EventID           uuid.UUID
	CategoryID        uuid.UUID
	Status            string
	CurrentPhaseIndex int32
	CreatedBy         uuid.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Role struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
	Name           string
	Slug           string
	IsSystem       bool
	CreatedAt      pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type SchemaHealth struct {
	ID        int16
	CheckedAt pgtype.Timestamptz
}

type Ticket struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     uuid.UUID
	OrderID        uuid.UUID
	ParticipantID  uuid.UUID
	TicketNumber   string
	Status         string
	HolderName     string
	HolderEmail    string
	EventTitle     string
	CategoryName   string
	QrVersion      int32
	IssuedAt       pgtype.Timestamptz
	UsedAt         pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    pgtype.Text
	FullName        string
	Phone           pgtype.Text
	IsPlatformAdmin bool
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	MembershipID    pgtype.Text
}

type Waitlist struct {
	ID                   uuid.UUID
	OrganizationID       uuid.UUID
	EventID              uuid.UUID
	CategoryID           uuid.UUID
	PoolID               *uuid.UUID
	Mode                 string
	Status               string
	MaxPromotionBatch    int32
	PromotionWindowHours int32
	AutoPromote          bool
	Seed                 pgtype.Text
	CreatedAt            pgtype.Timestamptz
}

type WaitlistEntry struct {
	ID                   uuid.UUID
	WaitlistID           uuid.UUID
	ParticipantID        uuid.UUID
	EventID              uuid.UUID
	CategoryID           uuid.UUID
	Source               string
	SourceRefID          *uuid.UUID
	Status               string
	Rank                 int64
	NotifiedAt           pgtype.Timestamptz
	PromotedAt           pgtype.Timestamptz
	AccessGrantID        *uuid.UUID
	PromotionWindowHours pgtype.Int4
	CreatedAt            pgtype.Timestamptz
}
