// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
	ActorUserID    *uuid.UUID
	Action         string
	TargetType     pgtype.Text
	TargetID       pgtype.Text
	Metadata       []byte
	CreatedAt      pgtype.Timestamptz
}

type CategoryRegistrationSetting struct {
	CategoryID       uuid.UUID
	RegistrationMode pgtype.Text
	OverrideEnabled  bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Event struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	Name            string
	Slug            string
	Description     pgtype.Text
	EventType       string
	Status          string
	BannerObjectKey pgtype.Text
	LogoObjectKey   pgtype.Text
	VenueName       pgtype.Text
	VenueAddress    pgtype.Text
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	Faq             pgtype.Text
	Terms           pgtype.Text
	Waiver          pgtype.Text
	PublishedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type EventCategory struct {
	ID                   uuid.UUID
	OrganizationID       uuid.UUID
	EventID              uuid.UUID
	Name                 string
	Price                int64
	Capacity             int32
	RegistrationOpensAt  pgtype.Timestamptz
	RegistrationClosesAt pgtype.Timestamptz
	BibPrefix            pgtype.Text
	MinAge               pgtype.Int4
	MaxOrderPerUser      int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type EventRegistrationSetting struct {
	EventID         uuid.UUID
	DefaultMode     string
	QueueEnabled    bool
	BallotEnabled   bool
	PriorityEnabled bool
	WaitlistEnabled bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type FormField struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	FormSchemaID   uuid.UUID
	FieldType      string
	Label          string
	FieldKey       string
	HelpText       pgtype.Text
	IsRequired     bool
	DisplayOrder   int32
	Options        []byte
	Validation     []byte
	Conditional    []byte
	CategoryScope  []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type FormSchema struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	Name           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type InventoryReservation struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     uuid.UUID
	OrderID        uuid.UUID
	ParticipantID  uuid.UUID
	Status         string
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type MemberRole struct {
	OrganizationMemberID uuid.UUID
	RoleID               uuid.UUID
}

type Order struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     uuid.UUID
	ParticipantID  uuid.UUID
	OrderNumber    string
	Status         string
	Subtotal       int64
	Fee            int64
	Discount       int64
	Total          int64
	ExpiredAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OrganizationMember struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	CreatedAt      pgtype.Timestamptz
}

type Payment struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	EventID           uuid.UUID
	OrderID           uuid.UUID
	ParticipantID     uuid.UUID
	Gateway           string
	Method            string
	Channel           pgtype.Text
	Status            string
	Amount            int64
	Currency          string
	GatewayReference  pgtype.Text
	MerchantReference string
	PayUrl            pgtype.Text
	QrString          pgtype.Text
	VaNumber          pgtype.Text
	Instructions      []byte
	ExpiresAt         pgtype.Timestamptz
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PaymentWebhook struct {
	ID                 uuid.UUID
	Gateway            string
	EventType          pgtype.Text
	MerchantReference  pgtype.Text
	GatewayReference   pgtype.Text
	Signature          pgtype.Text
	SignatureValid     bool
	Payload            []byte
	DedupeKey          pgtype.Text
	ProcessingStatus   string
	ProcessedPaymentID *uuid.UUID
	ErrorDetail        pgtype.Text
	ReceivedAt         pgtype.Timestamptz
	ProcessedAt        pgtype.Timestamptz
}

type Permission struct {
	ID          uuid.UUID
	Key         string
	Description string
}

type QueueAdmission struct {
	ID                uuid.UUID
	TokenID           uuid.UUID
	EventID           uuid.UUID
	ParticipantID     uuid.UUID
	CheckoutExpiresAt pgtype.Timestamptz
	Status            string
	CreatedAt         pgtype.Timestamptz
}

type QueueControl struct {
	EventID           uuid.UUID
	State             string
	ReleaseRate       int32
	RandomizationSeed pgtype.Text
	SaleStartAt       pgtype.Timestamptz
	PresalePoolOpenAt pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type QueueToken struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	ParticipantID  uuid.UUID
	Status         string
	Pool           string
	Score          int64
	JoinedAt       pgtype.Timestamptz
	AllowedAt      pgtype.Timestamptz
	ExpiredAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Role struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
	Name           string
	Slug           string
	IsSystem       bool
	CreatedAt      pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type SchemaHealth struct {
	ID        int16
	CheckedAt pgtype.Timestamptz
}

type Ticket struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     uuid.UUID
	OrderID        uuid.UUID
	ParticipantID  uuid.UUID
	TicketNumber   string
	Status         string
	HolderName     string
	HolderEmail    string
	EventTitle     string
	CategoryName   string
	QrVersion      int32
	IssuedAt       pgtype.Timestamptz
	UsedAt         pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    pgtype.Text
	FullName        string
	Phone           pgtype.Text
	IsPlatformAdmin bool
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
