// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AbuseLog struct {
	ID           uuid.UUID
	SubjectType  pgtype.Text
	SubjectValue pgtype.Text
	Action       string
	Category     pgtype.Text
	Fingerprint  pgtype.Text
	Ip           pgtype.Text
	UserID       *uuid.UUID
	Detail       []byte
	CreatedAt    pgtype.Timestamptz
}

type AccessCode struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	CategoryID      *uuid.UUID
	CodeType        string
	CodeValueHash   string
	IsSingleUse     bool
	MaxUses         int32
	UseCount        int32
	ValidFrom       pgtype.Timestamptz
	ValidUntil      pgtype.Timestamptz
	PoolID          *uuid.UUID
	EligibilityRule []byte
	CreatedBy       uuid.UUID
	CreatedAt       pgtype.Timestamptz
	Metadata        []byte
}

type AccessGrant struct {
	ID            uuid.UUID
	PoolID        *uuid.UUID
	ParticipantID uuid.UUID
	EventID       uuid.UUID
	CategoryID    uuid.UUID
	CodeID        *uuid.UUID
	Status        string
	GrantedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	ConsumedAt    pgtype.Timestamptz
	OrderID       *uuid.UUID
	CreatedAt     pgtype.Timestamptz
}

type AccessPool struct {
	ID                      uuid.UUID
	OrganizationID          uuid.UUID
	EventID                 uuid.UUID
	CategoryID              uuid.UUID
	PoolType                string
	Name                    string
	TotalSlots              int32
	ReservedSlots           int32
	UsedSlots               int32
	ReleasedSlots           int32
	OwnerAccountID          *uuid.UUID
	IsVisibleToParticipants bool
	EligibilityRule         []byte
	ValidFrom               pgtype.Timestamptz
	ValidUntil              pgtype.Timestamptz
	CreatedBy               uuid.UUID
	CreatedAt               pgtype.Timestamptz
}

type AccessPoolMember struct {
	ID              uuid.UUID
	PoolID          uuid.UUID
	UserID          *uuid.UUID
	Email           string
	MemberStatus    string
	EligibilityMeta []byte
	AccessGrantID   *uuid.UUID
	InvitedAt       pgtype.Timestamptz
	RegisteredAt    pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

type ApiKey struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	Name            string
	KeyPrefix       string
	KeyHash         string
	Scopes          []byte
	RateLimitPerMin int32
	LastUsedAt      pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type AuditLog struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
	ActorUserID    *uuid.UUID
	Action         string
	TargetType     pgtype.Text
	TargetID       pgtype.Text
	Metadata       []byte
	CreatedAt      pgtype.Timestamptz
}

type BallotDraw struct {
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
	EventID             uuid.UUID
	CategoryID          uuid.UUID
	Status              string
	Quota               int32
	WaitlistSize        pgtype.Int4
	PaymentWindowHours  int32
	ApplicationOpensAt  pgtype.Timestamptz
	ApplicationClosesAt pgtype.Timestamptz
	DrawAt              pgtype.Timestamptz
	AnnouncedAt         pgtype.Timestamptz
	Seed                pgtype.Text
	DrawNonce           *uuid.UUID
	WinnerPoolID        *uuid.UUID
	WaitlistID          *uuid.UUID
	CreatedBy           uuid.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type BallotDrawResult struct {
	ID            uuid.UUID
	DrawID        uuid.UUID
	BallotEntryID uuid.UUID
	Outcome       string
	Rank          int32
	ResultHash    string
}

type BallotEntry struct {
	ID              uuid.UUID
	DrawID          uuid.UUID
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	CategoryID      uuid.UUID
	ParticipantID   uuid.UUID
	Status          string
	AppliedAt       pgtype.Timestamptz
	PaymentDeadline pgtype.Timestamptz
	ConvertedAt     pgtype.Timestamptz
	PromotedRound   int32
	AccessGrantID   *uuid.UUID
}

type BibTransponderMapping struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	BibNumber       string
	TransponderCode string
	IsActive        bool
	Status          string
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type BlockedSubject struct {
	ID           uuid.UUID
	SubjectType  string
	SubjectValue string
	Reason       pgtype.Text
	BlockedBy    *uuid.UUID
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

type CategoryRegistrationSetting struct {
	CategoryID       uuid.UUID
	RegistrationMode pgtype.Text
	OverrideEnabled  bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type CertificateTemplate struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	Name           string
	Title          string
	Subtitle       string
	BodyTemplate   string
	BackgroundUrl  pgtype.Text
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type CompetitionConfig struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	CategoryID      *uuid.UUID
	SportID         string
	DisciplineID    string
	HasTiming       bool
	HasScoring      bool
	HasMatches      bool
	HasHeatsLanes   bool
	HasStages       bool
	TeamBased       bool
	MinTeamSize     int32
	MaxTeamSize     int32
	RankingStrategy string
	TimePrecision   string
	RulesConfig     []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type CompetitionMatch struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	EventID            uuid.UUID
	StageID            uuid.UUID
	RoundNumber        int32
	MatchNumber        int32
	HomeTeamID         *uuid.UUID
	AwayTeamID         *uuid.UUID
	HomeEntryID        *uuid.UUID
	AwayEntryID        *uuid.UUID
	ScheduledStartTime pgtype.Timestamptz
	VenueCourtName     pgtype.Text
	HomeScore          int32
	AwayScore          int32
	MatchStatus        string
	WinnerID           *uuid.UUID
	ScoreDetails       []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type CompetitionObservation struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	StageID         *uuid.UUID
	MatchID         *uuid.UUID
	EntryID         *uuid.UUID
	ObservationType string
	Source          string
	NumericValue    pgtype.Numeric
	TextValue       pgtype.Text
	ObservedAtMs    int64
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
}

type CompetitionResult struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	StageID         *uuid.UUID
	CategoryID      *uuid.UUID
	EntryID         uuid.UUID
	RankOverall     pgtype.Int4
	RankCategory    pgtype.Int4
	Status          string
	PrimaryTimeMs   pgtype.Int8
	SecondaryTimeMs pgtype.Int8
	PointsScored    pgtype.Numeric
	Metrics         []byte
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type CompetitionStage struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     *uuid.UUID
	Name           string
	StageType      string
	SequenceOrder  int32
	Status         string
	StageConfig    []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type CorporateAccount struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	Name            string
	BillingEmail    string
	InvoiceRequired bool
	Status          string
	ApprovedAt      pgtype.Timestamptz
	ApprovedBy      *uuid.UUID
	CreatedBy       uuid.UUID
	CreatedAt       pgtype.Timestamptz
}

type CustomDomain struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	Domain            string
	VerificationToken string
	Status            string
	VerifiedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Event struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	Name            string
	Slug            string
	Description     pgtype.Text
	EventType       string
	Status          string
	BannerObjectKey pgtype.Text
	LogoObjectKey   pgtype.Text
	VenueName       pgtype.Text
	VenueAddress    pgtype.Text
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	Faq             pgtype.Text
	Terms           pgtype.Text
	Waiver          pgtype.Text
	PublishedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	SportID         pgtype.Text
	DisciplineID    pgtype.Text
}

type EventCategory struct {
	ID                   uuid.UUID
	OrganizationID       uuid.UUID
	EventID              uuid.UUID
	Name                 string
	Price                int64
	Capacity             int32
	RegistrationOpensAt  pgtype.Timestamptz
	RegistrationClosesAt pgtype.Timestamptz
	BibPrefix            pgtype.Text
	MinAge               pgtype.Int4
	MaxOrderPerUser      int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DistanceKm           pgtype.Numeric
	CutoffTime           pgtype.Text
	PricingTiers         []byte
}

type EventPaymentChannel struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	ChannelCode string
	IsEnabled   bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type EventRegistrationSetting struct {
	EventID         uuid.UUID
	DefaultMode     string
	QueueEnabled    bool
	BallotEnabled   bool
	PriorityEnabled bool
	WaitlistEnabled bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ExportJob struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
	RequestedBy    uuid.UUID
	ReportType     string
	Format         string
	Params         []byte
	Status         string
	RowCount       pgtype.Int4
	FileKey        pgtype.Text
	FileUrl        pgtype.Text
	Error          pgtype.Text
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type FormField struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	FormSchemaID   uuid.UUID
	FieldType      string
	Label          string
	FieldKey       string
	HelpText       pgtype.Text
	IsRequired     bool
	DisplayOrder   int32
	Options        []byte
	Validation     []byte
	Conditional    []byte
	CategoryScope  []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type FormSchema struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	Name           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type IdempotencyKey struct {
	Key            string
	Scope          string
	RequestHash    string
	ResponseStatus int32
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
}

type Incident struct {
	ID         uuid.UUID
	Title      string
	Impact     string
	Status     string
	StartedAt  pgtype.Timestamptz
	ResolvedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type IncidentUpdate struct {
	ID         uuid.UUID
	IncidentID uuid.UUID
	Status     string
	Body       string
	CreatedAt  pgtype.Timestamptz
}

type InventoryReservation struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     uuid.UUID
	OrderID        uuid.UUID
	ParticipantID  uuid.UUID
	Status         string
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type IpReputation struct {
	SubjectType  string
	SubjectValue string
	Score        int32
	UpdatedAt    pgtype.Timestamptz
}

type IpRule struct {
	ID        uuid.UUID
	Cidr      string
	Rule      string
	Note      pgtype.Text
	CreatedBy *uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type LifecyclePhase struct {
	ID               uuid.UUID
	LifecycleID      uuid.UUID
	PhaseIndex       int32
	RegistrationMode string
	Label            string
	OpensAt          pgtype.Timestamptz
	ClosesAt         pgtype.Timestamptz
	CapacityOverride pgtype.Int4
	AutoAdvance      bool
	Status           string
	ActivatedAt      pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
}

type MemberRole struct {
	OrganizationMemberID uuid.UUID
	RoleID               uuid.UUID
}

type Notification struct {
	ID            uuid.UUID
	ParticipantID uuid.UUID
	Type          string
	Channel       string
	Status        string
	Payload       []byte
	Attempts      int32
	LastAttemptAt pgtype.Timestamptz
	SentAt        pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	NextRetryAt   pgtype.Timestamptz
	LastError     pgtype.Text
}

type NotificationTemplate struct {
	ID        uuid.UUID
	OrgID     *uuid.UUID
	Type      string
	Channel   string
	Subject   string
	BodyHtml  string
	BodyText  string
	IsDefault bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Order struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	EventID          uuid.UUID
	CategoryID       uuid.UUID
	ParticipantID    *uuid.UUID
	OrderNumber      string
	Status           string
	Subtotal         int64
	Fee              int64
	Discount         int64
	Total            int64
	ExpiredAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	GuestEmail       pgtype.Text
	GuestName        pgtype.Text
	GuestPhone       pgtype.Text
	TermsAcceptedAt  pgtype.Timestamptz
	TermsVersion     pgtype.Text
	WaiverAcceptedAt pgtype.Timestamptz
	WaiverVersion    pgtype.Text
	FormAnswers      []byte
	RefundedAmount   int64
	RefundReason     pgtype.Text
	RefundedAt       pgtype.Timestamptz
}

type OrgBranding struct {
	OrganizationID    uuid.UUID
	LogoObjectKey     string
	ThemeColor        string
	EmailFromName     string
	EmailFromAddress  string
	TermsText         string
	FooterText        string
	WhitelabelEnabled bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type OrgPayoutAccount struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	BankName       string
	BankCode       string
	AccountNumber  string
	AccountName    string
	IsVerified     bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type OrgSubscription struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	PackageID      uuid.UUID
	Status         string
	StartedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OrganizationMember struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	CreatedAt      pgtype.Timestamptz
}

type ParticipantEntry struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     *uuid.UUID
	TicketID       *uuid.UUID
	TeamID         *uuid.UUID
	EntryType      string
	DisplayName    string
	IdentifierCode pgtype.Text
	SeedNumber     pgtype.Int4
	LaneNumber     pgtype.Int4
	HeatNumber     pgtype.Int4
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Payment struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	EventID           uuid.UUID
	OrderID           uuid.UUID
	ParticipantID     uuid.UUID
	Gateway           string
	Method            string
	Channel           pgtype.Text
	Status            string
	Amount            int64
	Currency          string
	GatewayReference  pgtype.Text
	MerchantReference string
	PayUrl            pgtype.Text
	QrString          pgtype.Text
	VaNumber          pgtype.Text
	Instructions      []byte
	ExpiresAt         pgtype.Timestamptz
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PaymentWebhook struct {
	ID                 uuid.UUID
	Gateway            string
	EventType          pgtype.Text
	MerchantReference  pgtype.Text
	GatewayReference   pgtype.Text
	Signature          pgtype.Text
	SignatureValid     bool
	Payload            []byte
	DedupeKey          pgtype.Text
	ProcessingStatus   string
	ProcessedPaymentID *uuid.UUID
	ErrorDetail        pgtype.Text
	ReceivedAt         pgtype.Timestamptz
	ProcessedAt        pgtype.Timestamptz
}

type PayoutRequest struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	EventID         *uuid.UUID
	PayoutAccountID *uuid.UUID
	Amount          int64
	Currency        string
	Status          string
	Notes           pgtype.Text
	RejectionReason pgtype.Text
	RequestedBy     uuid.UUID
	ProcessedBy     *uuid.UUID
	ProcessedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Permission struct {
	ID          uuid.UUID
	Key         string
	Description string
}

type PlatformFeeLedger struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	OrderID        uuid.UUID
	OrderTotal     int64
	FeeBps         int32
	FeeAmount      int64
	CreatedAt      pgtype.Timestamptz
}

type PlatformInvoice struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	InvoiceNumber      string
	PeriodStart        pgtype.Date
	PeriodEnd          pgtype.Date
	SubscriptionAmount int64
	FeeAmount          int64
	TotalAmount        int64
	Status             string
	IssuedAt           pgtype.Timestamptz
	PaidAt             pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type PlatformSetting struct {
	Key       string
	Value     string
	UpdatedBy *uuid.UUID
	UpdatedAt pgtype.Timestamptz
}

type QueueAdmission struct {
	ID                uuid.UUID
	TokenID           uuid.UUID
	EventID           uuid.UUID
	ParticipantID     uuid.UUID
	CheckoutExpiresAt pgtype.Timestamptz
	Status            string
	CreatedAt         pgtype.Timestamptz
}

type QueueControl struct {
	EventID           uuid.UUID
	State             string
	ReleaseRate       int32
	RandomizationSeed pgtype.Text
	SaleStartAt       pgtype.Timestamptz
	PresalePoolOpenAt pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type QueueToken struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	ParticipantID  uuid.UUID
	Status         string
	Pool           string
	Score          int64
	JoinedAt       pgtype.Timestamptz
	AllowedAt      pgtype.Timestamptz
	ExpiredAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RaceResult struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	CategoryID      *uuid.UUID
	TicketID        *uuid.UUID
	BibNumber       string
	ParticipantName string
	Gender          pgtype.Text
	Age             pgtype.Int4
	AgeGroup        pgtype.Text
	Status          string
	ChipTimeMs      pgtype.Int8
	GunTimeMs       pgtype.Int8
	RankOverall     pgtype.Int4
	RankGender      pgtype.Int4
	RankCategory    pgtype.Int4
	RankAgeGroup    pgtype.Int4
	Source          string
	FinishedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	WaveID          *uuid.UUID
}

type RaceSplitTime struct {
	ID            uuid.UUID
	RaceResultID  uuid.UUID
	CheckpointID  uuid.UUID
	PassingID     pgtype.Int8
	SplitTimeMs   int64
	SplitPaceMsKm pgtype.Int8
	PassingTime   pgtype.Timestamptz
	OrderIndex    int32
	CreatedAt     pgtype.Timestamptz
}

type RaceWafe struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     *uuid.UUID
	Code           string
	Name           string
	StartAt        pgtype.Timestamptz
	OrderIndex     int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RacepackCounter struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	Name           string
	Location       pgtype.Text
	Active         bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RacepackPickupRecord struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	TicketID        uuid.UUID
	ParticipantID   uuid.UUID
	BibNumber       string
	CounterID       uuid.UUID
	StaffID         uuid.UUID
	PickupMethod    string
	PickupTimestamp pgtype.Timestamptz
	Notes           pgtype.Text
	Status          string
	SlotID          *uuid.UUID
}

type RacepackPickupSlot struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	Name           string
	PickupDate     pgtype.Date
	StartTime      pgtype.Timestamptz
	EndTime        pgtype.Timestamptz
	Capacity       int32
	ReservedCount  int32
	Active         bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RacepackProblemCase struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	TicketID       *uuid.UUID
	ParticipantID  *uuid.UUID
	Status         string
	Reason         string
	Resolution     pgtype.Text
	CreatedBy      uuid.UUID
	ResolvedBy     *uuid.UUID
	ResolvedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RacepackProxyAuthorization struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	EventID               uuid.UUID
	TicketID              uuid.UUID
	PickupRecordID        *uuid.UUID
	ProxyName             string
	ProxyPhone            pgtype.Text
	ProxyIdentity         string
	AuthorizationDocument pgtype.Text
	CreatedBy             uuid.UUID
	CreatedAt             pgtype.Timestamptz
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RegistrationLifecycle struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	EventID           uuid.UUID
	CategoryID        uuid.UUID
	Status            string
	CurrentPhaseIndex int32
	CreatedBy         uuid.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Role struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
	Name           string
	Slug           string
	IsSystem       bool
	CreatedAt      pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type SchemaHealth struct {
	ID        int16
	CheckedAt pgtype.Timestamptz
}

type Sport struct {
	ID            string
	Name          string
	GoverningBody string
	CreatedAt     pgtype.Timestamptz
}

type SportDiscipline struct {
	ID            string
	SportID       string
	Name          string
	DefaultConfig []byte
	CreatedAt     pgtype.Timestamptz
}

type StatusComponent struct {
	Key       string
	Name      string
	Status    string
	SortOrder int32
	UpdatedAt pgtype.Timestamptz
}

type SubscriptionPackage struct {
	ID           uuid.UUID
	Slug         string
	Name         string
	Description  string
	PriceMonthly int64
	MaxEvents    pgtype.Int4
	FeeBps       int32
	Features     []byte
	IsActive     bool
	SortOrder    int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Team struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     *uuid.UUID
	Name           string
	ShortName      pgtype.Text
	ManagerUserID  *uuid.UUID
	LogoUrl        pgtype.Text
	SeedNumber     pgtype.Int4
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type TeamRoster struct {
	ID           uuid.UUID
	TeamID       uuid.UUID
	TicketID     *uuid.UUID
	UserID       *uuid.UUID
	PlayerName   string
	JerseyNumber pgtype.Int4
	Position     pgtype.Text
	IsCaptain    bool
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Ticket struct {
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
	EventID             uuid.UUID
	CategoryID          uuid.UUID
	OrderID             uuid.UUID
	ParticipantID       *uuid.UUID
	TicketNumber        string
	Status              string
	HolderName          string
	HolderEmail         string
	EventTitle          string
	CategoryName        string
	QrVersion           int32
	IssuedAt            pgtype.Timestamptz
	UsedAt              pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	BibNumber           pgtype.Text
	BibAssignedAt       pgtype.Timestamptz
	BibAssignedBy       *uuid.UUID
	BibAssignmentMethod pgtype.Text
	WaveID              *uuid.UUID
	FormAnswers         []byte
}

type TimingCheckpoint struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	Code            string
	Name            string
	CheckpointType  string
	OrderIndex      int32
	DistanceMeters  pgtype.Int4
	CreatedAt       pgtype.Timestamptz
	Aliases         []string
	ProviderAliases []byte
}

type TimingConfig struct {
	ID                   uuid.UUID
	OrganizationID       uuid.UUID
	EventID              uuid.UUID
	Provider             string
	IngestionTokenHash   string
	IngestionTokenPrefix string
	EncryptedApiKey      pgtype.Text
	ExternalRaceID       pgtype.Text
	IsActive             bool
	Settings             []byte
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Transport            string
	SyncMode             string
	Policy               []byte
}

type TimingPassing struct {
	ID             int64
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CheckpointCode string
	Provider       string
	ExternalReadID pgtype.Text
	ChipCode       string
	BibNumber      pgtype.Text
	ObservedAt     pgtype.Timestamptz
	ReceivedAt     pgtype.Timestamptz
	RawPayload     pgtype.Text
	Metadata       []byte
	Processed      bool
	ProcessedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	RawChipCode    pgtype.Text
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    pgtype.Text
	FullName        string
	Phone           pgtype.Text
	IsPlatformAdmin bool
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	MembershipID    pgtype.Text
}

type Waitlist struct {
	ID                   uuid.UUID
	OrganizationID       uuid.UUID
	EventID              uuid.UUID
	CategoryID           uuid.UUID
	PoolID               *uuid.UUID
	Mode                 string
	Status               string
	MaxPromotionBatch    int32
	PromotionWindowHours int32
	AutoPromote          bool
	Seed                 pgtype.Text
	CreatedAt            pgtype.Timestamptz
}

type WaitlistEntry struct {
	ID                   uuid.UUID
	WaitlistID           uuid.UUID
	ParticipantID        uuid.UUID
	EventID              uuid.UUID
	CategoryID           uuid.UUID
	Source               string
	SourceRefID          *uuid.UUID
	Status               string
	Rank                 int64
	NotifiedAt           pgtype.Timestamptz
	PromotedAt           pgtype.Timestamptz
	AccessGrantID        *uuid.UUID
	PromotionWindowHours pgtype.Int4
	CreatedAt            pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID             uuid.UUID
	EndpointID     uuid.UUID
	OrganizationID uuid.UUID
	EventType      string
	EventKey       string
	Payload        []byte
	Status         string
	Attempts       int32
	LastError      pgtype.Text
	NextAttemptAt  pgtype.Timestamptz
	DeliveredAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type WebhookEndpoint struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Url            string
	Secret         string
	Events         []byte
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
