// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, participant_id, type, channel, status, payload, attempts, last_attempt_at, sent_at, created_at FROM notifications WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Type,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (participant_id, type, channel, status, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, participant_id, type, channel, status, payload, attempts, last_attempt_at, sent_at, created_at
`

type InsertNotificationParams struct {
	ParticipantID uuid.UUID
	Type          string
	Channel       string
	Status        string
	Payload       []byte
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.ParticipantID,
		arg.Type,
		arg.Channel,
		arg.Status,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Type,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingNotifications = `-- name: ListPendingNotifications :many
SELECT id, participant_id, type, channel, status, payload, attempts, last_attempt_at, sent_at, created_at FROM notifications
WHERE status = 'pending'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListPendingNotifications(ctx context.Context, limit int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listPendingNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.Type,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications
SET status = $2,
    attempts = $3,
    last_attempt_at = $4,
    sent_at = $5
WHERE id = $1
`

type UpdateNotificationStatusParams struct {
	ID            uuid.UUID
	Status        string
	Attempts      int32
	LastAttemptAt pgtype.Timestamptz
	SentAt        pgtype.Timestamptz
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationStatus,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.LastAttemptAt,
		arg.SentAt,
	)
	return err
}
