// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orders.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveOrdersForGuestCategory = `-- name: CountActiveOrdersForGuestCategory :one
SELECT count(*) FROM orders
WHERE category_id = $1 AND guest_email = $2
  AND status IN ('PENDING_PAYMENT','PAID')
`

type CountActiveOrdersForGuestCategoryParams struct {
	CategoryID uuid.UUID
	GuestEmail pgtype.Text
}

func (q *Queries) CountActiveOrdersForGuestCategory(ctx context.Context, arg CountActiveOrdersForGuestCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOrdersForGuestCategory, arg.CategoryID, arg.GuestEmail)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveOrdersForUserCategory = `-- name: CountActiveOrdersForUserCategory :one
SELECT count(*) FROM orders
WHERE category_id = $1 AND participant_id = $2
  AND status IN ('PENDING_PAYMENT','PAID')
`

type CountActiveOrdersForUserCategoryParams struct {
	CategoryID    uuid.UUID
	ParticipantID *uuid.UUID
}

func (q *Queries) CountActiveOrdersForUserCategory(ctx context.Context, arg CountActiveOrdersForUserCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOrdersForUserCategory, arg.CategoryID, arg.ParticipantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaidByCategory = `-- name: CountPaidByCategory :one
SELECT count(*) FROM orders WHERE category_id = $1 AND status = 'PAID'
`

func (q *Queries) CountPaidByCategory(ctx context.Context, categoryID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPaidByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuestOrder = `-- name: CreateGuestOrder :one
INSERT INTO orders (
    organization_id, event_id, category_id, participant_id,
    order_number, status, subtotal, fee, discount, total, expired_at,
    guest_email, guest_name, guest_phone,
    terms_accepted_at, terms_version, waiver_accepted_at, waiver_version,
    form_answers
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17, $18,
    $19
)
RETURNING id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at, guest_email, guest_name, guest_phone, terms_accepted_at, terms_version, waiver_accepted_at, waiver_version, form_answers, refunded_amount, refund_reason, refunded_at
`

type CreateGuestOrderParams struct {
	OrganizationID   uuid.UUID
	EventID          uuid.UUID
	CategoryID       uuid.UUID
	ParticipantID    *uuid.UUID
	OrderNumber      string
	Status           string
	Subtotal         int64
	Fee              int64
	Discount         int64
	Total            int64
	ExpiredAt        pgtype.Timestamptz
	GuestEmail       pgtype.Text
	GuestName        pgtype.Text
	GuestPhone       pgtype.Text
	TermsAcceptedAt  pgtype.Timestamptz
	TermsVersion     pgtype.Text
	WaiverAcceptedAt pgtype.Timestamptz
	WaiverVersion    pgtype.Text
	FormAnswers      []byte
}

func (q *Queries) CreateGuestOrder(ctx context.Context, arg CreateGuestOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createGuestOrder,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.ParticipantID,
		arg.OrderNumber,
		arg.Status,
		arg.Subtotal,
		arg.Fee,
		arg.Discount,
		arg.Total,
		arg.ExpiredAt,
		arg.GuestEmail,
		arg.GuestName,
		arg.GuestPhone,
		arg.TermsAcceptedAt,
		arg.TermsVersion,
		arg.WaiverAcceptedAt,
		arg.WaiverVersion,
		arg.FormAnswers,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.Fee,
		&i.Discount,
		&i.Total,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestEmail,
		&i.GuestName,
		&i.GuestPhone,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.WaiverAcceptedAt,
		&i.WaiverVersion,
		&i.FormAnswers,
		&i.RefundedAmount,
		&i.RefundReason,
		&i.RefundedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (organization_id, event_id, category_id, participant_id,
    order_number, status, subtotal, fee, discount, total, expired_at, form_answers)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at, guest_email, guest_name, guest_phone, terms_accepted_at, terms_version, waiver_accepted_at, waiver_version, form_answers, refunded_amount, refund_reason, refunded_at
`

type CreateOrderParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     uuid.UUID
	ParticipantID  *uuid.UUID
	OrderNumber    string
	Status         string
	Subtotal       int64
	Fee            int64
	Discount       int64
	Total          int64
	ExpiredAt      pgtype.Timestamptz
	FormAnswers    []byte
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.ParticipantID,
		arg.OrderNumber,
		arg.Status,
		arg.Subtotal,
		arg.Fee,
		arg.Discount,
		arg.Total,
		arg.ExpiredAt,
		arg.FormAnswers,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.Fee,
		&i.Discount,
		&i.Total,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestEmail,
		&i.GuestName,
		&i.GuestPhone,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.WaiverAcceptedAt,
		&i.WaiverVersion,
		&i.FormAnswers,
		&i.RefundedAmount,
		&i.RefundReason,
		&i.RefundedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at, guest_email, guest_name, guest_phone, terms_accepted_at, terms_version, waiver_accepted_at, waiver_version, form_answers, refunded_amount, refund_reason, refunded_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.Fee,
		&i.Discount,
		&i.Total,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestEmail,
		&i.GuestName,
		&i.GuestPhone,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.WaiverAcceptedAt,
		&i.WaiverVersion,
		&i.FormAnswers,
		&i.RefundedAmount,
		&i.RefundReason,
		&i.RefundedAt,
	)
	return i, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at, guest_email, guest_name, guest_phone, terms_accepted_at, terms_version, waiver_accepted_at, waiver_version, form_answers, refunded_amount, refund_reason, refunded_at FROM orders WHERE order_number = $1
`

func (q *Queries) GetOrderByNumber(ctx context.Context, orderNumber string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, orderNumber)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.Fee,
		&i.Discount,
		&i.Total,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestEmail,
		&i.GuestName,
		&i.GuestPhone,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.WaiverAcceptedAt,
		&i.WaiverVersion,
		&i.FormAnswers,
		&i.RefundedAmount,
		&i.RefundReason,
		&i.RefundedAt,
	)
	return i, err
}

const linkOrderToParticipant = `-- name: LinkOrderToParticipant :one
UPDATE orders
SET participant_id = $2, updated_at = now()
WHERE id = $1 AND participant_id IS NULL
RETURNING id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at, guest_email, guest_name, guest_phone, terms_accepted_at, terms_version, waiver_accepted_at, waiver_version, form_answers, refunded_amount, refund_reason, refunded_at
`

type LinkOrderToParticipantParams struct {
	ID            uuid.UUID
	ParticipantID *uuid.UUID
}

func (q *Queries) LinkOrderToParticipant(ctx context.Context, arg LinkOrderToParticipantParams) (Order, error) {
	row := q.db.QueryRow(ctx, linkOrderToParticipant, arg.ID, arg.ParticipantID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.Fee,
		&i.Discount,
		&i.Total,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestEmail,
		&i.GuestName,
		&i.GuestPhone,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.WaiverAcceptedAt,
		&i.WaiverVersion,
		&i.FormAnswers,
		&i.RefundedAmount,
		&i.RefundReason,
		&i.RefundedAt,
	)
	return i, err
}

const listExpiredPendingOrders = `-- name: ListExpiredPendingOrders :many
SELECT id FROM orders
WHERE status = 'PENDING_PAYMENT' AND expired_at < now()
ORDER BY expired_at
FOR UPDATE SKIP LOCKED
LIMIT $1
`

func (q *Queries) ListExpiredPendingOrders(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByOrgEvent = `-- name: ListOrdersByOrgEvent :many
SELECT id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at, guest_email, guest_name, guest_phone, terms_accepted_at, terms_version, waiver_accepted_at, waiver_version, form_answers, refunded_amount, refund_reason, refunded_at FROM orders WHERE organization_id = $1 AND event_id = $2 ORDER BY created_at DESC
`

type ListOrdersByOrgEventParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
}

func (q *Queries) ListOrdersByOrgEvent(ctx context.Context, arg ListOrdersByOrgEventParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByOrgEvent, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.ParticipantID,
			&i.OrderNumber,
			&i.Status,
			&i.Subtotal,
			&i.Fee,
			&i.Discount,
			&i.Total,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestEmail,
			&i.GuestName,
			&i.GuestPhone,
			&i.TermsAcceptedAt,
			&i.TermsVersion,
			&i.WaiverAcceptedAt,
			&i.WaiverVersion,
			&i.FormAnswers,
			&i.RefundedAmount,
			&i.RefundReason,
			&i.RefundedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByParticipant = `-- name: ListOrdersByParticipant :many
SELECT id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at, guest_email, guest_name, guest_phone, terms_accepted_at, terms_version, waiver_accepted_at, waiver_version, form_answers, refunded_amount, refund_reason, refunded_at FROM orders WHERE participant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByParticipant(ctx context.Context, participantID *uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByParticipant, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.ParticipantID,
			&i.OrderNumber,
			&i.Status,
			&i.Subtotal,
			&i.Fee,
			&i.Discount,
			&i.Total,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestEmail,
			&i.GuestName,
			&i.GuestPhone,
			&i.TermsAcceptedAt,
			&i.TermsVersion,
			&i.WaiverAcceptedAt,
			&i.WaiverVersion,
			&i.FormAnswers,
			&i.RefundedAmount,
			&i.RefundReason,
			&i.RefundedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordOrderRefund = `-- name: RecordOrderRefund :one
UPDATE orders SET
    status = 'REFUNDED',
    refunded_amount = $2,
    refund_reason = $3,
    refunded_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at, guest_email, guest_name, guest_phone, terms_accepted_at, terms_version, waiver_accepted_at, waiver_version, form_answers, refunded_amount, refund_reason, refunded_at
`

type RecordOrderRefundParams struct {
	ID             uuid.UUID
	RefundedAmount int64
	RefundReason   pgtype.Text
}

func (q *Queries) RecordOrderRefund(ctx context.Context, arg RecordOrderRefundParams) (Order, error) {
	row := q.db.QueryRow(ctx, recordOrderRefund, arg.ID, arg.RefundedAmount, arg.RefundReason)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.Fee,
		&i.Discount,
		&i.Total,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestEmail,
		&i.GuestName,
		&i.GuestPhone,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.WaiverAcceptedAt,
		&i.WaiverVersion,
		&i.FormAnswers,
		&i.RefundedAmount,
		&i.RefundReason,
		&i.RefundedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders SET status = $2, updated_at = now()
WHERE id = $1 AND status = $3
RETURNING id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at, guest_email, guest_name, guest_phone, terms_accepted_at, terms_version, waiver_accepted_at, waiver_version, form_answers, refunded_amount, refund_reason, refunded_at
`

type UpdateOrderStatusParams struct {
	ID       uuid.UUID
	Status   string
	Status_2 string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status, arg.Status_2)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.Fee,
		&i.Discount,
		&i.Total,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestEmail,
		&i.GuestName,
		&i.GuestPhone,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.WaiverAcceptedAt,
		&i.WaiverVersion,
		&i.FormAnswers,
		&i.RefundedAmount,
		&i.RefundReason,
		&i.RefundedAt,
	)
	return i, err
}
