// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveOrdersForUserCategory = `-- name: CountActiveOrdersForUserCategory :one
SELECT count(*) FROM orders
WHERE category_id = $1 AND participant_id = $2
  AND status IN ('PENDING_PAYMENT','PAID')
`

type CountActiveOrdersForUserCategoryParams struct {
	CategoryID    uuid.UUID
	ParticipantID uuid.UUID
}

func (q *Queries) CountActiveOrdersForUserCategory(ctx context.Context, arg CountActiveOrdersForUserCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOrdersForUserCategory, arg.CategoryID, arg.ParticipantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaidByCategory = `-- name: CountPaidByCategory :one
SELECT count(*) FROM orders WHERE category_id = $1 AND status = 'PAID'
`

func (q *Queries) CountPaidByCategory(ctx context.Context, categoryID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPaidByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (organization_id, event_id, category_id, participant_id,
    order_number, status, subtotal, fee, discount, total, expired_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at
`

type CreateOrderParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     uuid.UUID
	ParticipantID  uuid.UUID
	OrderNumber    string
	Status         string
	Subtotal       int64
	Fee            int64
	Discount       int64
	Total          int64
	ExpiredAt      pgtype.Timestamptz
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.ParticipantID,
		arg.OrderNumber,
		arg.Status,
		arg.Subtotal,
		arg.Fee,
		arg.Discount,
		arg.Total,
		arg.ExpiredAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.Fee,
		&i.Discount,
		&i.Total,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.Fee,
		&i.Discount,
		&i.Total,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at FROM orders WHERE order_number = $1
`

func (q *Queries) GetOrderByNumber(ctx context.Context, orderNumber string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, orderNumber)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.Fee,
		&i.Discount,
		&i.Total,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredPendingOrders = `-- name: ListExpiredPendingOrders :many
SELECT id FROM orders
WHERE status = 'PENDING_PAYMENT' AND expired_at < now()
ORDER BY expired_at
FOR UPDATE SKIP LOCKED
LIMIT $1
`

func (q *Queries) ListExpiredPendingOrders(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByOrgEvent = `-- name: ListOrdersByOrgEvent :many
SELECT id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at FROM orders WHERE organization_id = $1 AND event_id = $2 ORDER BY created_at DESC
`

type ListOrdersByOrgEventParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
}

func (q *Queries) ListOrdersByOrgEvent(ctx context.Context, arg ListOrdersByOrgEventParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByOrgEvent, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.ParticipantID,
			&i.OrderNumber,
			&i.Status,
			&i.Subtotal,
			&i.Fee,
			&i.Discount,
			&i.Total,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByParticipant = `-- name: ListOrdersByParticipant :many
SELECT id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at FROM orders WHERE participant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByParticipant(ctx context.Context, participantID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByParticipant, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.ParticipantID,
			&i.OrderNumber,
			&i.Status,
			&i.Subtotal,
			&i.Fee,
			&i.Discount,
			&i.Total,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders SET status = $2, updated_at = now()
WHERE id = $1 AND status = $3
RETURNING id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID       uuid.UUID
	Status   string
	Status_2 string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status, arg.Status_2)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.Fee,
		&i.Discount,
		&i.Total,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
