// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name string
	Slug string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllOrganizationsWithStats = `-- name: ListAllOrganizationsWithStats :many
SELECT 
    o.id,
    o.name,
    o.slug,
    o.created_at,
    (SELECT count(*) FROM events e WHERE e.organization_id = o.id)::bigint AS event_count,
    (SELECT count(*) FROM organization_members m WHERE m.organization_id = o.id)::bigint AS member_count,
    COALESCE((
        SELECT u.email FROM organization_members om 
        JOIN users u ON u.id = om.user_id 
        WHERE om.organization_id = o.id 
        ORDER BY om.created_at ASC LIMIT 1
    ), '')::text AS lead_email,
    COALESCE((
        SELECT u.full_name FROM organization_members om 
        JOIN users u ON u.id = om.user_id 
        WHERE om.organization_id = o.id 
        ORDER BY om.created_at ASC LIMIT 1
    ), '')::text AS lead_name
FROM organizations o
ORDER BY o.created_at DESC
`

type ListAllOrganizationsWithStatsRow struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	CreatedAt   pgtype.Timestamptz
	EventCount  int64
	MemberCount int64
	LeadEmail   string
	LeadName    string
}

func (q *Queries) ListAllOrganizationsWithStats(ctx context.Context) ([]ListAllOrganizationsWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listAllOrganizationsWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllOrganizationsWithStatsRow
	for rows.Next() {
		var i ListAllOrganizationsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.EventCount,
			&i.MemberCount,
			&i.LeadEmail,
			&i.LeadName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT o.id, o.name, o.slug, o.created_at, o.updated_at FROM organizations o
JOIN organization_members m ON m.organization_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at
`

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
