// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_webhooks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimWebhookDedupe = `-- name: ClaimWebhookDedupe :one
UPDATE payment_webhooks
SET dedupe_key = $2
WHERE id = $1
RETURNING id, gateway, event_type, merchant_reference, gateway_reference, signature, signature_valid, payload, dedupe_key, processing_status, processed_payment_id, error_detail, received_at, processed_at
`

type ClaimWebhookDedupeParams struct {
	ID        uuid.UUID
	DedupeKey pgtype.Text
}

func (q *Queries) ClaimWebhookDedupe(ctx context.Context, arg ClaimWebhookDedupeParams) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, claimWebhookDedupe, arg.ID, arg.DedupeKey)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.Gateway,
		&i.EventType,
		&i.MerchantReference,
		&i.GatewayReference,
		&i.Signature,
		&i.SignatureValid,
		&i.Payload,
		&i.DedupeKey,
		&i.ProcessingStatus,
		&i.ProcessedPaymentID,
		&i.ErrorDetail,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const createPaymentWebhook = `-- name: CreatePaymentWebhook :one
INSERT INTO payment_webhooks (
    gateway, event_type, merchant_reference, gateway_reference, signature,
    signature_valid, payload, processing_status
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, gateway, event_type, merchant_reference, gateway_reference, signature, signature_valid, payload, dedupe_key, processing_status, processed_payment_id, error_detail, received_at, processed_at
`

type CreatePaymentWebhookParams struct {
	Gateway           string
	EventType         pgtype.Text
	MerchantReference pgtype.Text
	GatewayReference  pgtype.Text
	Signature         pgtype.Text
	SignatureValid    bool
	Payload           []byte
	ProcessingStatus  string
}

func (q *Queries) CreatePaymentWebhook(ctx context.Context, arg CreatePaymentWebhookParams) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, createPaymentWebhook,
		arg.Gateway,
		arg.EventType,
		arg.MerchantReference,
		arg.GatewayReference,
		arg.Signature,
		arg.SignatureValid,
		arg.Payload,
		arg.ProcessingStatus,
	)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.Gateway,
		&i.EventType,
		&i.MerchantReference,
		&i.GatewayReference,
		&i.Signature,
		&i.SignatureValid,
		&i.Payload,
		&i.DedupeKey,
		&i.ProcessingStatus,
		&i.ProcessedPaymentID,
		&i.ErrorDetail,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE payment_webhooks
SET processing_status = $2, processed_payment_id = $3, error_detail = $4, processed_at = now()
WHERE id = $1
`

type MarkWebhookProcessedParams struct {
	ID                 uuid.UUID
	ProcessingStatus   string
	ProcessedPaymentID *uuid.UUID
	ErrorDetail        pgtype.Text
}

func (q *Queries) MarkWebhookProcessed(ctx context.Context, arg MarkWebhookProcessedParams) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed,
		arg.ID,
		arg.ProcessingStatus,
		arg.ProcessedPaymentID,
		arg.ErrorDetail,
	)
	return err
}
