// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payment_channels.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const isPaymentChannelEnabled = `-- name: IsPaymentChannelEnabled :one
SELECT COALESCE(
    (SELECT is_enabled FROM event_payment_channels WHERE event_id = $1 AND channel_code = $2),
    true
)::boolean AS is_enabled
`

type IsPaymentChannelEnabledParams struct {
	EventID     uuid.UUID
	ChannelCode string
}

func (q *Queries) IsPaymentChannelEnabled(ctx context.Context, arg IsPaymentChannelEnabledParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPaymentChannelEnabled, arg.EventID, arg.ChannelCode)
	var is_enabled bool
	err := row.Scan(&is_enabled)
	return is_enabled, err
}

const listPaymentChannelsByEvent = `-- name: ListPaymentChannelsByEvent :many
SELECT id, event_id, channel_code, is_enabled, created_at, updated_at FROM event_payment_channels WHERE event_id = $1 ORDER BY channel_code
`

func (q *Queries) ListPaymentChannelsByEvent(ctx context.Context, eventID uuid.UUID) ([]EventPaymentChannel, error) {
	rows, err := q.db.Query(ctx, listPaymentChannelsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventPaymentChannel
	for rows.Next() {
		var i EventPaymentChannel
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ChannelCode,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEventPaymentChannel = `-- name: UpsertEventPaymentChannel :one
INSERT INTO event_payment_channels (event_id, channel_code, is_enabled, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (event_id, channel_code)
DO UPDATE SET is_enabled = EXCLUDED.is_enabled, updated_at = now()
RETURNING id, event_id, channel_code, is_enabled, created_at, updated_at
`

type UpsertEventPaymentChannelParams struct {
	EventID     uuid.UUID
	ChannelCode string
	IsEnabled   bool
}

func (q *Queries) UpsertEventPaymentChannel(ctx context.Context, arg UpsertEventPaymentChannelParams) (EventPaymentChannel, error) {
	row := q.db.QueryRow(ctx, upsertEventPaymentChannel, arg.EventID, arg.ChannelCode, arg.IsEnabled)
	var i EventPaymentChannel
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ChannelCode,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
