// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    organization_id, event_id, order_id, participant_id, gateway, method, channel,
    status, amount, currency, gateway_reference, merchant_reference, pay_url, qr_string,
    va_number, instructions, expires_at
) VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17
)
RETURNING id, organization_id, event_id, order_id, participant_id, gateway, method, channel, status, amount, currency, gateway_reference, merchant_reference, pay_url, qr_string, va_number, instructions, expires_at, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	OrganizationID    uuid.UUID
	EventID           uuid.UUID
	OrderID           uuid.UUID
	ParticipantID     uuid.UUID
	Gateway           string
	Method            string
	Channel           pgtype.Text
	Status            string
	Amount            int64
	Currency          string
	GatewayReference  pgtype.Text
	MerchantReference string
	PayUrl            pgtype.Text
	QrString          pgtype.Text
	VaNumber          pgtype.Text
	Instructions      []byte
	ExpiresAt         pgtype.Timestamptz
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrganizationID,
		arg.EventID,
		arg.OrderID,
		arg.ParticipantID,
		arg.Gateway,
		arg.Method,
		arg.Channel,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.GatewayReference,
		arg.MerchantReference,
		arg.PayUrl,
		arg.QrString,
		arg.VaNumber,
		arg.Instructions,
		arg.ExpiresAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.OrderID,
		&i.ParticipantID,
		&i.Gateway,
		&i.Method,
		&i.Channel,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.GatewayReference,
		&i.MerchantReference,
		&i.PayUrl,
		&i.QrString,
		&i.VaNumber,
		&i.Instructions,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePaymentByOrder = `-- name: GetActivePaymentByOrder :one
SELECT id, organization_id, event_id, order_id, participant_id, gateway, method, channel, status, amount, currency, gateway_reference, merchant_reference, pay_url, qr_string, va_number, instructions, expires_at, paid_at, created_at, updated_at FROM payments WHERE order_id = $1 AND status IN ('PENDING','PAID') LIMIT 1
`

func (q *Queries) GetActivePaymentByOrder(ctx context.Context, orderID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getActivePaymentByOrder, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.OrderID,
		&i.ParticipantID,
		&i.Gateway,
		&i.Method,
		&i.Channel,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.GatewayReference,
		&i.MerchantReference,
		&i.PayUrl,
		&i.QrString,
		&i.VaNumber,
		&i.Instructions,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIDForUpdate = `-- name: GetOrderByIDForUpdate :one
SELECT id, organization_id, event_id, category_id, participant_id, order_number, status, subtotal, fee, discount, total, expired_at, created_at, updated_at FROM orders WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetOrderByIDForUpdate(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIDForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.Fee,
		&i.Discount,
		&i.Total,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, organization_id, event_id, order_id, participant_id, gateway, method, channel, status, amount, currency, gateway_reference, merchant_reference, pay_url, qr_string, va_number, instructions, expires_at, paid_at, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.OrderID,
		&i.ParticipantID,
		&i.Gateway,
		&i.Method,
		&i.Channel,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.GatewayReference,
		&i.MerchantReference,
		&i.PayUrl,
		&i.QrString,
		&i.VaNumber,
		&i.Instructions,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByMerchantRef = `-- name: GetPaymentByMerchantRef :one
SELECT id, organization_id, event_id, order_id, participant_id, gateway, method, channel, status, amount, currency, gateway_reference, merchant_reference, pay_url, qr_string, va_number, instructions, expires_at, paid_at, created_at, updated_at FROM payments WHERE merchant_reference = $1
`

func (q *Queries) GetPaymentByMerchantRef(ctx context.Context, merchantReference string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByMerchantRef, merchantReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.OrderID,
		&i.ParticipantID,
		&i.Gateway,
		&i.Method,
		&i.Channel,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.GatewayReference,
		&i.MerchantReference,
		&i.PayUrl,
		&i.QrString,
		&i.VaNumber,
		&i.Instructions,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByMerchantRefForUpdate = `-- name: GetPaymentByMerchantRefForUpdate :one
SELECT id, organization_id, event_id, order_id, participant_id, gateway, method, channel, status, amount, currency, gateway_reference, merchant_reference, pay_url, qr_string, va_number, instructions, expires_at, paid_at, created_at, updated_at FROM payments WHERE merchant_reference = $1 FOR UPDATE
`

func (q *Queries) GetPaymentByMerchantRefForUpdate(ctx context.Context, merchantReference string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByMerchantRefForUpdate, merchantReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.OrderID,
		&i.ParticipantID,
		&i.Gateway,
		&i.Method,
		&i.Channel,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.GatewayReference,
		&i.MerchantReference,
		&i.PayUrl,
		&i.QrString,
		&i.VaNumber,
		&i.Instructions,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByOrder = `-- name: ListPaymentsByOrder :many
SELECT id, organization_id, event_id, order_id, participant_id, gateway, method, channel, status, amount, currency, gateway_reference, merchant_reference, pay_url, qr_string, va_number, instructions, expires_at, paid_at, created_at, updated_at FROM payments WHERE order_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByOrder(ctx context.Context, orderID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.OrderID,
			&i.ParticipantID,
			&i.Gateway,
			&i.Method,
			&i.Channel,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.GatewayReference,
			&i.MerchantReference,
			&i.PayUrl,
			&i.QrString,
			&i.VaNumber,
			&i.Instructions,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByOrgEvent = `-- name: ListPaymentsByOrgEvent :many
SELECT id, organization_id, event_id, order_id, participant_id, gateway, method, channel, status, amount, currency, gateway_reference, merchant_reference, pay_url, qr_string, va_number, instructions, expires_at, paid_at, created_at, updated_at FROM payments WHERE organization_id = $1 AND event_id = $2 ORDER BY created_at DESC
`

type ListPaymentsByOrgEventParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
}

func (q *Queries) ListPaymentsByOrgEvent(ctx context.Context, arg ListPaymentsByOrgEventParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrgEvent, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.OrderID,
			&i.ParticipantID,
			&i.Gateway,
			&i.Method,
			&i.Channel,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.GatewayReference,
			&i.MerchantReference,
			&i.PayUrl,
			&i.QrString,
			&i.VaNumber,
			&i.Instructions,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentPaid = `-- name: MarkPaymentPaid :one
UPDATE payments
SET status = 'PAID', paid_at = $2, gateway_reference = COALESCE($3, gateway_reference), updated_at = now()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, organization_id, event_id, order_id, participant_id, gateway, method, channel, status, amount, currency, gateway_reference, merchant_reference, pay_url, qr_string, va_number, instructions, expires_at, paid_at, created_at, updated_at
`

type MarkPaymentPaidParams struct {
	ID               uuid.UUID
	PaidAt           pgtype.Timestamptz
	GatewayReference pgtype.Text
}

func (q *Queries) MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentPaid, arg.ID, arg.PaidAt, arg.GatewayReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.OrderID,
		&i.ParticipantID,
		&i.Gateway,
		&i.Method,
		&i.Channel,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.GatewayReference,
		&i.MerchantReference,
		&i.PayUrl,
		&i.QrString,
		&i.VaNumber,
		&i.Instructions,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2, updated_at = now()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, organization_id, event_id, order_id, participant_id, gateway, method, channel, status, amount, currency, gateway_reference, merchant_reference, pay_url, qr_string, va_number, instructions, expires_at, paid_at, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.OrderID,
		&i.ParticipantID,
		&i.Gateway,
		&i.Method,
		&i.Channel,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.GatewayReference,
		&i.MerchantReference,
		&i.PayUrl,
		&i.QrString,
		&i.VaNumber,
		&i.Instructions,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
