// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payouts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayoutAccount = `-- name: CreatePayoutAccount :one
INSERT INTO org_payout_accounts (
    organization_id, bank_name, bank_code, account_number, account_name, is_verified
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (organization_id, bank_code, account_number) DO UPDATE SET
    bank_name = EXCLUDED.bank_name,
    account_name = EXCLUDED.account_name,
    updated_at = now()
RETURNING id, organization_id, bank_name, bank_code, account_number, account_name, is_verified, created_at, updated_at
`

type CreatePayoutAccountParams struct {
	OrganizationID uuid.UUID
	BankName       string
	BankCode       string
	AccountNumber  string
	AccountName    string
	IsVerified     bool
}

func (q *Queries) CreatePayoutAccount(ctx context.Context, arg CreatePayoutAccountParams) (OrgPayoutAccount, error) {
	row := q.db.QueryRow(ctx, createPayoutAccount,
		arg.OrganizationID,
		arg.BankName,
		arg.BankCode,
		arg.AccountNumber,
		arg.AccountName,
		arg.IsVerified,
	)
	var i OrgPayoutAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BankName,
		&i.BankCode,
		&i.AccountNumber,
		&i.AccountName,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayoutRequest = `-- name: CreatePayoutRequest :one
INSERT INTO payout_requests (
    organization_id, event_id, payout_account_id, amount, currency, status,
    notes, requested_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, event_id, payout_account_id, amount, currency, status, notes, rejection_reason, requested_by, processed_by, processed_at, created_at, updated_at
`

type CreatePayoutRequestParams struct {
	OrganizationID  uuid.UUID
	EventID         *uuid.UUID
	PayoutAccountID *uuid.UUID
	Amount          int64
	Currency        string
	Status          string
	Notes           pgtype.Text
	RequestedBy     uuid.UUID
}

func (q *Queries) CreatePayoutRequest(ctx context.Context, arg CreatePayoutRequestParams) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, createPayoutRequest,
		arg.OrganizationID,
		arg.EventID,
		arg.PayoutAccountID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.Notes,
		arg.RequestedBy,
	)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.PayoutAccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Notes,
		&i.RejectionReason,
		&i.RequestedBy,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePayoutAccount = `-- name: DeletePayoutAccount :exec
DELETE FROM org_payout_accounts WHERE id = $1 AND organization_id = $2
`

type DeletePayoutAccountParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeletePayoutAccount(ctx context.Context, arg DeletePayoutAccountParams) error {
	_, err := q.db.Exec(ctx, deletePayoutAccount, arg.ID, arg.OrganizationID)
	return err
}

const getOrgRefundSummary = `-- name: GetOrgRefundSummary :one
SELECT COALESCE(SUM(refunded_amount), 0)::bigint AS total_refunded
FROM orders
WHERE organization_id = $1
`

func (q *Queries) GetOrgRefundSummary(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getOrgRefundSummary, organizationID)
	var total_refunded int64
	err := row.Scan(&total_refunded)
	return total_refunded, err
}

const getPayoutAccountByID = `-- name: GetPayoutAccountByID :one
SELECT id, organization_id, bank_name, bank_code, account_number, account_name, is_verified, created_at, updated_at FROM org_payout_accounts WHERE id = $1 AND organization_id = $2
`

type GetPayoutAccountByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetPayoutAccountByID(ctx context.Context, arg GetPayoutAccountByIDParams) (OrgPayoutAccount, error) {
	row := q.db.QueryRow(ctx, getPayoutAccountByID, arg.ID, arg.OrganizationID)
	var i OrgPayoutAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BankName,
		&i.BankCode,
		&i.AccountNumber,
		&i.AccountName,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayoutAccountsByOrg = `-- name: ListPayoutAccountsByOrg :many
SELECT id, organization_id, bank_name, bank_code, account_number, account_name, is_verified, created_at, updated_at FROM org_payout_accounts
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPayoutAccountsByOrg(ctx context.Context, organizationID uuid.UUID) ([]OrgPayoutAccount, error) {
	rows, err := q.db.Query(ctx, listPayoutAccountsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgPayoutAccount
	for rows.Next() {
		var i OrgPayoutAccount
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.BankName,
			&i.BankCode,
			&i.AccountNumber,
			&i.AccountName,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutRequestsByEvent = `-- name: ListPayoutRequestsByEvent :many
SELECT id, organization_id, event_id, payout_account_id, amount, currency, status, notes, rejection_reason, requested_by, processed_by, processed_at, created_at, updated_at FROM payout_requests
WHERE organization_id = $1 AND event_id = $2
ORDER BY created_at DESC
`

type ListPayoutRequestsByEventParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

func (q *Queries) ListPayoutRequestsByEvent(ctx context.Context, arg ListPayoutRequestsByEventParams) ([]PayoutRequest, error) {
	rows, err := q.db.Query(ctx, listPayoutRequestsByEvent, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayoutRequest
	for rows.Next() {
		var i PayoutRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.PayoutAccountID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Notes,
			&i.RejectionReason,
			&i.RequestedBy,
			&i.ProcessedBy,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutRequestsByOrg = `-- name: ListPayoutRequestsByOrg :many
SELECT id, organization_id, event_id, payout_account_id, amount, currency, status, notes, rejection_reason, requested_by, processed_by, processed_at, created_at, updated_at FROM payout_requests
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPayoutRequestsByOrg(ctx context.Context, organizationID uuid.UUID) ([]PayoutRequest, error) {
	rows, err := q.db.Query(ctx, listPayoutRequestsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayoutRequest
	for rows.Next() {
		var i PayoutRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.PayoutAccountID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Notes,
			&i.RejectionReason,
			&i.RequestedBy,
			&i.ProcessedBy,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayoutRequestStatus = `-- name: UpdatePayoutRequestStatus :one
UPDATE payout_requests SET
    status = $2,
    rejection_reason = $3,
    processed_by = $4,
    processed_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, payout_account_id, amount, currency, status, notes, rejection_reason, requested_by, processed_by, processed_at, created_at, updated_at
`

type UpdatePayoutRequestStatusParams struct {
	ID              uuid.UUID
	Status          string
	RejectionReason pgtype.Text
	ProcessedBy     *uuid.UUID
}

func (q *Queries) UpdatePayoutRequestStatus(ctx context.Context, arg UpdatePayoutRequestStatusParams) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, updatePayoutRequestStatus,
		arg.ID,
		arg.Status,
		arg.RejectionReason,
		arg.ProcessedBy,
	)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.PayoutAccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Notes,
		&i.RejectionReason,
		&i.RequestedBy,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
