// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAdmission = `-- name: ConsumeAdmission :exec
UPDATE queue_admissions SET status='CONSUMED' WHERE id = $1 AND status = 'ACTIVE'
`

func (q *Queries) ConsumeAdmission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeAdmission, id)
	return err
}

const countTokensByStatus = `-- name: CountTokensByStatus :one
SELECT count(*) FROM queue_tokens WHERE event_id = $1 AND status = $2
`

type CountTokensByStatusParams struct {
	EventID uuid.UUID
	Status  string
}

func (q *Queries) CountTokensByStatus(ctx context.Context, arg CountTokensByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTokensByStatus, arg.EventID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmission = `-- name: CreateAdmission :one
INSERT INTO queue_admissions (token_id, event_id, participant_id, checkout_expires_at, status)
VALUES ($1,$2,$3,$4,'ACTIVE')
RETURNING id, token_id, event_id, participant_id, checkout_expires_at, status, created_at
`

type CreateAdmissionParams struct {
	TokenID           uuid.UUID
	EventID           uuid.UUID
	ParticipantID     uuid.UUID
	CheckoutExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAdmission(ctx context.Context, arg CreateAdmissionParams) (QueueAdmission, error) {
	row := q.db.QueryRow(ctx, createAdmission,
		arg.TokenID,
		arg.EventID,
		arg.ParticipantID,
		arg.CheckoutExpiresAt,
	)
	var i QueueAdmission
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.EventID,
		&i.ParticipantID,
		&i.CheckoutExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createQueueToken = `-- name: CreateQueueToken :one
INSERT INTO queue_tokens (organization_id, event_id, participant_id, status, pool, score)
VALUES ($1,$2,$3,'WAITING',$4,$5)
ON CONFLICT (event_id, participant_id) DO NOTHING
RETURNING id, organization_id, event_id, participant_id, status, pool, score, joined_at, allowed_at, expired_at, completed_at, created_at, updated_at
`

type CreateQueueTokenParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	ParticipantID  uuid.UUID
	Pool           string
	Score          int64
}

func (q *Queries) CreateQueueToken(ctx context.Context, arg CreateQueueTokenParams) (QueueToken, error) {
	row := q.db.QueryRow(ctx, createQueueToken,
		arg.OrganizationID,
		arg.EventID,
		arg.ParticipantID,
		arg.Pool,
		arg.Score,
	)
	var i QueueToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.ParticipantID,
		&i.Status,
		&i.Pool,
		&i.Score,
		&i.JoinedAt,
		&i.AllowedAt,
		&i.ExpiredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireAdmission = `-- name: ExpireAdmission :exec
UPDATE queue_admissions SET status='EXPIRED' WHERE id = $1 AND status = 'ACTIVE'
`

func (q *Queries) ExpireAdmission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, expireAdmission, id)
	return err
}

const getActiveAdmissionByParticipant = `-- name: GetActiveAdmissionByParticipant :one
SELECT id, token_id, event_id, participant_id, checkout_expires_at, status, created_at FROM queue_admissions
WHERE event_id = $1 AND participant_id = $2 AND status = 'ACTIVE'
`

type GetActiveAdmissionByParticipantParams struct {
	EventID       uuid.UUID
	ParticipantID uuid.UUID
}

func (q *Queries) GetActiveAdmissionByParticipant(ctx context.Context, arg GetActiveAdmissionByParticipantParams) (QueueAdmission, error) {
	row := q.db.QueryRow(ctx, getActiveAdmissionByParticipant, arg.EventID, arg.ParticipantID)
	var i QueueAdmission
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.EventID,
		&i.ParticipantID,
		&i.CheckoutExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getQueueControl = `-- name: GetQueueControl :one
SELECT event_id, state, release_rate, randomization_seed, sale_start_at, presale_pool_open_at, updated_at FROM queue_control WHERE event_id = $1
`

func (q *Queries) GetQueueControl(ctx context.Context, eventID uuid.UUID) (QueueControl, error) {
	row := q.db.QueryRow(ctx, getQueueControl, eventID)
	var i QueueControl
	err := row.Scan(
		&i.EventID,
		&i.State,
		&i.ReleaseRate,
		&i.RandomizationSeed,
		&i.SaleStartAt,
		&i.PresalePoolOpenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueueTokenByEventParticipant = `-- name: GetQueueTokenByEventParticipant :one
SELECT id, organization_id, event_id, participant_id, status, pool, score, joined_at, allowed_at, expired_at, completed_at, created_at, updated_at FROM queue_tokens WHERE event_id = $1 AND participant_id = $2
`

type GetQueueTokenByEventParticipantParams struct {
	EventID       uuid.UUID
	ParticipantID uuid.UUID
}

func (q *Queries) GetQueueTokenByEventParticipant(ctx context.Context, arg GetQueueTokenByEventParticipantParams) (QueueToken, error) {
	row := q.db.QueryRow(ctx, getQueueTokenByEventParticipant, arg.EventID, arg.ParticipantID)
	var i QueueToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.ParticipantID,
		&i.Status,
		&i.Pool,
		&i.Score,
		&i.JoinedAt,
		&i.AllowedAt,
		&i.ExpiredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueueTokenByID = `-- name: GetQueueTokenByID :one
SELECT id, organization_id, event_id, participant_id, status, pool, score, joined_at, allowed_at, expired_at, completed_at, created_at, updated_at FROM queue_tokens WHERE id = $1
`

func (q *Queries) GetQueueTokenByID(ctx context.Context, id uuid.UUID) (QueueToken, error) {
	row := q.db.QueryRow(ctx, getQueueTokenByID, id)
	var i QueueToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.ParticipantID,
		&i.Status,
		&i.Pool,
		&i.Score,
		&i.JoinedAt,
		&i.AllowedAt,
		&i.ExpiredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsWithRunningQueue = `-- name: ListEventsWithRunningQueue :many
SELECT event_id FROM queue_control WHERE state = 'RUNNING'
`

func (q *Queries) ListEventsWithRunningQueue(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEventsWithRunningQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var event_id uuid.UUID
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredActiveAdmissions = `-- name: ListExpiredActiveAdmissions :many
SELECT id, token_id, event_id, participant_id, checkout_expires_at, status, created_at FROM queue_admissions
WHERE status = 'ACTIVE' AND checkout_expires_at < now()
ORDER BY checkout_expires_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListExpiredActiveAdmissions(ctx context.Context, limit int32) ([]QueueAdmission, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveAdmissions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueAdmission
	for rows.Next() {
		var i QueueAdmission
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.EventID,
			&i.ParticipantID,
			&i.CheckoutExpiresAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingTokens = `-- name: ListWaitingTokens :many
SELECT id, organization_id, event_id, participant_id, status, pool, score, joined_at, allowed_at, expired_at, completed_at, created_at, updated_at FROM queue_tokens
WHERE event_id = $1 AND status = 'WAITING'
ORDER BY pool DESC, score ASC
LIMIT $2
`

type ListWaitingTokensParams struct {
	EventID uuid.UUID
	Limit   int32
}

func (q *Queries) ListWaitingTokens(ctx context.Context, arg ListWaitingTokensParams) ([]QueueToken, error) {
	rows, err := q.db.Query(ctx, listWaitingTokens, arg.EventID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueToken
	for rows.Next() {
		var i QueueToken
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.ParticipantID,
			&i.Status,
			&i.Pool,
			&i.Score,
			&i.JoinedAt,
			&i.AllowedAt,
			&i.ExpiredAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingTokensAll = `-- name: ListWaitingTokensAll :many
SELECT id, organization_id, event_id, participant_id, status, pool, score, joined_at, allowed_at, expired_at, completed_at, created_at, updated_at FROM queue_tokens WHERE event_id = $1 AND status = 'WAITING' ORDER BY pool DESC, score ASC
`

func (q *Queries) ListWaitingTokensAll(ctx context.Context, eventID uuid.UUID) ([]QueueToken, error) {
	rows, err := q.db.Query(ctx, listWaitingTokensAll, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueToken
	for rows.Next() {
		var i QueueToken
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.ParticipantID,
			&i.Status,
			&i.Pool,
			&i.Score,
			&i.JoinedAt,
			&i.AllowedAt,
			&i.ExpiredAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTokenAllowed = `-- name: MarkTokenAllowed :one
UPDATE queue_tokens SET status='ALLOWED', allowed_at=now(), updated_at=now()
WHERE id = $1 AND status = 'WAITING'
RETURNING id, organization_id, event_id, participant_id, status, pool, score, joined_at, allowed_at, expired_at, completed_at, created_at, updated_at
`

func (q *Queries) MarkTokenAllowed(ctx context.Context, id uuid.UUID) (QueueToken, error) {
	row := q.db.QueryRow(ctx, markTokenAllowed, id)
	var i QueueToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.ParticipantID,
		&i.Status,
		&i.Pool,
		&i.Score,
		&i.JoinedAt,
		&i.AllowedAt,
		&i.ExpiredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTokenCompleted = `-- name: MarkTokenCompleted :exec
UPDATE queue_tokens SET status='COMPLETED', completed_at=now(), updated_at=now()
WHERE id = $1 AND status = 'ALLOWED'
`

func (q *Queries) MarkTokenCompleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTokenCompleted, id)
	return err
}

const requeueToken = `-- name: RequeueToken :exec
UPDATE queue_tokens SET status='WAITING', score=$2, allowed_at=NULL, updated_at=now()
WHERE id = $1 AND status = 'ALLOWED'
`

type RequeueTokenParams struct {
	ID    uuid.UUID
	Score int64
}

func (q *Queries) RequeueToken(ctx context.Context, arg RequeueTokenParams) error {
	_, err := q.db.Exec(ctx, requeueToken, arg.ID, arg.Score)
	return err
}

const setQueueState = `-- name: SetQueueState :exec
UPDATE queue_control SET state=$2, updated_at=now() WHERE event_id=$1
`

type SetQueueStateParams struct {
	EventID uuid.UUID
	State   string
}

func (q *Queries) SetQueueState(ctx context.Context, arg SetQueueStateParams) error {
	_, err := q.db.Exec(ctx, setQueueState, arg.EventID, arg.State)
	return err
}

const setReleaseRate = `-- name: SetReleaseRate :exec
UPDATE queue_control SET release_rate=$2, updated_at=now() WHERE event_id=$1
`

type SetReleaseRateParams struct {
	EventID     uuid.UUID
	ReleaseRate int32
}

func (q *Queries) SetReleaseRate(ctx context.Context, arg SetReleaseRateParams) error {
	_, err := q.db.Exec(ctx, setReleaseRate, arg.EventID, arg.ReleaseRate)
	return err
}

const upsertQueueControl = `-- name: UpsertQueueControl :one
INSERT INTO queue_control (event_id, state, release_rate, randomization_seed, sale_start_at, presale_pool_open_at)
VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (event_id) DO UPDATE SET
    state = EXCLUDED.state,
    release_rate = EXCLUDED.release_rate,
    randomization_seed = EXCLUDED.randomization_seed,
    sale_start_at = EXCLUDED.sale_start_at,
    presale_pool_open_at = EXCLUDED.presale_pool_open_at,
    updated_at = now()
RETURNING event_id, state, release_rate, randomization_seed, sale_start_at, presale_pool_open_at, updated_at
`

type UpsertQueueControlParams struct {
	EventID           uuid.UUID
	State             string
	ReleaseRate       int32
	RandomizationSeed pgtype.Text
	SaleStartAt       pgtype.Timestamptz
	PresalePoolOpenAt pgtype.Timestamptz
}

func (q *Queries) UpsertQueueControl(ctx context.Context, arg UpsertQueueControlParams) (QueueControl, error) {
	row := q.db.QueryRow(ctx, upsertQueueControl,
		arg.EventID,
		arg.State,
		arg.ReleaseRate,
		arg.RandomizationSeed,
		arg.SaleStartAt,
		arg.PresalePoolOpenAt,
	)
	var i QueueControl
	err := row.Scan(
		&i.EventID,
		&i.State,
		&i.ReleaseRate,
		&i.RandomizationSeed,
		&i.SaleStartAt,
		&i.PresalePoolOpenAt,
		&i.UpdatedAt,
	)
	return i, err
}
