// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: racepack.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkOrganizationMembership = `-- name: CheckOrganizationMembership :one
SELECT EXISTS (
    SELECT 1 FROM organization_members
    WHERE organization_id = $1 AND user_id = $2 AND removed_at IS NULL
) AS is_member
`

type CheckOrganizationMembershipParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) CheckOrganizationMembership(ctx context.Context, arg CheckOrganizationMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkOrganizationMembership, arg.OrganizationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const countRacepackPickupRecordsByCounter = `-- name: CountRacepackPickupRecordsByCounter :many
SELECT counter_id, COUNT(*) AS pickup_count
FROM racepack_pickup_records
WHERE event_id = $1 AND status = 'PICKED_UP'
  AND pickup_timestamp >= $2 AND pickup_timestamp < $3
GROUP BY counter_id
`

type CountRacepackPickupRecordsByCounterParams struct {
	EventID           uuid.UUID
	PickupTimestamp   pgtype.Timestamptz
	PickupTimestamp_2 pgtype.Timestamptz
}

type CountRacepackPickupRecordsByCounterRow struct {
	CounterID   uuid.UUID
	PickupCount int64
}

func (q *Queries) CountRacepackPickupRecordsByCounter(ctx context.Context, arg CountRacepackPickupRecordsByCounterParams) ([]CountRacepackPickupRecordsByCounterRow, error) {
	rows, err := q.db.Query(ctx, countRacepackPickupRecordsByCounter, arg.EventID, arg.PickupTimestamp, arg.PickupTimestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRacepackPickupRecordsByCounterRow
	for rows.Next() {
		var i CountRacepackPickupRecordsByCounterRow
		if err := rows.Scan(&i.CounterID, &i.PickupCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRacepackPickupRecordsByEvent = `-- name: CountRacepackPickupRecordsByEvent :one
SELECT COUNT(*) FROM racepack_pickup_records
WHERE event_id = $1 AND status = 'PICKED_UP'
`

func (q *Queries) CountRacepackPickupRecordsByEvent(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRacepackPickupRecordsByEvent, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRacepackProblemCasesByEventAndStatus = `-- name: CountRacepackProblemCasesByEventAndStatus :one
SELECT COUNT(*) FROM racepack_problem_cases
WHERE event_id = $1 AND status = $2
`

type CountRacepackProblemCasesByEventAndStatusParams struct {
	EventID uuid.UUID
	Status  string
}

func (q *Queries) CountRacepackProblemCasesByEventAndStatus(ctx context.Context, arg CountRacepackProblemCasesByEventAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRacepackProblemCasesByEventAndStatus, arg.EventID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRacepackCounter = `-- name: CreateRacepackCounter :one
INSERT INTO racepack_counters (organization_id, event_id, name, location, active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, event_id, name, location, active, created_at, updated_at
`

type CreateRacepackCounterParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	Name           string
	Location       pgtype.Text
	Active         bool
}

func (q *Queries) CreateRacepackCounter(ctx context.Context, arg CreateRacepackCounterParams) (RacepackCounter, error) {
	row := q.db.QueryRow(ctx, createRacepackCounter,
		arg.OrganizationID,
		arg.EventID,
		arg.Name,
		arg.Location,
		arg.Active,
	)
	var i RacepackCounter
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.Location,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRacepackPickupRecord = `-- name: CreateRacepackPickupRecord :one
INSERT INTO racepack_pickup_records (
    organization_id, event_id, ticket_id, participant_id, bib_number,
    counter_id, slot_id, staff_id, pickup_method, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, organization_id, event_id, ticket_id, participant_id, bib_number, counter_id, staff_id, pickup_method, pickup_timestamp, notes, status, slot_id
`

type CreateRacepackPickupRecordParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	TicketID       uuid.UUID
	ParticipantID  uuid.UUID
	BibNumber      string
	CounterID      uuid.UUID
	SlotID         *uuid.UUID
	StaffID        uuid.UUID
	PickupMethod   string
	Notes          pgtype.Text
}

func (q *Queries) CreateRacepackPickupRecord(ctx context.Context, arg CreateRacepackPickupRecordParams) (RacepackPickupRecord, error) {
	row := q.db.QueryRow(ctx, createRacepackPickupRecord,
		arg.OrganizationID,
		arg.EventID,
		arg.TicketID,
		arg.ParticipantID,
		arg.BibNumber,
		arg.CounterID,
		arg.SlotID,
		arg.StaffID,
		arg.PickupMethod,
		arg.Notes,
	)
	var i RacepackPickupRecord
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.TicketID,
		&i.ParticipantID,
		&i.BibNumber,
		&i.CounterID,
		&i.StaffID,
		&i.PickupMethod,
		&i.PickupTimestamp,
		&i.Notes,
		&i.Status,
		&i.SlotID,
	)
	return i, err
}

const createRacepackPickupSlot = `-- name: CreateRacepackPickupSlot :one
INSERT INTO racepack_pickup_slots (organization_id, event_id, name, pickup_date, start_time, end_time, capacity)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, event_id, name, pickup_date, start_time, end_time, capacity, reserved_count, active, created_at, updated_at
`

type CreateRacepackPickupSlotParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	Name           string
	PickupDate     pgtype.Date
	StartTime      pgtype.Timestamptz
	EndTime        pgtype.Timestamptz
	Capacity       int32
}

func (q *Queries) CreateRacepackPickupSlot(ctx context.Context, arg CreateRacepackPickupSlotParams) (RacepackPickupSlot, error) {
	row := q.db.QueryRow(ctx, createRacepackPickupSlot,
		arg.OrganizationID,
		arg.EventID,
		arg.Name,
		arg.PickupDate,
		arg.StartTime,
		arg.EndTime,
		arg.Capacity,
	)
	var i RacepackPickupSlot
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.PickupDate,
		&i.StartTime,
		&i.EndTime,
		&i.Capacity,
		&i.ReservedCount,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRacepackProblemCase = `-- name: CreateRacepackProblemCase :one
INSERT INTO racepack_problem_cases (
    organization_id, event_id, ticket_id, participant_id, status, reason, created_by
) VALUES ($1, $2, $3, $4, 'OPEN', $5, $6)
RETURNING id, organization_id, event_id, ticket_id, participant_id, status, reason, resolution, created_by, resolved_by, resolved_at, created_at, updated_at
`

type CreateRacepackProblemCaseParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	TicketID       *uuid.UUID
	ParticipantID  *uuid.UUID
	Reason         string
	CreatedBy      uuid.UUID
}

func (q *Queries) CreateRacepackProblemCase(ctx context.Context, arg CreateRacepackProblemCaseParams) (RacepackProblemCase, error) {
	row := q.db.QueryRow(ctx, createRacepackProblemCase,
		arg.OrganizationID,
		arg.EventID,
		arg.TicketID,
		arg.ParticipantID,
		arg.Reason,
		arg.CreatedBy,
	)
	var i RacepackProblemCase
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.TicketID,
		&i.ParticipantID,
		&i.Status,
		&i.Reason,
		&i.Resolution,
		&i.CreatedBy,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRacepackProxyAuthorization = `-- name: CreateRacepackProxyAuthorization :one
INSERT INTO racepack_proxy_authorizations (
    organization_id, event_id, ticket_id, pickup_record_id,
    proxy_name, proxy_phone, proxy_identity, authorization_document, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, event_id, ticket_id, pickup_record_id, proxy_name, proxy_phone, proxy_identity, authorization_document, created_by, created_at
`

type CreateRacepackProxyAuthorizationParams struct {
	OrganizationID        uuid.UUID
	EventID               uuid.UUID
	TicketID              uuid.UUID
	PickupRecordID        *uuid.UUID
	ProxyName             string
	ProxyPhone            pgtype.Text
	ProxyIdentity         string
	AuthorizationDocument pgtype.Text
	CreatedBy             uuid.UUID
}

func (q *Queries) CreateRacepackProxyAuthorization(ctx context.Context, arg CreateRacepackProxyAuthorizationParams) (RacepackProxyAuthorization, error) {
	row := q.db.QueryRow(ctx, createRacepackProxyAuthorization,
		arg.OrganizationID,
		arg.EventID,
		arg.TicketID,
		arg.PickupRecordID,
		arg.ProxyName,
		arg.ProxyPhone,
		arg.ProxyIdentity,
		arg.AuthorizationDocument,
		arg.CreatedBy,
	)
	var i RacepackProxyAuthorization
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.TicketID,
		&i.PickupRecordID,
		&i.ProxyName,
		&i.ProxyPhone,
		&i.ProxyIdentity,
		&i.AuthorizationDocument,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const decrementRacepackPickupSlotReserved = `-- name: DecrementRacepackPickupSlotReserved :exec
UPDATE racepack_pickup_slots
SET reserved_count = reserved_count - 1, updated_at = now()
WHERE id = $1 AND reserved_count > 0
`

func (q *Queries) DecrementRacepackPickupSlotReserved(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementRacepackPickupSlotReserved, id)
	return err
}

const getEventOrganizationID = `-- name: GetEventOrganizationID :one
SELECT organization_id FROM events WHERE id = $1
`

func (q *Queries) GetEventOrganizationID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getEventOrganizationID, id)
	var organization_id uuid.UUID
	err := row.Scan(&organization_id)
	return organization_id, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, request_hash, response_status, response_body, created_at
FROM idempotency_keys
WHERE key = $1 AND scope = $2
`

type GetIdempotencyKeyParams struct {
	Key   string
	Scope string
}

type GetIdempotencyKeyRow struct {
	Key            string
	RequestHash    string
	ResponseStatus int32
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Key, arg.Scope)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const getRacepackCounterByID = `-- name: GetRacepackCounterByID :one
SELECT id, organization_id, event_id, name, location, active, created_at, updated_at FROM racepack_counters WHERE id = $1
`

func (q *Queries) GetRacepackCounterByID(ctx context.Context, id uuid.UUID) (RacepackCounter, error) {
	row := q.db.QueryRow(ctx, getRacepackCounterByID, id)
	var i RacepackCounter
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.Location,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRacepackPickupRecordByID = `-- name: GetRacepackPickupRecordByID :one
SELECT id, organization_id, event_id, ticket_id, participant_id, bib_number, counter_id, staff_id, pickup_method, pickup_timestamp, notes, status, slot_id FROM racepack_pickup_records WHERE id = $1
`

func (q *Queries) GetRacepackPickupRecordByID(ctx context.Context, id uuid.UUID) (RacepackPickupRecord, error) {
	row := q.db.QueryRow(ctx, getRacepackPickupRecordByID, id)
	var i RacepackPickupRecord
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.TicketID,
		&i.ParticipantID,
		&i.BibNumber,
		&i.CounterID,
		&i.StaffID,
		&i.PickupMethod,
		&i.PickupTimestamp,
		&i.Notes,
		&i.Status,
		&i.SlotID,
	)
	return i, err
}

const getRacepackPickupRecordByTicket = `-- name: GetRacepackPickupRecordByTicket :one
SELECT id, organization_id, event_id, ticket_id, participant_id, bib_number, counter_id, staff_id, pickup_method, pickup_timestamp, notes, status, slot_id FROM racepack_pickup_records
WHERE ticket_id = $1 AND status = 'PICKED_UP'
`

func (q *Queries) GetRacepackPickupRecordByTicket(ctx context.Context, ticketID uuid.UUID) (RacepackPickupRecord, error) {
	row := q.db.QueryRow(ctx, getRacepackPickupRecordByTicket, ticketID)
	var i RacepackPickupRecord
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.TicketID,
		&i.ParticipantID,
		&i.BibNumber,
		&i.CounterID,
		&i.StaffID,
		&i.PickupMethod,
		&i.PickupTimestamp,
		&i.Notes,
		&i.Status,
		&i.SlotID,
	)
	return i, err
}

const getRacepackPickupSlotByID = `-- name: GetRacepackPickupSlotByID :one
SELECT id, organization_id, event_id, name, pickup_date, start_time, end_time, capacity, reserved_count, active, created_at, updated_at FROM racepack_pickup_slots WHERE id = $1
`

func (q *Queries) GetRacepackPickupSlotByID(ctx context.Context, id uuid.UUID) (RacepackPickupSlot, error) {
	row := q.db.QueryRow(ctx, getRacepackPickupSlotByID, id)
	var i RacepackPickupSlot
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.PickupDate,
		&i.StartTime,
		&i.EndTime,
		&i.Capacity,
		&i.ReservedCount,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRacepackProblemCaseByID = `-- name: GetRacepackProblemCaseByID :one
SELECT id, organization_id, event_id, ticket_id, participant_id, status, reason, resolution, created_by, resolved_by, resolved_at, created_at, updated_at FROM racepack_problem_cases WHERE id = $1
`

func (q *Queries) GetRacepackProblemCaseByID(ctx context.Context, id uuid.UUID) (RacepackProblemCase, error) {
	row := q.db.QueryRow(ctx, getRacepackProblemCaseByID, id)
	var i RacepackProblemCase
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.TicketID,
		&i.ParticipantID,
		&i.Status,
		&i.Reason,
		&i.Resolution,
		&i.CreatedBy,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRacepackProxyAuthorizationByID = `-- name: GetRacepackProxyAuthorizationByID :one
SELECT id, organization_id, event_id, ticket_id, pickup_record_id, proxy_name, proxy_phone, proxy_identity, authorization_document, created_by, created_at FROM racepack_proxy_authorizations WHERE id = $1
`

func (q *Queries) GetRacepackProxyAuthorizationByID(ctx context.Context, id uuid.UUID) (RacepackProxyAuthorization, error) {
	row := q.db.QueryRow(ctx, getRacepackProxyAuthorizationByID, id)
	var i RacepackProxyAuthorization
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.TicketID,
		&i.PickupRecordID,
		&i.ProxyName,
		&i.ProxyPhone,
		&i.ProxyIdentity,
		&i.AuthorizationDocument,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserTicketByID = `-- name: GetUserTicketByID :one
SELECT t.id, t.event_id, t.participant_id, t.status, t.bib_number,
       o.status AS order_status
FROM tickets t
JOIN orders o ON o.id = t.order_id
WHERE t.id = $1
`

type GetUserTicketByIDRow struct {
	ID            uuid.UUID
	EventID       uuid.UUID
	ParticipantID uuid.UUID
	Status        string
	BibNumber     pgtype.Text
	OrderStatus   string
}

// Returns ticket + order status in one query for the eligibility path.
func (q *Queries) GetUserTicketByID(ctx context.Context, id uuid.UUID) (GetUserTicketByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserTicketByID, id)
	var i GetUserTicketByIDRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ParticipantID,
		&i.Status,
		&i.BibNumber,
		&i.OrderStatus,
	)
	return i, err
}

const incrementRacepackPickupSlotReserved = `-- name: IncrementRacepackPickupSlotReserved :one
UPDATE racepack_pickup_slots
SET reserved_count = reserved_count + 1, updated_at = now()
WHERE id = $1 AND reserved_count < capacity
RETURNING id, organization_id, event_id, name, pickup_date, start_time, end_time, capacity, reserved_count, active, created_at, updated_at
`

func (q *Queries) IncrementRacepackPickupSlotReserved(ctx context.Context, id uuid.UUID) (RacepackPickupSlot, error) {
	row := q.db.QueryRow(ctx, incrementRacepackPickupSlotReserved, id)
	var i RacepackPickupSlot
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.PickupDate,
		&i.StartTime,
		&i.EndTime,
		&i.Capacity,
		&i.ReservedCount,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (key, scope, request_hash, response_status, response_body)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key, scope) DO NOTHING
RETURNING key, scope, request_hash, response_status, response_body, created_at
`

type InsertIdempotencyKeyParams struct {
	Key            string
	Scope          string
	RequestHash    string
	ResponseStatus int32
	ResponseBody   []byte
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.Key,
		arg.Scope,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Scope,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const listRacepackCountersByEvent = `-- name: ListRacepackCountersByEvent :many
SELECT id, organization_id, event_id, name, location, active, created_at, updated_at FROM racepack_counters WHERE event_id = $1 ORDER BY name ASC
`

func (q *Queries) ListRacepackCountersByEvent(ctx context.Context, eventID uuid.UUID) ([]RacepackCounter, error) {
	rows, err := q.db.Query(ctx, listRacepackCountersByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacepackCounter
	for rows.Next() {
		var i RacepackCounter
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.Name,
			&i.Location,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRacepackPickupRecordsByEvent = `-- name: ListRacepackPickupRecordsByEvent :many
SELECT id, organization_id, event_id, ticket_id, participant_id, bib_number, counter_id, staff_id, pickup_method, pickup_timestamp, notes, status, slot_id FROM racepack_pickup_records
WHERE event_id = $1 AND status = 'PICKED_UP'
ORDER BY pickup_timestamp DESC
LIMIT $2 OFFSET $3
`

type ListRacepackPickupRecordsByEventParams struct {
	EventID uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListRacepackPickupRecordsByEvent(ctx context.Context, arg ListRacepackPickupRecordsByEventParams) ([]RacepackPickupRecord, error) {
	rows, err := q.db.Query(ctx, listRacepackPickupRecordsByEvent, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacepackPickupRecord
	for rows.Next() {
		var i RacepackPickupRecord
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.TicketID,
			&i.ParticipantID,
			&i.BibNumber,
			&i.CounterID,
			&i.StaffID,
			&i.PickupMethod,
			&i.PickupTimestamp,
			&i.Notes,
			&i.Status,
			&i.SlotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRacepackPickupSlotsActiveByEvent = `-- name: ListRacepackPickupSlotsActiveByEvent :many
SELECT id, organization_id, event_id, name, pickup_date, start_time, end_time, capacity, reserved_count, active, created_at, updated_at FROM racepack_pickup_slots
WHERE event_id = $1 AND active = true
ORDER BY pickup_date ASC, start_time ASC
`

func (q *Queries) ListRacepackPickupSlotsActiveByEvent(ctx context.Context, eventID uuid.UUID) ([]RacepackPickupSlot, error) {
	rows, err := q.db.Query(ctx, listRacepackPickupSlotsActiveByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacepackPickupSlot
	for rows.Next() {
		var i RacepackPickupSlot
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.Name,
			&i.PickupDate,
			&i.StartTime,
			&i.EndTime,
			&i.Capacity,
			&i.ReservedCount,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRacepackPickupSlotsByEvent = `-- name: ListRacepackPickupSlotsByEvent :many
SELECT id, organization_id, event_id, name, pickup_date, start_time, end_time, capacity, reserved_count, active, created_at, updated_at FROM racepack_pickup_slots
WHERE event_id = $1
ORDER BY pickup_date ASC, start_time ASC
`

func (q *Queries) ListRacepackPickupSlotsByEvent(ctx context.Context, eventID uuid.UUID) ([]RacepackPickupSlot, error) {
	rows, err := q.db.Query(ctx, listRacepackPickupSlotsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacepackPickupSlot
	for rows.Next() {
		var i RacepackPickupSlot
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.Name,
			&i.PickupDate,
			&i.StartTime,
			&i.EndTime,
			&i.Capacity,
			&i.ReservedCount,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRacepackProblemCasesByEvent = `-- name: ListRacepackProblemCasesByEvent :many
SELECT id, organization_id, event_id, ticket_id, participant_id, status, reason, resolution, created_by, resolved_by, resolved_at, created_at, updated_at FROM racepack_problem_cases
WHERE event_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRacepackProblemCasesByEventParams struct {
	EventID uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListRacepackProblemCasesByEvent(ctx context.Context, arg ListRacepackProblemCasesByEventParams) ([]RacepackProblemCase, error) {
	rows, err := q.db.Query(ctx, listRacepackProblemCasesByEvent, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacepackProblemCase
	for rows.Next() {
		var i RacepackProblemCase
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.TicketID,
			&i.ParticipantID,
			&i.Status,
			&i.Reason,
			&i.Resolution,
			&i.CreatedBy,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRacepackProxyAuthorizationsByTicket = `-- name: ListRacepackProxyAuthorizationsByTicket :many
SELECT id, organization_id, event_id, ticket_id, pickup_record_id, proxy_name, proxy_phone, proxy_identity, authorization_document, created_by, created_at FROM racepack_proxy_authorizations
WHERE ticket_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRacepackProxyAuthorizationsByTicket(ctx context.Context, ticketID uuid.UUID) ([]RacepackProxyAuthorization, error) {
	rows, err := q.db.Query(ctx, listRacepackProxyAuthorizationsByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacepackProxyAuthorization
	for rows.Next() {
		var i RacepackProxyAuthorization
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.TicketID,
			&i.PickupRecordID,
			&i.ProxyName,
			&i.ProxyPhone,
			&i.ProxyIdentity,
			&i.AuthorizationDocument,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTicketForUpdate = `-- name: LockTicketForUpdate :one
SELECT id, organization_id, event_id, category_id, order_id, participant_id, ticket_number, status, holder_name, holder_email, event_title, category_name, qr_version, issued_at, used_at, created_at, updated_at, bib_number, bib_assigned_at, bib_assigned_by, bib_assignment_method FROM tickets WHERE id = $1 FOR UPDATE
`

// Acquires a row-level lock on the ticket row inside a transaction.
// Used to close the TOCTOU window between eligibility check and pickup insert.
func (q *Queries) LockTicketForUpdate(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, lockTicketForUpdate, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.OrderID,
		&i.ParticipantID,
		&i.TicketNumber,
		&i.Status,
		&i.HolderName,
		&i.HolderEmail,
		&i.EventTitle,
		&i.CategoryName,
		&i.QrVersion,
		&i.IssuedAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BibNumber,
		&i.BibAssignedAt,
		&i.BibAssignedBy,
		&i.BibAssignmentMethod,
	)
	return i, err
}

const setRacepackCounterActive = `-- name: SetRacepackCounterActive :one
UPDATE racepack_counters
SET active = $2, updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, name, location, active, created_at, updated_at
`

type SetRacepackCounterActiveParams struct {
	ID     uuid.UUID
	Active bool
}

func (q *Queries) SetRacepackCounterActive(ctx context.Context, arg SetRacepackCounterActiveParams) (RacepackCounter, error) {
	row := q.db.QueryRow(ctx, setRacepackCounterActive, arg.ID, arg.Active)
	var i RacepackCounter
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.Location,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRacepackCounter = `-- name: UpdateRacepackCounter :one
UPDATE racepack_counters
SET name = $2, location = $3, active = $4, updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, name, location, active, created_at, updated_at
`

type UpdateRacepackCounterParams struct {
	ID       uuid.UUID
	Name     string
	Location pgtype.Text
	Active   bool
}

func (q *Queries) UpdateRacepackCounter(ctx context.Context, arg UpdateRacepackCounterParams) (RacepackCounter, error) {
	row := q.db.QueryRow(ctx, updateRacepackCounter,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.Active,
	)
	var i RacepackCounter
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.Location,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRacepackPickupSlot = `-- name: UpdateRacepackPickupSlot :one
UPDATE racepack_pickup_slots
SET name = $2, pickup_date = $3, start_time = $4, end_time = $5,
    capacity = $6, active = $7, updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, name, pickup_date, start_time, end_time, capacity, reserved_count, active, created_at, updated_at
`

type UpdateRacepackPickupSlotParams struct {
	ID         uuid.UUID
	Name       string
	PickupDate pgtype.Date
	StartTime  pgtype.Timestamptz
	EndTime    pgtype.Timestamptz
	Capacity   int32
	Active     bool
}

func (q *Queries) UpdateRacepackPickupSlot(ctx context.Context, arg UpdateRacepackPickupSlotParams) (RacepackPickupSlot, error) {
	row := q.db.QueryRow(ctx, updateRacepackPickupSlot,
		arg.ID,
		arg.Name,
		arg.PickupDate,
		arg.StartTime,
		arg.EndTime,
		arg.Capacity,
		arg.Active,
	)
	var i RacepackPickupSlot
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Name,
		&i.PickupDate,
		&i.StartTime,
		&i.EndTime,
		&i.Capacity,
		&i.ReservedCount,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRacepackProblemCaseStatus = `-- name: UpdateRacepackProblemCaseStatus :one
UPDATE racepack_problem_cases
SET status = $2,
    resolution = CASE WHEN $2 IN ('RESOLVED','ESCALATED') THEN $3 ELSE resolution END,
    resolved_by = CASE WHEN $2 IN ('RESOLVED','ESCALATED') THEN $4 ELSE resolved_by END,
    resolved_at = CASE WHEN $2 IN ('RESOLVED','ESCALATED') THEN now() ELSE resolved_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, ticket_id, participant_id, status, reason, resolution, created_by, resolved_by, resolved_at, created_at, updated_at
`

type UpdateRacepackProblemCaseStatusParams struct {
	ID         uuid.UUID
	Status     string
	Resolution pgtype.Text
	ResolvedBy *uuid.UUID
}

func (q *Queries) UpdateRacepackProblemCaseStatus(ctx context.Context, arg UpdateRacepackProblemCaseStatusParams) (RacepackProblemCase, error) {
	row := q.db.QueryRow(ctx, updateRacepackProblemCaseStatus,
		arg.ID,
		arg.Status,
		arg.Resolution,
		arg.ResolvedBy,
	)
	var i RacepackProblemCase
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.TicketID,
		&i.ParticipantID,
		&i.Status,
		&i.Reason,
		&i.Resolution,
		&i.CreatedBy,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
