// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCategoryRegistrationSettings = `-- name: GetCategoryRegistrationSettings :one
SELECT category_id, registration_mode, override_enabled, created_at, updated_at FROM category_registration_settings WHERE category_id = $1
`

func (q *Queries) GetCategoryRegistrationSettings(ctx context.Context, categoryID uuid.UUID) (CategoryRegistrationSetting, error) {
	row := q.db.QueryRow(ctx, getCategoryRegistrationSettings, categoryID)
	var i CategoryRegistrationSetting
	err := row.Scan(
		&i.CategoryID,
		&i.RegistrationMode,
		&i.OverrideEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventRegistrationSettings = `-- name: GetEventRegistrationSettings :one
SELECT event_id, default_mode, queue_enabled, ballot_enabled, priority_enabled, waitlist_enabled, created_at, updated_at FROM event_registration_settings WHERE event_id = $1
`

func (q *Queries) GetEventRegistrationSettings(ctx context.Context, eventID uuid.UUID) (EventRegistrationSetting, error) {
	row := q.db.QueryRow(ctx, getEventRegistrationSettings, eventID)
	var i EventRegistrationSetting
	err := row.Scan(
		&i.EventID,
		&i.DefaultMode,
		&i.QueueEnabled,
		&i.BallotEnabled,
		&i.PriorityEnabled,
		&i.WaitlistEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoryRegistrationSettingsByEvent = `-- name: ListCategoryRegistrationSettingsByEvent :many
SELECT crs.category_id, crs.registration_mode, crs.override_enabled, crs.created_at, crs.updated_at FROM category_registration_settings crs
JOIN event_categories ec ON ec.id = crs.category_id
WHERE ec.event_id = $1
`

func (q *Queries) ListCategoryRegistrationSettingsByEvent(ctx context.Context, eventID uuid.UUID) ([]CategoryRegistrationSetting, error) {
	rows, err := q.db.Query(ctx, listCategoryRegistrationSettingsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryRegistrationSetting
	for rows.Next() {
		var i CategoryRegistrationSetting
		if err := rows.Scan(
			&i.CategoryID,
			&i.RegistrationMode,
			&i.OverrideEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCategoryRegistrationSettings = `-- name: UpsertCategoryRegistrationSettings :one
INSERT INTO category_registration_settings (category_id, registration_mode, override_enabled)
VALUES ($1,$2,$3)
ON CONFLICT (category_id) DO UPDATE SET
    registration_mode = EXCLUDED.registration_mode,
    override_enabled = EXCLUDED.override_enabled,
    updated_at = now()
RETURNING category_id, registration_mode, override_enabled, created_at, updated_at
`

type UpsertCategoryRegistrationSettingsParams struct {
	CategoryID       uuid.UUID
	RegistrationMode pgtype.Text
	OverrideEnabled  bool
}

func (q *Queries) UpsertCategoryRegistrationSettings(ctx context.Context, arg UpsertCategoryRegistrationSettingsParams) (CategoryRegistrationSetting, error) {
	row := q.db.QueryRow(ctx, upsertCategoryRegistrationSettings, arg.CategoryID, arg.RegistrationMode, arg.OverrideEnabled)
	var i CategoryRegistrationSetting
	err := row.Scan(
		&i.CategoryID,
		&i.RegistrationMode,
		&i.OverrideEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEventRegistrationSettings = `-- name: UpsertEventRegistrationSettings :one
INSERT INTO event_registration_settings (event_id, default_mode, queue_enabled, ballot_enabled, priority_enabled, waitlist_enabled)
VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (event_id) DO UPDATE SET
    default_mode = EXCLUDED.default_mode,
    queue_enabled = EXCLUDED.queue_enabled,
    ballot_enabled = EXCLUDED.ballot_enabled,
    priority_enabled = EXCLUDED.priority_enabled,
    waitlist_enabled = EXCLUDED.waitlist_enabled,
    updated_at = now()
RETURNING event_id, default_mode, queue_enabled, ballot_enabled, priority_enabled, waitlist_enabled, created_at, updated_at
`

type UpsertEventRegistrationSettingsParams struct {
	EventID         uuid.UUID
	DefaultMode     string
	QueueEnabled    bool
	BallotEnabled   bool
	PriorityEnabled bool
	WaitlistEnabled bool
}

func (q *Queries) UpsertEventRegistrationSettings(ctx context.Context, arg UpsertEventRegistrationSettingsParams) (EventRegistrationSetting, error) {
	row := q.db.QueryRow(ctx, upsertEventRegistrationSettings,
		arg.EventID,
		arg.DefaultMode,
		arg.QueueEnabled,
		arg.BallotEnabled,
		arg.PriorityEnabled,
		arg.WaitlistEnabled,
	)
	var i EventRegistrationSetting
	err := row.Scan(
		&i.EventID,
		&i.DefaultMode,
		&i.QueueEnabled,
		&i.BallotEnabled,
		&i.PriorityEnabled,
		&i.WaitlistEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
