// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reporting.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ballotReportRows = `-- name: BallotReportRows :many
SELECT
    be.status, be.applied_at, be.payment_deadline, be.converted_at,
    be.promoted_round,
    u.full_name AS participant_name, u.email AS participant_email
FROM ballot_entries be
JOIN users u ON u.id = be.participant_id
WHERE be.organization_id = $1
  AND ($2::uuid IS NULL OR be.event_id = $2)
ORDER BY be.applied_at ASC
`

type BallotReportRowsParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type BallotReportRowsRow struct {
	Status           string
	AppliedAt        pgtype.Timestamptz
	PaymentDeadline  pgtype.Timestamptz
	ConvertedAt      pgtype.Timestamptz
	PromotedRound    int32
	ParticipantName  string
	ParticipantEmail string
}

func (q *Queries) BallotReportRows(ctx context.Context, arg BallotReportRowsParams) ([]BallotReportRowsRow, error) {
	rows, err := q.db.Query(ctx, ballotReportRows, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BallotReportRowsRow
	for rows.Next() {
		var i BallotReportRowsRow
		if err := rows.Scan(
			&i.Status,
			&i.AppliedAt,
			&i.PaymentDeadline,
			&i.ConvertedAt,
			&i.PromotedRound,
			&i.ParticipantName,
			&i.ParticipantEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ballotReportSummary = `-- name: BallotReportSummary :one

SELECT
    COUNT(*)                                           AS total_entries,
    COUNT(*) FILTER (WHERE status = 'APPLIED')         AS applied,
    COUNT(*) FILTER (WHERE status = 'WINNER')          AS winners,
    COUNT(*) FILTER (WHERE status = 'WAITLISTED')      AS waitlisted,
    COUNT(*) FILTER (WHERE status = 'NOT_SELECTED')    AS not_selected,
    COUNT(*) FILTER (WHERE status = 'CONVERTED')       AS converted,
    COUNT(*) FILTER (WHERE status = 'LAPSED')          AS lapsed
FROM ballot_entries
WHERE organization_id = $1
  AND ($2::uuid IS NULL OR event_id = $2)
`

type BallotReportSummaryParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type BallotReportSummaryRow struct {
	TotalEntries int64
	Applied      int64
	Winners      int64
	Waitlisted   int64
	NotSelected  int64
	Converted    int64
	Lapsed       int64
}

// ==========================================================================
// Ballot report
// ==========================================================================
func (q *Queries) BallotReportSummary(ctx context.Context, arg BallotReportSummaryParams) (BallotReportSummaryRow, error) {
	row := q.db.QueryRow(ctx, ballotReportSummary, arg.OrganizationID, arg.EventID)
	var i BallotReportSummaryRow
	err := row.Scan(
		&i.TotalEntries,
		&i.Applied,
		&i.Winners,
		&i.Waitlisted,
		&i.NotSelected,
		&i.Converted,
		&i.Lapsed,
	)
	return i, err
}

const claimPendingExportJob = `-- name: ClaimPendingExportJob :one
UPDATE export_jobs
SET status = 'PROCESSING', started_at = now(), updated_at = now()
WHERE id = (
    SELECT id FROM export_jobs
    WHERE status = 'PENDING'
    ORDER BY created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, organization_id, event_id, requested_by, report_type, format, params, status, row_count, file_key, file_url, error, started_at, completed_at, created_at, updated_at
`

func (q *Queries) ClaimPendingExportJob(ctx context.Context) (ExportJob, error) {
	row := q.db.QueryRow(ctx, claimPendingExportJob)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.RequestedBy,
		&i.ReportType,
		&i.Format,
		&i.Params,
		&i.Status,
		&i.RowCount,
		&i.FileKey,
		&i.FileUrl,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const couponReportRows = `-- name: CouponReportRows :many
SELECT
    ac.code_type, ac.is_single_use, ac.max_uses, ac.use_count,
    ac.valid_from, ac.valid_until, ac.created_at
FROM access_codes ac
WHERE ac.organization_id = $1
  AND ($2::uuid IS NULL OR ac.event_id = $2)
ORDER BY ac.created_at ASC
`

type CouponReportRowsParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type CouponReportRowsRow struct {
	CodeType    string
	IsSingleUse bool
	MaxUses     int32
	UseCount    int32
	ValidFrom   pgtype.Timestamptz
	ValidUntil  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CouponReportRows(ctx context.Context, arg CouponReportRowsParams) ([]CouponReportRowsRow, error) {
	rows, err := q.db.Query(ctx, couponReportRows, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponReportRowsRow
	for rows.Next() {
		var i CouponReportRowsRow
		if err := rows.Scan(
			&i.CodeType,
			&i.IsSingleUse,
			&i.MaxUses,
			&i.UseCount,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const couponReportSummary = `-- name: CouponReportSummary :many

SELECT
    ac.code_type,
    COUNT(*)                    AS total_codes,
    COALESCE(SUM(ac.max_uses), 0)::bigint  AS total_capacity,
    COALESCE(SUM(ac.use_count), 0)::bigint AS total_used
FROM access_codes ac
WHERE ac.organization_id = $1
  AND ($2::uuid IS NULL OR ac.event_id = $2)
GROUP BY ac.code_type
ORDER BY ac.code_type
`

type CouponReportSummaryParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type CouponReportSummaryRow struct {
	CodeType      string
	TotalCodes    int64
	TotalCapacity int64
	TotalUsed     int64
}

// ==========================================================================
// Coupon report (access codes)
// ==========================================================================
func (q *Queries) CouponReportSummary(ctx context.Context, arg CouponReportSummaryParams) ([]CouponReportSummaryRow, error) {
	rows, err := q.db.Query(ctx, couponReportSummary, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponReportSummaryRow
	for rows.Next() {
		var i CouponReportSummaryRow
		if err := rows.Scan(
			&i.CodeType,
			&i.TotalCodes,
			&i.TotalCapacity,
			&i.TotalUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createExportJob = `-- name: CreateExportJob :one


INSERT INTO export_jobs (organization_id, event_id, requested_by, report_type, format, params)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, event_id, requested_by, report_type, format, params, status, row_count, file_key, file_url, error, started_at, completed_at, created_at, updated_at
`

type CreateExportJobParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
	RequestedBy    uuid.UUID
	ReportType     string
	Format         string
	Params         []byte
}

// Phase 16 — Reporting & Export.
// Export-job lifecycle queries plus aggregate + row-level report queries.
// Every report is org-scoped; event_id is an optional narrowing filter
// (NULL param = all events in the org).
// ==========================================================================
// Export jobs
// ==========================================================================
func (q *Queries) CreateExportJob(ctx context.Context, arg CreateExportJobParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, createExportJob,
		arg.OrganizationID,
		arg.EventID,
		arg.RequestedBy,
		arg.ReportType,
		arg.Format,
		arg.Params,
	)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.RequestedBy,
		&i.ReportType,
		&i.Format,
		&i.Params,
		&i.Status,
		&i.RowCount,
		&i.FileKey,
		&i.FileUrl,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExportJob = `-- name: GetExportJob :one
SELECT id, organization_id, event_id, requested_by, report_type, format, params, status, row_count, file_key, file_url, error, started_at, completed_at, created_at, updated_at FROM export_jobs WHERE id = $1 AND organization_id = $2
`

type GetExportJobParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetExportJob(ctx context.Context, arg GetExportJobParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, getExportJob, arg.ID, arg.OrganizationID)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.RequestedBy,
		&i.ReportType,
		&i.Format,
		&i.Params,
		&i.Status,
		&i.RowCount,
		&i.FileKey,
		&i.FileUrl,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExportJobsByOrg = `-- name: ListExportJobsByOrg :many
SELECT id, organization_id, event_id, requested_by, report_type, format, params, status, row_count, file_key, file_url, error, started_at, completed_at, created_at, updated_at FROM export_jobs
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListExportJobsByOrgParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListExportJobsByOrg(ctx context.Context, arg ListExportJobsByOrgParams) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listExportJobsByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportJob
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.RequestedBy,
			&i.ReportType,
			&i.Format,
			&i.Params,
			&i.Status,
			&i.RowCount,
			&i.FileKey,
			&i.FileUrl,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExportJobFailed = `-- name: MarkExportJobFailed :one
UPDATE export_jobs
SET status = 'FAILED', error = $2, completed_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, requested_by, report_type, format, params, status, row_count, file_key, file_url, error, started_at, completed_at, created_at, updated_at
`

type MarkExportJobFailedParams struct {
	ID    uuid.UUID
	Error pgtype.Text
}

func (q *Queries) MarkExportJobFailed(ctx context.Context, arg MarkExportJobFailedParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, markExportJobFailed, arg.ID, arg.Error)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.RequestedBy,
		&i.ReportType,
		&i.Format,
		&i.Params,
		&i.Status,
		&i.RowCount,
		&i.FileKey,
		&i.FileUrl,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markExportJobReady = `-- name: MarkExportJobReady :one
UPDATE export_jobs
SET status = 'READY', row_count = $2, file_key = $3, file_url = $4,
    completed_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, organization_id, event_id, requested_by, report_type, format, params, status, row_count, file_key, file_url, error, started_at, completed_at, created_at, updated_at
`

type MarkExportJobReadyParams struct {
	ID       uuid.UUID
	RowCount pgtype.Int4
	FileKey  pgtype.Text
	FileUrl  pgtype.Text
}

func (q *Queries) MarkExportJobReady(ctx context.Context, arg MarkExportJobReadyParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, markExportJobReady,
		arg.ID,
		arg.RowCount,
		arg.FileKey,
		arg.FileUrl,
	)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.RequestedBy,
		&i.ReportType,
		&i.Format,
		&i.Params,
		&i.Status,
		&i.RowCount,
		&i.FileKey,
		&i.FileUrl,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const participantReportRows = `-- name: ParticipantReportRows :many
SELECT
    t.ticket_number, t.holder_name, t.holder_email, t.event_title,
    t.category_name, t.status, t.bib_number, t.issued_at, t.used_at
FROM tickets t
WHERE t.organization_id = $1
  AND ($2::uuid IS NULL OR t.event_id = $2)
ORDER BY t.issued_at ASC
`

type ParticipantReportRowsParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type ParticipantReportRowsRow struct {
	TicketNumber string
	HolderName   string
	HolderEmail  string
	EventTitle   string
	CategoryName string
	Status       string
	BibNumber    pgtype.Text
	IssuedAt     pgtype.Timestamptz
	UsedAt       pgtype.Timestamptz
}

func (q *Queries) ParticipantReportRows(ctx context.Context, arg ParticipantReportRowsParams) ([]ParticipantReportRowsRow, error) {
	rows, err := q.db.Query(ctx, participantReportRows, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParticipantReportRowsRow
	for rows.Next() {
		var i ParticipantReportRowsRow
		if err := rows.Scan(
			&i.TicketNumber,
			&i.HolderName,
			&i.HolderEmail,
			&i.EventTitle,
			&i.CategoryName,
			&i.Status,
			&i.BibNumber,
			&i.IssuedAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const participantReportSummary = `-- name: ParticipantReportSummary :one

SELECT
    COUNT(*)                                             AS total_tickets,
    COUNT(*) FILTER (WHERE t.status = 'VALID')           AS valid_tickets,
    COUNT(*) FILTER (WHERE t.status = 'USED')            AS used_tickets,
    COUNT(*) FILTER (WHERE t.status = 'CANCELLED')       AS cancelled_tickets,
    COUNT(DISTINCT t.participant_id)                     AS unique_participants
FROM tickets t
WHERE t.organization_id = $1
  AND ($2::uuid IS NULL OR t.event_id = $2)
`

type ParticipantReportSummaryParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type ParticipantReportSummaryRow struct {
	TotalTickets       int64
	ValidTickets       int64
	UsedTickets        int64
	CancelledTickets   int64
	UniqueParticipants int64
}

// ==========================================================================
// Participant report
// ==========================================================================
func (q *Queries) ParticipantReportSummary(ctx context.Context, arg ParticipantReportSummaryParams) (ParticipantReportSummaryRow, error) {
	row := q.db.QueryRow(ctx, participantReportSummary, arg.OrganizationID, arg.EventID)
	var i ParticipantReportSummaryRow
	err := row.Scan(
		&i.TotalTickets,
		&i.ValidTickets,
		&i.UsedTickets,
		&i.CancelledTickets,
		&i.UniqueParticipants,
	)
	return i, err
}

const paymentReportRows = `-- name: PaymentReportRows :many
SELECT
    p.merchant_reference, p.gateway, p.method, p.channel, p.status,
    p.amount, p.currency, p.gateway_reference, p.paid_at, p.created_at
FROM payments p
WHERE p.organization_id = $1
  AND ($2::uuid IS NULL OR p.event_id = $2)
ORDER BY p.created_at ASC
`

type PaymentReportRowsParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type PaymentReportRowsRow struct {
	MerchantReference string
	Gateway           string
	Method            string
	Channel           pgtype.Text
	Status            string
	Amount            int64
	Currency          string
	GatewayReference  pgtype.Text
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) PaymentReportRows(ctx context.Context, arg PaymentReportRowsParams) ([]PaymentReportRowsRow, error) {
	rows, err := q.db.Query(ctx, paymentReportRows, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentReportRowsRow
	for rows.Next() {
		var i PaymentReportRowsRow
		if err := rows.Scan(
			&i.MerchantReference,
			&i.Gateway,
			&i.Method,
			&i.Channel,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.GatewayReference,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentReportSummary = `-- name: PaymentReportSummary :many

SELECT
    p.gateway, p.method, p.status,
    COUNT(*)                        AS count,
    COALESCE(SUM(p.amount), 0)::bigint AS total_amount
FROM payments p
WHERE p.organization_id = $1
  AND ($2::uuid IS NULL OR p.event_id = $2)
GROUP BY p.gateway, p.method, p.status
ORDER BY p.gateway, p.method, p.status
`

type PaymentReportSummaryParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type PaymentReportSummaryRow struct {
	Gateway     string
	Method      string
	Status      string
	Count       int64
	TotalAmount int64
}

// ==========================================================================
// Payment report
// ==========================================================================
func (q *Queries) PaymentReportSummary(ctx context.Context, arg PaymentReportSummaryParams) ([]PaymentReportSummaryRow, error) {
	rows, err := q.db.Query(ctx, paymentReportSummary, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentReportSummaryRow
	for rows.Next() {
		var i PaymentReportSummaryRow
		if err := rows.Scan(
			&i.Gateway,
			&i.Method,
			&i.Status,
			&i.Count,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformRevenueByOrg = `-- name: PlatformRevenueByOrg :many

SELECT
    o.organization_id,
    org.name AS organization_name,
    COUNT(*) FILTER (WHERE o.status = 'PAID')          AS paid_orders,
    COALESCE(SUM(o.total) FILTER (WHERE o.status = 'PAID'), 0)::bigint AS gross_revenue
FROM orders o
JOIN organizations org ON org.id = o.organization_id
GROUP BY o.organization_id, org.name
ORDER BY gross_revenue DESC
`

type PlatformRevenueByOrgRow struct {
	OrganizationID   uuid.UUID
	OrganizationName string
	PaidOrders       int64
	GrossRevenue     int64
}

// ==========================================================================
// Super-admin cross-org aggregate
// ==========================================================================
func (q *Queries) PlatformRevenueByOrg(ctx context.Context) ([]PlatformRevenueByOrgRow, error) {
	rows, err := q.db.Query(ctx, platformRevenueByOrg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformRevenueByOrgRow
	for rows.Next() {
		var i PlatformRevenueByOrgRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.OrganizationName,
			&i.PaidOrders,
			&i.GrossRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueReportRows = `-- name: QueueReportRows :many
SELECT
    qt.pool, qt.status, qt.score, qt.joined_at, qt.allowed_at,
    qt.completed_at, qt.expired_at,
    u.full_name AS participant_name, u.email AS participant_email
FROM queue_tokens qt
JOIN users u ON u.id = qt.participant_id
WHERE qt.organization_id = $1
  AND ($2::uuid IS NULL OR qt.event_id = $2)
ORDER BY qt.joined_at ASC
`

type QueueReportRowsParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type QueueReportRowsRow struct {
	Pool             string
	Status           string
	Score            int64
	JoinedAt         pgtype.Timestamptz
	AllowedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	ExpiredAt        pgtype.Timestamptz
	ParticipantName  string
	ParticipantEmail string
}

func (q *Queries) QueueReportRows(ctx context.Context, arg QueueReportRowsParams) ([]QueueReportRowsRow, error) {
	rows, err := q.db.Query(ctx, queueReportRows, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueReportRowsRow
	for rows.Next() {
		var i QueueReportRowsRow
		if err := rows.Scan(
			&i.Pool,
			&i.Status,
			&i.Score,
			&i.JoinedAt,
			&i.AllowedAt,
			&i.CompletedAt,
			&i.ExpiredAt,
			&i.ParticipantName,
			&i.ParticipantEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueReportSummary = `-- name: QueueReportSummary :one

SELECT
    COUNT(*)                                        AS total_tokens,
    COUNT(*) FILTER (WHERE status = 'WAITING')      AS waiting,
    COUNT(*) FILTER (WHERE status = 'ALLOWED')      AS allowed,
    COUNT(*) FILTER (WHERE status = 'COMPLETED')    AS completed,
    COUNT(*) FILTER (WHERE status = 'EXPIRED')      AS expired,
    COUNT(*) FILTER (WHERE status = 'BLOCKED')      AS blocked
FROM queue_tokens
WHERE organization_id = $1
  AND ($2::uuid IS NULL OR event_id = $2)
`

type QueueReportSummaryParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type QueueReportSummaryRow struct {
	TotalTokens int64
	Waiting     int64
	Allowed     int64
	Completed   int64
	Expired     int64
	Blocked     int64
}

// ==========================================================================
// Queue report
// ==========================================================================
func (q *Queries) QueueReportSummary(ctx context.Context, arg QueueReportSummaryParams) (QueueReportSummaryRow, error) {
	row := q.db.QueryRow(ctx, queueReportSummary, arg.OrganizationID, arg.EventID)
	var i QueueReportSummaryRow
	err := row.Scan(
		&i.TotalTokens,
		&i.Waiting,
		&i.Allowed,
		&i.Completed,
		&i.Expired,
		&i.Blocked,
	)
	return i, err
}

const racepackReportRows = `-- name: RacepackReportRows :many
SELECT
    rpr.bib_number, rpr.pickup_method, rpr.pickup_timestamp, rpr.notes,
    u.full_name AS participant_name, u.email AS participant_email,
    s.full_name AS staff_name
FROM racepack_pickup_records rpr
JOIN users u ON u.id = rpr.participant_id
JOIN users s ON s.id = rpr.staff_id
WHERE rpr.organization_id = $1
  AND rpr.status = 'PICKED_UP'
  AND ($2::uuid IS NULL OR rpr.event_id = $2)
ORDER BY rpr.pickup_timestamp ASC
`

type RacepackReportRowsParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type RacepackReportRowsRow struct {
	BibNumber        string
	PickupMethod     string
	PickupTimestamp  pgtype.Timestamptz
	Notes            pgtype.Text
	ParticipantName  string
	ParticipantEmail string
	StaffName        string
}

func (q *Queries) RacepackReportRows(ctx context.Context, arg RacepackReportRowsParams) ([]RacepackReportRowsRow, error) {
	rows, err := q.db.Query(ctx, racepackReportRows, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacepackReportRowsRow
	for rows.Next() {
		var i RacepackReportRowsRow
		if err := rows.Scan(
			&i.BibNumber,
			&i.PickupMethod,
			&i.PickupTimestamp,
			&i.Notes,
			&i.ParticipantName,
			&i.ParticipantEmail,
			&i.StaffName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const racepackReportSummary = `-- name: RacepackReportSummary :one

SELECT
    COUNT(*)                                              AS total_pickups,
    COUNT(*) FILTER (WHERE pickup_method = 'SELF')        AS self_pickups,
    COUNT(*) FILTER (WHERE pickup_method = 'PROXY')       AS proxy_pickups,
    COUNT(*) FILTER (WHERE pickup_method = 'MANUAL_OVERRIDE') AS manual_pickups
FROM racepack_pickup_records
WHERE organization_id = $1
  AND status = 'PICKED_UP'
  AND ($2::uuid IS NULL OR event_id = $2)
`

type RacepackReportSummaryParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type RacepackReportSummaryRow struct {
	TotalPickups  int64
	SelfPickups   int64
	ProxyPickups  int64
	ManualPickups int64
}

// ==========================================================================
// Racepack report
// ==========================================================================
func (q *Queries) RacepackReportSummary(ctx context.Context, arg RacepackReportSummaryParams) (RacepackReportSummaryRow, error) {
	row := q.db.QueryRow(ctx, racepackReportSummary, arg.OrganizationID, arg.EventID)
	var i RacepackReportSummaryRow
	err := row.Scan(
		&i.TotalPickups,
		&i.SelfPickups,
		&i.ProxyPickups,
		&i.ManualPickups,
	)
	return i, err
}

const revenueReportRows = `-- name: RevenueReportRows :many
SELECT
    date_trunc('day', o.updated_at)::date AS day,
    COUNT(*)                              AS paid_orders,
    COALESCE(SUM(o.total), 0)::bigint     AS gross_revenue,
    COALESCE(SUM(o.discount), 0)::bigint  AS total_discount
FROM orders o
WHERE o.organization_id = $1
  AND o.status = 'PAID'
  AND ($2::uuid IS NULL OR o.event_id = $2)
GROUP BY date_trunc('day', o.updated_at)
ORDER BY day ASC
`

type RevenueReportRowsParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type RevenueReportRowsRow struct {
	Day           pgtype.Date
	PaidOrders    int64
	GrossRevenue  int64
	TotalDiscount int64
}

func (q *Queries) RevenueReportRows(ctx context.Context, arg RevenueReportRowsParams) ([]RevenueReportRowsRow, error) {
	rows, err := q.db.Query(ctx, revenueReportRows, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenueReportRowsRow
	for rows.Next() {
		var i RevenueReportRowsRow
		if err := rows.Scan(
			&i.Day,
			&i.PaidOrders,
			&i.GrossRevenue,
			&i.TotalDiscount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueReportSummary = `-- name: RevenueReportSummary :one

SELECT
    COALESCE(SUM(o.total), 0)::bigint     AS gross_revenue,
    COALESCE(SUM(o.discount), 0)::bigint  AS total_discount,
    COALESCE(SUM(o.fee), 0)::bigint       AS total_fee,
    COUNT(*)                              AS paid_orders,
    COALESCE(AVG(o.total), 0)::bigint     AS avg_order_value
FROM orders o
WHERE o.organization_id = $1
  AND o.status = 'PAID'
  AND ($2::uuid IS NULL OR o.event_id = $2)
`

type RevenueReportSummaryParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type RevenueReportSummaryRow struct {
	GrossRevenue  int64
	TotalDiscount int64
	TotalFee      int64
	PaidOrders    int64
	AvgOrderValue int64
}

// ==========================================================================
// Revenue report (paid orders, daily buckets)
// ==========================================================================
func (q *Queries) RevenueReportSummary(ctx context.Context, arg RevenueReportSummaryParams) (RevenueReportSummaryRow, error) {
	row := q.db.QueryRow(ctx, revenueReportSummary, arg.OrganizationID, arg.EventID)
	var i RevenueReportSummaryRow
	err := row.Scan(
		&i.GrossRevenue,
		&i.TotalDiscount,
		&i.TotalFee,
		&i.PaidOrders,
		&i.AvgOrderValue,
	)
	return i, err
}

const salesReportRows = `-- name: SalesReportRows :many
SELECT
    o.order_number, o.status, o.subtotal, o.fee, o.discount, o.total,
    u.full_name AS participant_name, u.email AS participant_email,
    o.created_at
FROM orders o
JOIN users u ON u.id = o.participant_id
WHERE o.organization_id = $1
  AND ($2::uuid IS NULL OR o.event_id = $2)
ORDER BY o.created_at ASC
`

type SalesReportRowsParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type SalesReportRowsRow struct {
	OrderNumber      string
	Status           string
	Subtotal         int64
	Fee              int64
	Discount         int64
	Total            int64
	ParticipantName  string
	ParticipantEmail string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) SalesReportRows(ctx context.Context, arg SalesReportRowsParams) ([]SalesReportRowsRow, error) {
	rows, err := q.db.Query(ctx, salesReportRows, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesReportRowsRow
	for rows.Next() {
		var i SalesReportRowsRow
		if err := rows.Scan(
			&i.OrderNumber,
			&i.Status,
			&i.Subtotal,
			&i.Fee,
			&i.Discount,
			&i.Total,
			&i.ParticipantName,
			&i.ParticipantEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesReportSummary = `-- name: SalesReportSummary :one

SELECT
    COUNT(*)                                              AS total_orders,
    COUNT(*) FILTER (WHERE o.status = 'PAID')             AS paid_orders,
    COUNT(*) FILTER (WHERE o.status = 'PENDING_PAYMENT')  AS pending_orders,
    COUNT(*) FILTER (WHERE o.status = 'EXPIRED')          AS expired_orders,
    COUNT(*) FILTER (WHERE o.status = 'CANCELLED')        AS cancelled_orders,
    COUNT(*) FILTER (WHERE o.status = 'REFUNDED')         AS refunded_orders,
    COALESCE(SUM(o.total) FILTER (WHERE o.status = 'PAID'), 0)::bigint AS gross_paid,
    COALESCE(SUM(o.discount) FILTER (WHERE o.status = 'PAID'), 0)::bigint AS total_discount
FROM orders o
WHERE o.organization_id = $1
  AND ($2::uuid IS NULL OR o.event_id = $2)
`

type SalesReportSummaryParams struct {
	OrganizationID uuid.UUID
	EventID        *uuid.UUID
}

type SalesReportSummaryRow struct {
	TotalOrders     int64
	PaidOrders      int64
	PendingOrders   int64
	ExpiredOrders   int64
	CancelledOrders int64
	RefundedOrders  int64
	GrossPaid       int64
	TotalDiscount   int64
}

// ==========================================================================
// Sales report (orders)
// ==========================================================================
func (q *Queries) SalesReportSummary(ctx context.Context, arg SalesReportSummaryParams) (SalesReportSummaryRow, error) {
	row := q.db.QueryRow(ctx, salesReportSummary, arg.OrganizationID, arg.EventID)
	var i SalesReportSummaryRow
	err := row.Scan(
		&i.TotalOrders,
		&i.PaidOrders,
		&i.PendingOrders,
		&i.ExpiredOrders,
		&i.CancelledOrders,
		&i.RefundedOrders,
		&i.GrossPaid,
		&i.TotalDiscount,
	)
	return i, err
}
