// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const clearRolePermissions = `-- name: ClearRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) ClearRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearRolePermissions, roleID)
	return err
}

const countMembersWithRole = `-- name: CountMembersWithRole :one
SELECT count(*) FROM member_roles WHERE role_id = $1
`

func (q *Queries) CountMembersWithRole(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersWithRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (organization_id, name, slug, is_system)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, name, slug, is_system, created_at
`

type CreateRoleParams struct {
	OrganizationID *uuid.UUID
	Name           string
	Slug           string
	IsSystem       bool
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
		arg.IsSystem,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1 AND organization_id = $2 AND is_system = false
`

type DeleteRoleParams struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.Exec(ctx, deleteRole, arg.ID, arg.OrganizationID)
	return err
}

const getPermissionByKey = `-- name: GetPermissionByKey :one
SELECT id, key, description FROM permissions WHERE key = $1
`

func (q *Queries) GetPermissionByKey(ctx context.Context, key string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByKey, key)
	var i Permission
	err := row.Scan(&i.ID, &i.Key, &i.Description)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, organization_id, name, slug, is_system, created_at FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByOrgAndSlug = `-- name: GetRoleByOrgAndSlug :one
SELECT id, organization_id, name, slug, is_system, created_at FROM roles WHERE organization_id = $1 AND slug = $2
`

type GetRoleByOrgAndSlugParams struct {
	OrganizationID *uuid.UUID
	Slug           string
}

func (q *Queries) GetRoleByOrgAndSlug(ctx context.Context, arg GetRoleByOrgAndSlugParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByOrgAndSlug, arg.OrganizationID, arg.Slug)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, key, description FROM permissions ORDER BY key
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Key, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsForRole = `-- name: ListPermissionsForRole :many
SELECT p.id, p.key, p.description FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
ORDER BY p.key
`

func (q *Queries) ListPermissionsForRole(ctx context.Context, roleID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Key, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByOrg = `-- name: ListRolesByOrg :many
SELECT id, organization_id, name, slug, is_system, created_at FROM roles WHERE organization_id = $1 ORDER BY name
`

func (q *Queries) ListRolesByOrg(ctx context.Context, organizationID *uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateRoles = `-- name: ListTemplateRoles :many
SELECT id, organization_id, name, slug, is_system, created_at FROM roles WHERE organization_id IS NULL ORDER BY name
`

func (q *Queries) ListTemplateRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listTemplateRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoleName = `-- name: UpdateRoleName :one
UPDATE roles SET name = $2 WHERE id = $1 AND organization_id = $3
RETURNING id, organization_id, name, slug, is_system, created_at
`

type UpdateRoleNameParams struct {
	ID             uuid.UUID
	Name           string
	OrganizationID *uuid.UUID
}

func (q *Queries) UpdateRoleName(ctx context.Context, arg UpdateRoleNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRoleName, arg.ID, arg.Name, arg.OrganizationID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}
