// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scanner.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listScannableEventsForUser = `-- name: ListScannableEventsForUser :many
SELECT DISTINCT e.id, e.organization_id, e.name, e.status
FROM events e
JOIN organization_members om ON om.organization_id = e.organization_id
JOIN member_roles mr ON mr.organization_member_id = om.id
JOIN role_permissions rp ON rp.role_id = mr.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE om.user_id = $1
  AND p.key IN ('racepack.execute', 'checkin.execute')
ORDER BY e.name
`

type ListScannableEventsForUserRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Status         string
}

// Returns the set of events (across all of the user's organizations) for which
// the user holds a role granting either `racepack.execute` or `checkin.execute`.
// These are the staff member's Permitted_Events for the Scanner PWA.
func (q *Queries) ListScannableEventsForUser(ctx context.Context, userID uuid.UUID) ([]ListScannableEventsForUserRow, error) {
	rows, err := q.db.Query(ctx, listScannableEventsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScannableEventsForUserRow
	for rows.Next() {
		var i ListScannableEventsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCanScanEvent = `-- name: UserCanScanEvent :one
SELECT EXISTS (
    SELECT 1
    FROM events e
    JOIN organization_members om ON om.organization_id = e.organization_id
    JOIN member_roles mr ON mr.organization_member_id = om.id
    JOIN role_permissions rp ON rp.role_id = mr.role_id
    JOIN permissions p ON p.id = rp.permission_id
    WHERE e.id = $1
      AND om.user_id = $2
      AND p.key IN ('racepack.execute', 'checkin.execute')
) AS can_scan
`

type UserCanScanEventParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Reports whether the user holds `racepack.execute` or `checkin.execute` in the
// organization that owns the given event. Used as the per-operation
// authorization guard (defense-in-depth behind the route RBAC middleware).
func (q *Queries) UserCanScanEvent(ctx context.Context, arg UserCanScanEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, userCanScanEvent, arg.ID, arg.UserID)
	var can_scan bool
	err := row.Scan(&can_scan)
	return can_scan, err
}
