// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (title, impact, status)
VALUES ($1, $2, $3)
RETURNING id, title, impact, status, started_at, resolved_at, created_at, updated_at
`

type CreateIncidentParams struct {
	Title  string
	Impact string
	Status string
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident, arg.Title, arg.Impact, arg.Status)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Impact,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIncidentUpdate = `-- name: CreateIncidentUpdate :one
INSERT INTO incident_updates (incident_id, status, body)
VALUES ($1, $2, $3)
RETURNING id, incident_id, status, body, created_at
`

type CreateIncidentUpdateParams struct {
	IncidentID uuid.UUID
	Status     string
	Body       string
}

func (q *Queries) CreateIncidentUpdate(ctx context.Context, arg CreateIncidentUpdateParams) (IncidentUpdate, error) {
	row := q.db.QueryRow(ctx, createIncidentUpdate, arg.IncidentID, arg.Status, arg.Body)
	var i IncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Status,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getIncident = `-- name: GetIncident :one
SELECT id, title, impact, status, started_at, resolved_at, created_at, updated_at FROM incidents WHERE id = $1
`

func (q *Queries) GetIncident(ctx context.Context, id uuid.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncident, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Impact,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveIncidents = `-- name: ListActiveIncidents :many
SELECT id, title, impact, status, started_at, resolved_at, created_at, updated_at FROM incidents
WHERE resolved_at IS NULL
ORDER BY started_at DESC
`

func (q *Queries) ListActiveIncidents(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listActiveIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Impact,
			&i.Status,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentUpdates = `-- name: ListIncidentUpdates :many
SELECT id, incident_id, status, body, created_at FROM incident_updates
WHERE incident_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListIncidentUpdates(ctx context.Context, incidentID uuid.UUID) ([]IncidentUpdate, error) {
	rows, err := q.db.Query(ctx, listIncidentUpdates, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentUpdate
	for rows.Next() {
		var i IncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Status,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentIncidents = `-- name: ListRecentIncidents :many
SELECT id, title, impact, status, started_at, resolved_at, created_at, updated_at FROM incidents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentIncidentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRecentIncidents(ctx context.Context, arg ListRecentIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listRecentIncidents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Impact,
			&i.Status,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusComponents = `-- name: ListStatusComponents :many
SELECT key, name, status, sort_order, updated_at FROM status_components ORDER BY sort_order, key
`

func (q *Queries) ListStatusComponents(ctx context.Context) ([]StatusComponent, error) {
	rows, err := q.db.Query(ctx, listStatusComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusComponent
	for rows.Next() {
		var i StatusComponent
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Status,
			&i.SortOrder,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpdatesForIncidents = `-- name: ListUpdatesForIncidents :many
SELECT id, incident_id, status, body, created_at FROM incident_updates
WHERE incident_id = ANY($1::uuid[])
ORDER BY created_at DESC
`

func (q *Queries) ListUpdatesForIncidents(ctx context.Context, dollar_1 []uuid.UUID) ([]IncidentUpdate, error) {
	rows, err := q.db.Query(ctx, listUpdatesForIncidents, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentUpdate
	for rows.Next() {
		var i IncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Status,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncidentStatus = `-- name: UpdateIncidentStatus :one
UPDATE incidents
SET status = $2,
    resolved_at = CASE WHEN $2 = 'RESOLVED' THEN now() ELSE resolved_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, title, impact, status, started_at, resolved_at, created_at, updated_at
`

type UpdateIncidentStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateIncidentStatus(ctx context.Context, arg UpdateIncidentStatusParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentStatus, arg.ID, arg.Status)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Impact,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStatusComponent = `-- name: UpdateStatusComponent :one
UPDATE status_components
SET status = $2, updated_at = now()
WHERE key = $1
RETURNING key, name, status, sort_order, updated_at
`

type UpdateStatusComponentParams struct {
	Key    string
	Status string
}

func (q *Queries) UpdateStatusComponent(ctx context.Context, arg UpdateStatusComponentParams) (StatusComponent, error) {
	row := q.db.QueryRow(ctx, updateStatusComponent, arg.Key, arg.Status)
	var i StatusComponent
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Status,
		&i.SortOrder,
		&i.UpdatedAt,
	)
	return i, err
}
