// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const healthPing = `-- name: HealthPing :one
SELECT checked_at FROM schema_health WHERE id = 1
`

func (q *Queries) HealthPing(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, healthPing)
	var checked_at pgtype.Timestamptz
	err := row.Scan(&checked_at)
	return checked_at, err
}
