// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    organization_id, event_id, category_id, order_id, participant_id,
    ticket_number, holder_name, holder_email, event_title, category_name, qr_version
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
ON CONFLICT (order_id) DO NOTHING
RETURNING id, organization_id, event_id, category_id, order_id, participant_id, ticket_number, status, holder_name, holder_email, event_title, category_name, qr_version, issued_at, used_at, created_at, updated_at
`

type CreateTicketParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     uuid.UUID
	OrderID        uuid.UUID
	ParticipantID  uuid.UUID
	TicketNumber   string
	HolderName     string
	HolderEmail    string
	EventTitle     string
	CategoryName   string
	QrVersion      int32
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.OrderID,
		arg.ParticipantID,
		arg.TicketNumber,
		arg.HolderName,
		arg.HolderEmail,
		arg.EventTitle,
		arg.CategoryName,
		arg.QrVersion,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.OrderID,
		&i.ParticipantID,
		&i.TicketNumber,
		&i.Status,
		&i.HolderName,
		&i.HolderEmail,
		&i.EventTitle,
		&i.CategoryName,
		&i.QrVersion,
		&i.IssuedAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, organization_id, event_id, category_id, order_id, participant_id, ticket_number, status, holder_name, holder_email, event_title, category_name, qr_version, issued_at, used_at, created_at, updated_at FROM tickets WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.OrderID,
		&i.ParticipantID,
		&i.TicketNumber,
		&i.Status,
		&i.HolderName,
		&i.HolderEmail,
		&i.EventTitle,
		&i.CategoryName,
		&i.QrVersion,
		&i.IssuedAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByOrderID = `-- name: GetTicketByOrderID :one
SELECT id, organization_id, event_id, category_id, order_id, participant_id, ticket_number, status, holder_name, holder_email, event_title, category_name, qr_version, issued_at, used_at, created_at, updated_at FROM tickets WHERE order_id = $1
`

func (q *Queries) GetTicketByOrderID(ctx context.Context, orderID uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByOrderID, orderID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.OrderID,
		&i.ParticipantID,
		&i.TicketNumber,
		&i.Status,
		&i.HolderName,
		&i.HolderEmail,
		&i.EventTitle,
		&i.CategoryName,
		&i.QrVersion,
		&i.IssuedAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketsByEvent = `-- name: ListTicketsByEvent :many
SELECT id, organization_id, event_id, category_id, order_id, participant_id, ticket_number, status, holder_name, holder_email, event_title, category_name, qr_version, issued_at, used_at, created_at, updated_at FROM tickets
WHERE organization_id = $1 AND event_id = $2
ORDER BY issued_at DESC
`

type ListTicketsByEventParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
}

func (q *Queries) ListTicketsByEvent(ctx context.Context, arg ListTicketsByEventParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByEvent, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.OrderID,
			&i.ParticipantID,
			&i.TicketNumber,
			&i.Status,
			&i.HolderName,
			&i.HolderEmail,
			&i.EventTitle,
			&i.CategoryName,
			&i.QrVersion,
			&i.IssuedAt,
			&i.UsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByParticipant = `-- name: ListTicketsByParticipant :many
SELECT id, organization_id, event_id, category_id, order_id, participant_id, ticket_number, status, holder_name, holder_email, event_title, category_name, qr_version, issued_at, used_at, created_at, updated_at FROM tickets WHERE participant_id = $1 ORDER BY issued_at DESC
`

func (q *Queries) ListTicketsByParticipant(ctx context.Context, participantID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByParticipant, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.OrderID,
			&i.ParticipantID,
			&i.TicketNumber,
			&i.Status,
			&i.HolderName,
			&i.HolderEmail,
			&i.EventTitle,
			&i.CategoryName,
			&i.QrVersion,
			&i.IssuedAt,
			&i.UsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
