// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: timing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPassingsByEvent = `-- name: CountPassingsByEvent :one
SELECT
    count(*) AS total,
    count(*) FILTER (WHERE processed) AS processed_count
FROM timing_passings
WHERE event_id = $1
`

type CountPassingsByEventRow struct {
	Total          int64
	ProcessedCount int64
}

func (q *Queries) CountPassingsByEvent(ctx context.Context, eventID uuid.UUID) (CountPassingsByEventRow, error) {
	row := q.db.QueryRow(ctx, countPassingsByEvent, eventID)
	var i CountPassingsByEventRow
	err := row.Scan(&i.Total, &i.ProcessedCount)
	return i, err
}

const createRaceWave = `-- name: CreateRaceWave :one

INSERT INTO race_waves (
    organization_id, event_id, category_id, code, name, start_at, order_index
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, event_id, category_id, code, name, start_at, order_index, created_at, updated_at
`

type CreateRaceWaveParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CategoryID     *uuid.UUID
	Code           string
	Name           string
	StartAt        pgtype.Timestamptz
	OrderIndex     int32
}

// Race Waves
func (q *Queries) CreateRaceWave(ctx context.Context, arg CreateRaceWaveParams) (RaceWafe, error) {
	row := q.db.QueryRow(ctx, createRaceWave,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.Code,
		arg.Name,
		arg.StartAt,
		arg.OrderIndex,
	)
	var i RaceWafe
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Code,
		&i.Name,
		&i.StartAt,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateBibMappings = `-- name: DeactivateBibMappings :exec
UPDATE bib_transponder_mappings
SET is_active = false, status = 'REPLACED', updated_at = now()
WHERE event_id = $1 AND bib_number = $2 AND is_active = true
`

type DeactivateBibMappingsParams struct {
	EventID   uuid.UUID
	BibNumber string
}

func (q *Queries) DeactivateBibMappings(ctx context.Context, arg DeactivateBibMappingsParams) error {
	_, err := q.db.Exec(ctx, deactivateBibMappings, arg.EventID, arg.BibNumber)
	return err
}

const deactivateChipMappings = `-- name: DeactivateChipMappings :exec
UPDATE bib_transponder_mappings
SET is_active = false, status = 'REPLACED', updated_at = now()
WHERE event_id = $1 AND transponder_code = $2 AND is_active = true
`

type DeactivateChipMappingsParams struct {
	EventID         uuid.UUID
	TransponderCode string
}

func (q *Queries) DeactivateChipMappings(ctx context.Context, arg DeactivateChipMappingsParams) error {
	_, err := q.db.Exec(ctx, deactivateChipMappings, arg.EventID, arg.TransponderCode)
	return err
}

const deleteRaceWave = `-- name: DeleteRaceWave :exec
DELETE FROM race_waves WHERE id = $1 AND event_id = $2
`

type DeleteRaceWaveParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) DeleteRaceWave(ctx context.Context, arg DeleteRaceWaveParams) error {
	_, err := q.db.Exec(ctx, deleteRaceWave, arg.ID, arg.EventID)
	return err
}

const deleteTimingCheckpoint = `-- name: DeleteTimingCheckpoint :exec
DELETE FROM timing_checkpoints WHERE id = $1 AND event_id = $2
`

type DeleteTimingCheckpointParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) DeleteTimingCheckpoint(ctx context.Context, arg DeleteTimingCheckpointParams) error {
	_, err := q.db.Exec(ctx, deleteTimingCheckpoint, arg.ID, arg.EventID)
	return err
}

const getActiveMappingByBib = `-- name: GetActiveMappingByBib :one
SELECT id, organization_id, event_id, bib_number, transponder_code, is_active, status, notes, created_at, updated_at FROM bib_transponder_mappings
WHERE event_id = $1 AND bib_number = $2 AND is_active = true
`

type GetActiveMappingByBibParams struct {
	EventID   uuid.UUID
	BibNumber string
}

func (q *Queries) GetActiveMappingByBib(ctx context.Context, arg GetActiveMappingByBibParams) (BibTransponderMapping, error) {
	row := q.db.QueryRow(ctx, getActiveMappingByBib, arg.EventID, arg.BibNumber)
	var i BibTransponderMapping
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.BibNumber,
		&i.TransponderCode,
		&i.IsActive,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveMappingByChip = `-- name: GetActiveMappingByChip :one
SELECT id, organization_id, event_id, bib_number, transponder_code, is_active, status, notes, created_at, updated_at FROM bib_transponder_mappings
WHERE event_id = $1 AND transponder_code = $2 AND is_active = true
`

type GetActiveMappingByChipParams struct {
	EventID         uuid.UUID
	TransponderCode string
}

func (q *Queries) GetActiveMappingByChip(ctx context.Context, arg GetActiveMappingByChipParams) (BibTransponderMapping, error) {
	row := q.db.QueryRow(ctx, getActiveMappingByChip, arg.EventID, arg.TransponderCode)
	var i BibTransponderMapping
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.BibNumber,
		&i.TransponderCode,
		&i.IsActive,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRaceWaveByID = `-- name: GetRaceWaveByID :one
SELECT id, organization_id, event_id, category_id, code, name, start_at, order_index, created_at, updated_at FROM race_waves WHERE id = $1
`

func (q *Queries) GetRaceWaveByID(ctx context.Context, id uuid.UUID) (RaceWafe, error) {
	row := q.db.QueryRow(ctx, getRaceWaveByID, id)
	var i RaceWafe
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Code,
		&i.Name,
		&i.StartAt,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTimingCheckpointByCode = `-- name: GetTimingCheckpointByCode :one
SELECT id, organization_id, event_id, code, name, checkpoint_type, order_index, distance_meters, created_at, aliases, provider_aliases FROM timing_checkpoints
WHERE event_id = $1 AND code = $2
`

type GetTimingCheckpointByCodeParams struct {
	EventID uuid.UUID
	Code    string
}

func (q *Queries) GetTimingCheckpointByCode(ctx context.Context, arg GetTimingCheckpointByCodeParams) (TimingCheckpoint, error) {
	row := q.db.QueryRow(ctx, getTimingCheckpointByCode, arg.EventID, arg.Code)
	var i TimingCheckpoint
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Code,
		&i.Name,
		&i.CheckpointType,
		&i.OrderIndex,
		&i.DistanceMeters,
		&i.CreatedAt,
		&i.Aliases,
		&i.ProviderAliases,
	)
	return i, err
}

const getTimingConfigByEvent = `-- name: GetTimingConfigByEvent :one
SELECT id, organization_id, event_id, provider, ingestion_token_hash, ingestion_token_prefix, encrypted_api_key, external_race_id, is_active, settings, created_at, updated_at, transport, sync_mode, policy FROM timing_configs WHERE event_id = $1
`

func (q *Queries) GetTimingConfigByEvent(ctx context.Context, eventID uuid.UUID) (TimingConfig, error) {
	row := q.db.QueryRow(ctx, getTimingConfigByEvent, eventID)
	var i TimingConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Provider,
		&i.IngestionTokenHash,
		&i.IngestionTokenPrefix,
		&i.EncryptedApiKey,
		&i.ExternalRaceID,
		&i.IsActive,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Transport,
		&i.SyncMode,
		&i.Policy,
	)
	return i, err
}

const getTimingConfigByTokenHash = `-- name: GetTimingConfigByTokenHash :one
SELECT id, organization_id, event_id, provider, ingestion_token_hash, ingestion_token_prefix, encrypted_api_key, external_race_id, is_active, settings, created_at, updated_at, transport, sync_mode, policy FROM timing_configs
WHERE event_id = $1 AND ingestion_token_hash = $2 AND is_active = true
`

type GetTimingConfigByTokenHashParams struct {
	EventID            uuid.UUID
	IngestionTokenHash string
}

func (q *Queries) GetTimingConfigByTokenHash(ctx context.Context, arg GetTimingConfigByTokenHashParams) (TimingConfig, error) {
	row := q.db.QueryRow(ctx, getTimingConfigByTokenHash, arg.EventID, arg.IngestionTokenHash)
	var i TimingConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Provider,
		&i.IngestionTokenHash,
		&i.IngestionTokenPrefix,
		&i.EncryptedApiKey,
		&i.ExternalRaceID,
		&i.IsActive,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Transport,
		&i.SyncMode,
		&i.Policy,
	)
	return i, err
}

const insertBibTransponderMapping = `-- name: InsertBibTransponderMapping :one

INSERT INTO bib_transponder_mappings (
    organization_id, event_id, bib_number, transponder_code, is_active, status, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, event_id, bib_number, transponder_code, is_active, status, notes, created_at, updated_at
`

type InsertBibTransponderMappingParams struct {
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	BibNumber       string
	TransponderCode string
	IsActive        bool
	Status          string
	Notes           pgtype.Text
}

// BIB Transponder Mappings
func (q *Queries) InsertBibTransponderMapping(ctx context.Context, arg InsertBibTransponderMappingParams) (BibTransponderMapping, error) {
	row := q.db.QueryRow(ctx, insertBibTransponderMapping,
		arg.OrganizationID,
		arg.EventID,
		arg.BibNumber,
		arg.TransponderCode,
		arg.IsActive,
		arg.Status,
		arg.Notes,
	)
	var i BibTransponderMapping
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.BibNumber,
		&i.TransponderCode,
		&i.IsActive,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTimingPassing = `-- name: InsertTimingPassing :one

INSERT INTO timing_passings (
    organization_id, event_id, checkpoint_code, provider,
    external_read_id, chip_code, raw_chip_code, bib_number, observed_at,
    raw_payload, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11
)
ON CONFLICT (event_id, provider, external_read_id) WHERE external_read_id IS NOT NULL
DO NOTHING
RETURNING id, organization_id, event_id, checkpoint_code, provider, external_read_id, chip_code, bib_number, observed_at, received_at, raw_payload, metadata, processed, processed_at, created_at, raw_chip_code
`

type InsertTimingPassingParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CheckpointCode string
	Provider       string
	ExternalReadID pgtype.Text
	ChipCode       string
	RawChipCode    pgtype.Text
	BibNumber      pgtype.Text
	ObservedAt     pgtype.Timestamptz
	RawPayload     pgtype.Text
	Metadata       []byte
}

// Timing Passings
func (q *Queries) InsertTimingPassing(ctx context.Context, arg InsertTimingPassingParams) (TimingPassing, error) {
	row := q.db.QueryRow(ctx, insertTimingPassing,
		arg.OrganizationID,
		arg.EventID,
		arg.CheckpointCode,
		arg.Provider,
		arg.ExternalReadID,
		arg.ChipCode,
		arg.RawChipCode,
		arg.BibNumber,
		arg.ObservedAt,
		arg.RawPayload,
		arg.Metadata,
	)
	var i TimingPassing
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CheckpointCode,
		&i.Provider,
		&i.ExternalReadID,
		&i.ChipCode,
		&i.BibNumber,
		&i.ObservedAt,
		&i.ReceivedAt,
		&i.RawPayload,
		&i.Metadata,
		&i.Processed,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.RawChipCode,
	)
	return i, err
}

const insertTimingPassingFallback = `-- name: InsertTimingPassingFallback :one
INSERT INTO timing_passings (
    organization_id, event_id, checkpoint_code, provider,
    external_read_id, chip_code, raw_chip_code, bib_number, observed_at,
    raw_payload, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11
)
ON CONFLICT (event_id, provider, chip_code, checkpoint_code, observed_at) WHERE external_read_id IS NULL
DO NOTHING
RETURNING id, organization_id, event_id, checkpoint_code, provider, external_read_id, chip_code, bib_number, observed_at, received_at, raw_payload, metadata, processed, processed_at, created_at, raw_chip_code
`

type InsertTimingPassingFallbackParams struct {
	OrganizationID uuid.UUID
	EventID        uuid.UUID
	CheckpointCode string
	Provider       string
	ExternalReadID pgtype.Text
	ChipCode       string
	RawChipCode    pgtype.Text
	BibNumber      pgtype.Text
	ObservedAt     pgtype.Timestamptz
	RawPayload     pgtype.Text
	Metadata       []byte
}

func (q *Queries) InsertTimingPassingFallback(ctx context.Context, arg InsertTimingPassingFallbackParams) (TimingPassing, error) {
	row := q.db.QueryRow(ctx, insertTimingPassingFallback,
		arg.OrganizationID,
		arg.EventID,
		arg.CheckpointCode,
		arg.Provider,
		arg.ExternalReadID,
		arg.ChipCode,
		arg.RawChipCode,
		arg.BibNumber,
		arg.ObservedAt,
		arg.RawPayload,
		arg.Metadata,
	)
	var i TimingPassing
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CheckpointCode,
		&i.Provider,
		&i.ExternalReadID,
		&i.ChipCode,
		&i.BibNumber,
		&i.ObservedAt,
		&i.ReceivedAt,
		&i.RawPayload,
		&i.Metadata,
		&i.Processed,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.RawChipCode,
	)
	return i, err
}

const listMappingsByEvent = `-- name: ListMappingsByEvent :many
SELECT id, organization_id, event_id, bib_number, transponder_code, is_active, status, notes, created_at, updated_at FROM bib_transponder_mappings
WHERE event_id = $1
ORDER BY bib_number ASC, created_at DESC
`

func (q *Queries) ListMappingsByEvent(ctx context.Context, eventID uuid.UUID) ([]BibTransponderMapping, error) {
	rows, err := q.db.Query(ctx, listMappingsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BibTransponderMapping
	for rows.Next() {
		var i BibTransponderMapping
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.BibNumber,
			&i.TransponderCode,
			&i.IsActive,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRaceWavesByEvent = `-- name: ListRaceWavesByEvent :many
SELECT id, organization_id, event_id, category_id, code, name, start_at, order_index, created_at, updated_at FROM race_waves
WHERE event_id = $1
ORDER BY order_index ASC, created_at ASC
`

func (q *Queries) ListRaceWavesByEvent(ctx context.Context, eventID uuid.UUID) ([]RaceWafe, error) {
	rows, err := q.db.Query(ctx, listRaceWavesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RaceWafe
	for rows.Next() {
		var i RaceWafe
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.CategoryID,
			&i.Code,
			&i.Name,
			&i.StartAt,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSplitsByResult = `-- name: ListSplitsByResult :many
SELECT s.id, s.race_result_id, s.checkpoint_id, s.passing_id, s.split_time_ms, s.split_pace_ms_km, s.passing_time, s.order_index, s.created_at, c.code AS checkpoint_code, c.name AS checkpoint_name, c.distance_meters
FROM race_split_times s
JOIN timing_checkpoints c ON s.checkpoint_id = c.id
WHERE s.race_result_id = $1
ORDER BY s.order_index ASC
`

type ListSplitsByResultRow struct {
	ID             uuid.UUID
	RaceResultID   uuid.UUID
	CheckpointID   uuid.UUID
	PassingID      pgtype.Int8
	SplitTimeMs    int64
	SplitPaceMsKm  pgtype.Int8
	PassingTime    pgtype.Timestamptz
	OrderIndex     int32
	CreatedAt      pgtype.Timestamptz
	CheckpointCode string
	CheckpointName string
	DistanceMeters pgtype.Int4
}

func (q *Queries) ListSplitsByResult(ctx context.Context, raceResultID uuid.UUID) ([]ListSplitsByResultRow, error) {
	rows, err := q.db.Query(ctx, listSplitsByResult, raceResultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSplitsByResultRow
	for rows.Next() {
		var i ListSplitsByResultRow
		if err := rows.Scan(
			&i.ID,
			&i.RaceResultID,
			&i.CheckpointID,
			&i.PassingID,
			&i.SplitTimeMs,
			&i.SplitPaceMsKm,
			&i.PassingTime,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.CheckpointCode,
			&i.CheckpointName,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimingCheckpointsByEvent = `-- name: ListTimingCheckpointsByEvent :many
SELECT id, organization_id, event_id, code, name, checkpoint_type, order_index, distance_meters, created_at, aliases, provider_aliases FROM timing_checkpoints
WHERE event_id = $1
ORDER BY order_index ASC
`

func (q *Queries) ListTimingCheckpointsByEvent(ctx context.Context, eventID uuid.UUID) ([]TimingCheckpoint, error) {
	rows, err := q.db.Query(ctx, listTimingCheckpointsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimingCheckpoint
	for rows.Next() {
		var i TimingCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.Code,
			&i.Name,
			&i.CheckpointType,
			&i.OrderIndex,
			&i.DistanceMeters,
			&i.CreatedAt,
			&i.Aliases,
			&i.ProviderAliases,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedPassings = `-- name: ListUnprocessedPassings :many
SELECT id, organization_id, event_id, checkpoint_code, provider, external_read_id, chip_code, bib_number, observed_at, received_at, raw_payload, metadata, processed, processed_at, created_at, raw_chip_code FROM timing_passings
WHERE event_id = $1 AND NOT processed
ORDER BY observed_at ASC
LIMIT $2
`

type ListUnprocessedPassingsParams struct {
	EventID uuid.UUID
	Limit   int32
}

func (q *Queries) ListUnprocessedPassings(ctx context.Context, arg ListUnprocessedPassingsParams) ([]TimingPassing, error) {
	rows, err := q.db.Query(ctx, listUnprocessedPassings, arg.EventID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimingPassing
	for rows.Next() {
		var i TimingPassing
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.CheckpointCode,
			&i.Provider,
			&i.ExternalReadID,
			&i.ChipCode,
			&i.BibNumber,
			&i.ObservedAt,
			&i.ReceivedAt,
			&i.RawPayload,
			&i.Metadata,
			&i.Processed,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.RawChipCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPassingsProcessed = `-- name: MarkPassingsProcessed :exec
UPDATE timing_passings
SET processed = true, processed_at = now()
WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkPassingsProcessed(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, markPassingsProcessed, dollar_1)
	return err
}

const setTicketWave = `-- name: SetTicketWave :exec

UPDATE tickets
SET wave_id = $2, updated_at = now()
WHERE id = $1
`

type SetTicketWaveParams struct {
	ID     uuid.UUID
	WaveID *uuid.UUID
}

// Tickets Wave linking
func (q *Queries) SetTicketWave(ctx context.Context, arg SetTicketWaveParams) error {
	_, err := q.db.Exec(ctx, setTicketWave, arg.ID, arg.WaveID)
	return err
}

const updateRaceWave = `-- name: UpdateRaceWave :one
UPDATE race_waves
SET name = $3, start_at = $4, order_index = $5, updated_at = now()
WHERE id = $1 AND event_id = $2
RETURNING id, organization_id, event_id, category_id, code, name, start_at, order_index, created_at, updated_at
`

type UpdateRaceWaveParams struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	Name       string
	StartAt    pgtype.Timestamptz
	OrderIndex int32
}

func (q *Queries) UpdateRaceWave(ctx context.Context, arg UpdateRaceWaveParams) (RaceWafe, error) {
	row := q.db.QueryRow(ctx, updateRaceWave,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.StartAt,
		arg.OrderIndex,
	)
	var i RaceWafe
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.Code,
		&i.Name,
		&i.StartAt,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRaceSplitTime = `-- name: UpsertRaceSplitTime :one

INSERT INTO race_split_times (
    race_result_id, checkpoint_id, passing_id, split_time_ms,
    split_pace_ms_km, passing_time, order_index
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (race_result_id, checkpoint_id) DO UPDATE SET
    passing_id       = EXCLUDED.passing_id,
    split_time_ms    = EXCLUDED.split_time_ms,
    split_pace_ms_km = EXCLUDED.split_pace_ms_km,
    passing_time     = EXCLUDED.passing_time,
    order_index      = EXCLUDED.order_index
RETURNING id, race_result_id, checkpoint_id, passing_id, split_time_ms, split_pace_ms_km, passing_time, order_index, created_at
`

type UpsertRaceSplitTimeParams struct {
	RaceResultID  uuid.UUID
	CheckpointID  uuid.UUID
	PassingID     pgtype.Int8
	SplitTimeMs   int64
	SplitPaceMsKm pgtype.Int8
	PassingTime   pgtype.Timestamptz
	OrderIndex    int32
}

// Race Split Times
func (q *Queries) UpsertRaceSplitTime(ctx context.Context, arg UpsertRaceSplitTimeParams) (RaceSplitTime, error) {
	row := q.db.QueryRow(ctx, upsertRaceSplitTime,
		arg.RaceResultID,
		arg.CheckpointID,
		arg.PassingID,
		arg.SplitTimeMs,
		arg.SplitPaceMsKm,
		arg.PassingTime,
		arg.OrderIndex,
	)
	var i RaceSplitTime
	err := row.Scan(
		&i.ID,
		&i.RaceResultID,
		&i.CheckpointID,
		&i.PassingID,
		&i.SplitTimeMs,
		&i.SplitPaceMsKm,
		&i.PassingTime,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTimingCheckpoint = `-- name: UpsertTimingCheckpoint :one

INSERT INTO timing_checkpoints (
    organization_id, event_id, code, name, checkpoint_type, order_index, distance_meters,
    aliases, provider_aliases
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (event_id, code) DO UPDATE SET
    name             = EXCLUDED.name,
    checkpoint_type  = EXCLUDED.checkpoint_type,
    order_index      = EXCLUDED.order_index,
    distance_meters  = EXCLUDED.distance_meters,
    aliases          = EXCLUDED.aliases,
    provider_aliases = EXCLUDED.provider_aliases
RETURNING id, organization_id, event_id, code, name, checkpoint_type, order_index, distance_meters, created_at, aliases, provider_aliases
`

type UpsertTimingCheckpointParams struct {
	OrganizationID  uuid.UUID
	EventID         uuid.UUID
	Code            string
	Name            string
	CheckpointType  string
	OrderIndex      int32
	DistanceMeters  pgtype.Int4
	Aliases         []string
	ProviderAliases []byte
}

// Timing Checkpoints
func (q *Queries) UpsertTimingCheckpoint(ctx context.Context, arg UpsertTimingCheckpointParams) (TimingCheckpoint, error) {
	row := q.db.QueryRow(ctx, upsertTimingCheckpoint,
		arg.OrganizationID,
		arg.EventID,
		arg.Code,
		arg.Name,
		arg.CheckpointType,
		arg.OrderIndex,
		arg.DistanceMeters,
		arg.Aliases,
		arg.ProviderAliases,
	)
	var i TimingCheckpoint
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Code,
		&i.Name,
		&i.CheckpointType,
		&i.OrderIndex,
		&i.DistanceMeters,
		&i.CreatedAt,
		&i.Aliases,
		&i.ProviderAliases,
	)
	return i, err
}

const upsertTimingConfig = `-- name: UpsertTimingConfig :one

INSERT INTO timing_configs (
    organization_id, event_id, provider, transport, sync_mode, policy,
    ingestion_token_hash, ingestion_token_prefix, encrypted_api_key,
    external_race_id, is_active, settings
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12
)
ON CONFLICT (event_id) DO UPDATE SET
    provider               = EXCLUDED.provider,
    transport              = EXCLUDED.transport,
    sync_mode              = EXCLUDED.sync_mode,
    policy                 = EXCLUDED.policy,
    ingestion_token_hash   = EXCLUDED.ingestion_token_hash,
    ingestion_token_prefix = EXCLUDED.ingestion_token_prefix,
    encrypted_api_key      = EXCLUDED.encrypted_api_key,
    external_race_id       = EXCLUDED.external_race_id,
    is_active              = EXCLUDED.is_active,
    settings               = EXCLUDED.settings,
    updated_at             = now()
RETURNING id, organization_id, event_id, provider, ingestion_token_hash, ingestion_token_prefix, encrypted_api_key, external_race_id, is_active, settings, created_at, updated_at, transport, sync_mode, policy
`

type UpsertTimingConfigParams struct {
	OrganizationID       uuid.UUID
	EventID              uuid.UUID
	Provider             string
	Transport            string
	SyncMode             string
	Policy               []byte
	IngestionTokenHash   string
	IngestionTokenPrefix string
	EncryptedApiKey      pgtype.Text
	ExternalRaceID       pgtype.Text
	IsActive             bool
	Settings             []byte
}

// Timing Configs
func (q *Queries) UpsertTimingConfig(ctx context.Context, arg UpsertTimingConfigParams) (TimingConfig, error) {
	row := q.db.QueryRow(ctx, upsertTimingConfig,
		arg.OrganizationID,
		arg.EventID,
		arg.Provider,
		arg.Transport,
		arg.SyncMode,
		arg.Policy,
		arg.IngestionTokenHash,
		arg.IngestionTokenPrefix,
		arg.EncryptedApiKey,
		arg.ExternalRaceID,
		arg.IsActive,
		arg.Settings,
	)
	var i TimingConfig
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.Provider,
		&i.IngestionTokenHash,
		&i.IngestionTokenPrefix,
		&i.EncryptedApiKey,
		&i.ExternalRaceID,
		&i.IsActive,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Transport,
		&i.SyncMode,
		&i.Policy,
	)
	return i, err
}
