// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waitlist.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWaitlistPosition = `-- name: CountWaitlistPosition :one
SELECT count(*) FROM waitlist_entries
WHERE waitlist_id = $1 AND status = 'WAITING' AND rank < $2
`

type CountWaitlistPositionParams struct {
	WaitlistID uuid.UUID
	Rank       int64
}

func (q *Queries) CountWaitlistPosition(ctx context.Context, arg CountWaitlistPositionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitlistPosition, arg.WaitlistID, arg.Rank)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWaitlist = `-- name: CreateWaitlist :one
INSERT INTO waitlists
    (organization_id, event_id, category_id, mode, max_promotion_batch,
     promotion_window_hours, auto_promote)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, event_id, category_id, pool_id, mode, status, max_promotion_batch, promotion_window_hours, auto_promote, seed, created_at
`

type CreateWaitlistParams struct {
	OrganizationID       uuid.UUID
	EventID              uuid.UUID
	CategoryID           uuid.UUID
	Mode                 string
	MaxPromotionBatch    int32
	PromotionWindowHours int32
	AutoPromote          bool
}

func (q *Queries) CreateWaitlist(ctx context.Context, arg CreateWaitlistParams) (Waitlist, error) {
	row := q.db.QueryRow(ctx, createWaitlist,
		arg.OrganizationID,
		arg.EventID,
		arg.CategoryID,
		arg.Mode,
		arg.MaxPromotionBatch,
		arg.PromotionWindowHours,
		arg.AutoPromote,
	)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.PoolID,
		&i.Mode,
		&i.Status,
		&i.MaxPromotionBatch,
		&i.PromotionWindowHours,
		&i.AutoPromote,
		&i.Seed,
		&i.CreatedAt,
	)
	return i, err
}

const getWaitlist = `-- name: GetWaitlist :one
SELECT id, organization_id, event_id, category_id, pool_id, mode, status, max_promotion_batch, promotion_window_hours, auto_promote, seed, created_at FROM waitlists WHERE id = $1
`

func (q *Queries) GetWaitlist(ctx context.Context, id uuid.UUID) (Waitlist, error) {
	row := q.db.QueryRow(ctx, getWaitlist, id)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.PoolID,
		&i.Mode,
		&i.Status,
		&i.MaxPromotionBatch,
		&i.PromotionWindowHours,
		&i.AutoPromote,
		&i.Seed,
		&i.CreatedAt,
	)
	return i, err
}

const getWaitlistByCategory = `-- name: GetWaitlistByCategory :one
SELECT id, organization_id, event_id, category_id, pool_id, mode, status, max_promotion_batch, promotion_window_hours, auto_promote, seed, created_at FROM waitlists
WHERE event_id = $1 AND category_id = $2 AND status = 'ACTIVE'
LIMIT 1
`

type GetWaitlistByCategoryParams struct {
	EventID    uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) GetWaitlistByCategory(ctx context.Context, arg GetWaitlistByCategoryParams) (Waitlist, error) {
	row := q.db.QueryRow(ctx, getWaitlistByCategory, arg.EventID, arg.CategoryID)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.CategoryID,
		&i.PoolID,
		&i.Mode,
		&i.Status,
		&i.MaxPromotionBatch,
		&i.PromotionWindowHours,
		&i.AutoPromote,
		&i.Seed,
		&i.CreatedAt,
	)
	return i, err
}

const getWaitlistEntry = `-- name: GetWaitlistEntry :one
SELECT id, waitlist_id, participant_id, event_id, category_id, source, source_ref_id, status, rank, notified_at, promoted_at, access_grant_id, promotion_window_hours, created_at FROM waitlist_entries
WHERE waitlist_id = $1 AND participant_id = $2 AND status NOT IN ('WITHDRAWN','EXPIRED')
LIMIT 1
`

type GetWaitlistEntryParams struct {
	WaitlistID    uuid.UUID
	ParticipantID uuid.UUID
}

func (q *Queries) GetWaitlistEntry(ctx context.Context, arg GetWaitlistEntryParams) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, getWaitlistEntry, arg.WaitlistID, arg.ParticipantID)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.WaitlistID,
		&i.ParticipantID,
		&i.EventID,
		&i.CategoryID,
		&i.Source,
		&i.SourceRefID,
		&i.Status,
		&i.Rank,
		&i.NotifiedAt,
		&i.PromotedAt,
		&i.AccessGrantID,
		&i.PromotionWindowHours,
		&i.CreatedAt,
	)
	return i, err
}

const joinWaitlist = `-- name: JoinWaitlist :one
INSERT INTO waitlist_entries
    (waitlist_id, participant_id, event_id, category_id, source, source_ref_id,
     rank, promotion_window_hours)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, waitlist_id, participant_id, event_id, category_id, source, source_ref_id, status, rank, notified_at, promoted_at, access_grant_id, promotion_window_hours, created_at
`

type JoinWaitlistParams struct {
	WaitlistID           uuid.UUID
	ParticipantID        uuid.UUID
	EventID              uuid.UUID
	CategoryID           uuid.UUID
	Source               string
	SourceRefID          *uuid.UUID
	Rank                 int64
	PromotionWindowHours pgtype.Int4
}

func (q *Queries) JoinWaitlist(ctx context.Context, arg JoinWaitlistParams) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, joinWaitlist,
		arg.WaitlistID,
		arg.ParticipantID,
		arg.EventID,
		arg.CategoryID,
		arg.Source,
		arg.SourceRefID,
		arg.Rank,
		arg.PromotionWindowHours,
	)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.WaitlistID,
		&i.ParticipantID,
		&i.EventID,
		&i.CategoryID,
		&i.Source,
		&i.SourceRefID,
		&i.Status,
		&i.Rank,
		&i.NotifiedAt,
		&i.PromotedAt,
		&i.AccessGrantID,
		&i.PromotionWindowHours,
		&i.CreatedAt,
	)
	return i, err
}

const listWaitingEntries = `-- name: ListWaitingEntries :many
SELECT id, waitlist_id, participant_id, event_id, category_id, source, source_ref_id, status, rank, notified_at, promoted_at, access_grant_id, promotion_window_hours, created_at FROM waitlist_entries
WHERE waitlist_id = $1 AND status = 'WAITING'
ORDER BY rank ASC
LIMIT $2
`

type ListWaitingEntriesParams struct {
	WaitlistID uuid.UUID
	Limit      int32
}

func (q *Queries) ListWaitingEntries(ctx context.Context, arg ListWaitingEntriesParams) ([]WaitlistEntry, error) {
	rows, err := q.db.Query(ctx, listWaitingEntries, arg.WaitlistID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaitlistEntry
	for rows.Next() {
		var i WaitlistEntry
		if err := rows.Scan(
			&i.ID,
			&i.WaitlistID,
			&i.ParticipantID,
			&i.EventID,
			&i.CategoryID,
			&i.Source,
			&i.SourceRefID,
			&i.Status,
			&i.Rank,
			&i.NotifiedAt,
			&i.PromotedAt,
			&i.AccessGrantID,
			&i.PromotionWindowHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWaitlistPool = `-- name: SetWaitlistPool :exec
UPDATE waitlists SET pool_id = $2 WHERE id = $1
`

type SetWaitlistPoolParams struct {
	ID     uuid.UUID
	PoolID *uuid.UUID
}

func (q *Queries) SetWaitlistPool(ctx context.Context, arg SetWaitlistPoolParams) error {
	_, err := q.db.Exec(ctx, setWaitlistPool, arg.ID, arg.PoolID)
	return err
}

const setWaitlistSeed = `-- name: SetWaitlistSeed :exec
UPDATE waitlists SET seed = $2 WHERE id = $1 AND seed IS NULL
`

type SetWaitlistSeedParams struct {
	ID   uuid.UUID
	Seed pgtype.Text
}

func (q *Queries) SetWaitlistSeed(ctx context.Context, arg SetWaitlistSeedParams) error {
	_, err := q.db.Exec(ctx, setWaitlistSeed, arg.ID, arg.Seed)
	return err
}

const updateWaitlistEntryStatus = `-- name: UpdateWaitlistEntryStatus :one
UPDATE waitlist_entries
SET status = $2,
    promoted_at = CASE WHEN $2 = 'PROMOTED' THEN now() ELSE promoted_at END,
    access_grant_id = COALESCE($3, access_grant_id)
WHERE id = $1
RETURNING id, waitlist_id, participant_id, event_id, category_id, source, source_ref_id, status, rank, notified_at, promoted_at, access_grant_id, promotion_window_hours, created_at
`

type UpdateWaitlistEntryStatusParams struct {
	ID            uuid.UUID
	Status        string
	AccessGrantID *uuid.UUID
}

func (q *Queries) UpdateWaitlistEntryStatus(ctx context.Context, arg UpdateWaitlistEntryStatusParams) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, updateWaitlistEntryStatus, arg.ID, arg.Status, arg.AccessGrantID)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.WaitlistID,
		&i.ParticipantID,
		&i.EventID,
		&i.CategoryID,
		&i.Source,
		&i.SourceRefID,
		&i.Status,
		&i.Rank,
		&i.NotifiedAt,
		&i.PromotedAt,
		&i.AccessGrantID,
		&i.PromotionWindowHours,
		&i.CreatedAt,
	)
	return i, err
}

const updateWaitlistStatus = `-- name: UpdateWaitlistStatus :exec
UPDATE waitlists SET status = $2 WHERE id = $1
`

type UpdateWaitlistStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateWaitlistStatus(ctx context.Context, arg UpdateWaitlistStatusParams) error {
	_, err := q.db.Exec(ctx, updateWaitlistStatus, arg.ID, arg.Status)
	return err
}
