// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: whitelabel.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCustomDomain = `-- name: CreateCustomDomain :one
INSERT INTO custom_domains (organization_id, domain, verification_token, status)
VALUES ($1, $2, $3, 'PENDING')
RETURNING id, organization_id, domain, verification_token, status, verified_at, created_at, updated_at
`

type CreateCustomDomainParams struct {
	OrganizationID    uuid.UUID
	Domain            string
	VerificationToken string
}

func (q *Queries) CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, createCustomDomain, arg.OrganizationID, arg.Domain, arg.VerificationToken)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Domain,
		&i.VerificationToken,
		&i.Status,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomDomain = `-- name: DeleteCustomDomain :exec
DELETE FROM custom_domains WHERE id = $1 AND organization_id = $2
`

type DeleteCustomDomainParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteCustomDomain(ctx context.Context, arg DeleteCustomDomainParams) error {
	_, err := q.db.Exec(ctx, deleteCustomDomain, arg.ID, arg.OrganizationID)
	return err
}

const getCustomDomain = `-- name: GetCustomDomain :one
SELECT id, organization_id, domain, verification_token, status, verified_at, created_at, updated_at FROM custom_domains WHERE id = $1
`

func (q *Queries) GetCustomDomain(ctx context.Context, id uuid.UUID) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, getCustomDomain, id)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Domain,
		&i.VerificationToken,
		&i.Status,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomDomainByName = `-- name: GetCustomDomainByName :one
SELECT id, organization_id, domain, verification_token, status, verified_at, created_at, updated_at FROM custom_domains WHERE domain = $1
`

func (q *Queries) GetCustomDomainByName(ctx context.Context, domain string) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, getCustomDomainByName, domain)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Domain,
		&i.VerificationToken,
		&i.Status,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgBranding = `-- name: GetOrgBranding :one
SELECT organization_id, logo_object_key, theme_color, email_from_name, email_from_address, terms_text, footer_text, whitelabel_enabled, created_at, updated_at FROM org_branding WHERE organization_id = $1
`

func (q *Queries) GetOrgBranding(ctx context.Context, organizationID uuid.UUID) (OrgBranding, error) {
	row := q.db.QueryRow(ctx, getOrgBranding, organizationID)
	var i OrgBranding
	err := row.Scan(
		&i.OrganizationID,
		&i.LogoObjectKey,
		&i.ThemeColor,
		&i.EmailFromName,
		&i.EmailFromAddress,
		&i.TermsText,
		&i.FooterText,
		&i.WhitelabelEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomDomainsByOrg = `-- name: ListCustomDomainsByOrg :many
SELECT id, organization_id, domain, verification_token, status, verified_at, created_at, updated_at FROM custom_domains
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCustomDomainsByOrg(ctx context.Context, organizationID uuid.UUID) ([]CustomDomain, error) {
	rows, err := q.db.Query(ctx, listCustomDomainsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomDomain
	for rows.Next() {
		var i CustomDomain
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Domain,
			&i.VerificationToken,
			&i.Status,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCustomDomainFailed = `-- name: MarkCustomDomainFailed :one
UPDATE custom_domains
SET status = 'FAILED', updated_at = now()
WHERE id = $1
RETURNING id, organization_id, domain, verification_token, status, verified_at, created_at, updated_at
`

func (q *Queries) MarkCustomDomainFailed(ctx context.Context, id uuid.UUID) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, markCustomDomainFailed, id)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Domain,
		&i.VerificationToken,
		&i.Status,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCustomDomainVerified = `-- name: MarkCustomDomainVerified :one
UPDATE custom_domains
SET status = 'VERIFIED', verified_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, organization_id, domain, verification_token, status, verified_at, created_at, updated_at
`

func (q *Queries) MarkCustomDomainVerified(ctx context.Context, id uuid.UUID) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, markCustomDomainVerified, id)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Domain,
		&i.VerificationToken,
		&i.Status,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrgBranding = `-- name: UpsertOrgBranding :one
INSERT INTO org_branding (
    organization_id, logo_object_key, theme_color, email_from_name,
    email_from_address, terms_text, footer_text, whitelabel_enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (organization_id) DO UPDATE
SET logo_object_key    = EXCLUDED.logo_object_key,
    theme_color        = EXCLUDED.theme_color,
    email_from_name    = EXCLUDED.email_from_name,
    email_from_address = EXCLUDED.email_from_address,
    terms_text         = EXCLUDED.terms_text,
    footer_text        = EXCLUDED.footer_text,
    whitelabel_enabled = EXCLUDED.whitelabel_enabled,
    updated_at         = now()
RETURNING organization_id, logo_object_key, theme_color, email_from_name, email_from_address, terms_text, footer_text, whitelabel_enabled, created_at, updated_at
`

type UpsertOrgBrandingParams struct {
	OrganizationID    uuid.UUID
	LogoObjectKey     string
	ThemeColor        string
	EmailFromName     string
	EmailFromAddress  string
	TermsText         string
	FooterText        string
	WhitelabelEnabled bool
}

func (q *Queries) UpsertOrgBranding(ctx context.Context, arg UpsertOrgBrandingParams) (OrgBranding, error) {
	row := q.db.QueryRow(ctx, upsertOrgBranding,
		arg.OrganizationID,
		arg.LogoObjectKey,
		arg.ThemeColor,
		arg.EmailFromName,
		arg.EmailFromAddress,
		arg.TermsText,
		arg.FooterText,
		arg.WhitelabelEnabled,
	)
	var i OrgBranding
	err := row.Scan(
		&i.OrganizationID,
		&i.LogoObjectKey,
		&i.ThemeColor,
		&i.EmailFromName,
		&i.EmailFromAddress,
		&i.TermsText,
		&i.FooterText,
		&i.WhitelabelEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
